import type { LineKind } from "@/lib/pomodoro/simulated-voice"

/**
 * The fixed lines a made-up member says when there is no AI key, a call
 * fails, or a written line fails the checks twice (live activity task 03).
 * They follow the default never-say list: no cheering, no line ending in an
 * exclamation mark. A greeting cannot see the room's phase, so none of them
 * says "starting soon" or "we're on a break". `{name}` is the real person's
 * first name and `{them}` the name of whoever the line answers.
 */
export const FIXED_LINES: Record<LineKind, readonly string[]> = {
  open: [
    "ok starting in a few min",
    "room's open, join whenever",
    "starting soon. bring coffee",
    "opening this up for a bit",
    "here for a couple hours probably",
    "quiet room, come work",
    "giving this another go today",
    "few minutes then we start",
    "back at it",
    "doors open",
    "ok. first one soon",
    "settling in",
  ],
  focus: [
    "ok back to it",
    "starting the next one",
    "round two",
    "alright, heads down",
    "back in",
    "here we go again",
    "ok focus time",
    "next one starting",
    "back to the doc",
    "one more",
    "phone face down",
    "and again",
  ],
  break: [
    "break",
    "stretching",
    "getting water",
    "that one went fast",
    "refilling coffee",
    "ok short break",
    "eyes need a rest",
    "standing up for a sec",
    "half done with this thing",
    "that was a slog",
    "made some progress at least",
    "five min",
  ],
  greet: [
    "hey {name}",
    "hi {name}",
    "hey, welcome",
    "oh hey {name}",
    "welcome in",
    "hey. grab a seat",
    "hi {name}, good timing",
    "hey hey",
    "hello {name}",
    "hey, glad someone else is up",
  ],
  reply: [
    "same honestly",
    "yep",
    "ha, same here",
    "relatable",
    "one more round then",
    "coffee is the answer",
    "felt that",
    "mood",
    "i'm barely holding on too",
    "true",
    "same boat",
    "slowly getting there",
  ],
  mention: [
    "yeah?",
    "hey, what's up",
    "here",
    "yep, still going",
    "ha, yes",
    "hm?",
    "still here",
    "sorry, was in the zone",
    "what's up {them}",
    "yes",
    "i'm here",
    "hey {them}",
  ],
  exchange: [
    "anyone else dying",
    "how's everyone's thing going",
    "this chapter will not end",
    "third coffee",
    "my brain is soup",
    "what's everyone working on",
    "yep. coffee number three",
    "slowly. very slowly",
    "same",
    "barely",
    "inbox, forever",
    "ok getting there",
  ],
  leave: [
    "gotta run",
    "ok that's me for now",
    "heading out, thanks all",
    "need to go, later",
    "that's my lot",
    "off to a meeting",
    "calling it here",
    "bye all",
    "lunch time for me",
    "ok signing off",
    "running out, see you",
    "done for now",
  ],
}
