"use client"

import { useState, useEffect } from "react"
import { 
  Dialog,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import {
  AdminModalBody,
  AdminModalContent,
  AdminModalFooter,
  AdminModalHeader,
  AdminModalTitle,
} from "@/components/admin/shared/AdminModalLayout"
import {
  Field,
  FieldContent,
  FieldDescription,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field"
import { MediaPicker } from "@/components/admin/media-library/MediaPicker"
import { RichTextEditor } from "@/components/admin/shared/RichTextEditor"
import { CategoryPicker } from "@/components/admin/shared/CategoryPicker"
import { ImageIcon, X, Check } from "lucide-react"
import { getContentCategoriesAction, bulkAssignCategoriesToContentAction } from "@/lib/actions/categories/category-relationship-actions"
import { generateSlug } from "@/lib/utils/slug"
import type { Product, UpdateProductData } from "@/lib/actions/products/product-actions"
import type { SiteWithTheme } from "@/lib/actions/sites/site-actions"

interface ProductSettingsModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  product: Product | null
  site: SiteWithTheme | null
  onSuccess?: (updatedProduct: Product) => void
}

export function ProductSettingsModal({ 
  open, 
  onOpenChange, 
  product, 
  site,
  onSuccess 
}: ProductSettingsModalProps) {
  const [formData, setFormData] = useState<UpdateProductData>({})
  const [richTextContent, setRichTextContent] = useState('')
  const [featuredImage, setFeaturedImage] = useState('')
  const [isPrivate, setIsPrivate] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [saveMessage, setSaveMessage] = useState<string | null>(null)
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false)
  const [showImagePicker, setShowImagePicker] = useState(false)
  const [isSaved, setIsSaved] = useState(false)
  const [selectedCategoryIds, setSelectedCategoryIds] = useState<string[]>([])

  // Handle title change and auto-generate slug if slug hasn't been manually edited
  const handleTitleChange = (title: string) => {
    setIsSaved(false)
    setFormData(prev => ({
      ...prev,
      title,
      slug: slugManuallyEdited ? prev.slug : generateSlug(title)
    }))
  }

  // Handle manual slug changes
  const handleSlugChange = (slug: string) => {
    setIsSaved(false)
    if (slug === '') {
      // If user clears the field, reset to auto-generation
      setSlugManuallyEdited(false)
      setFormData(prev => ({ ...prev, slug: generateSlug(prev.title || '') }))
    } else {
      setSlugManuallyEdited(true)
      setFormData(prev => ({ ...prev, slug }))
    }
  }

  // Handle featured image changes
  const handleImageChange = async (newImageUrl: string) => {
    setIsSaved(false)
    setFeaturedImage(newImageUrl)
  }

  // Handle removing the featured image
  const handleRemoveImage = async () => {
    setIsSaved(false)
    setFeaturedImage('')
  }


  // Initialize form data when product changes
  useEffect(() => {
    if (product) {
      setFormData({
        title: product.title,
        slug: product.slug,
        is_published: product.is_published
      })
      
      // Get is_private from content_blocks
      setIsPrivate(product.content_blocks?._settings?.is_private === true)
      
      // Get content from product columns
      setRichTextContent(product.description || '')
      setFeaturedImage(product.featured_image || '')
      
      // Check if slug was manually edited (different from auto-generated)
      const autoGeneratedSlug = generateSlug(product.title)
      setSlugManuallyEdited(product.slug !== autoGeneratedSlug)
      
      // Reset states
      setError(null)
      setSaveMessage(null)

      // Fetch existing category assignments
      getContentCategoriesAction(product.id, 'product').then(({ data }) => {
        if (data) {
          setSelectedCategoryIds(data.map((c) => c.id))
        }
      })
    }
  }, [product])


  // Handle saving as draft
  const handleSaveDraft = async () => {
    if (!formData.title?.trim()) {
      setError('Product title is required')
      return
    }

    if (!product) {
      setError('No product selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)
      
      const draftData = { 
        ...formData, 
        is_published: false,
        featured_image: featuredImage || null,
        description: richTextContent || null,
        content_blocks: {
          ...product.content_blocks,
          _settings: {
            ...product.content_blocks?._settings,
            is_private: isPrivate
          }
        }
      }
      
      const response = await fetch(`/api/products/${product.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(draftData),
      })
      
      const result = await response.json()
      
      if (!response.ok || result.error) {
        setError(result.error || 'Failed to save product as draft')
        return
      }
      
      if (result.data) {
        if (selectedCategoryIds.length > 0) {
          bulkAssignCategoriesToContentAction(result.data.id, 'product', selectedCategoryIds).catch(() => {})
        }
        setSaveMessage('Product saved as draft successfully!')
        setIsSaved(true)
        
        // Call success callback with updated product
        if (onSuccess) {
          onSuccess(result.data)
        }
        
        // Clear success message after 3 seconds but keep modal open
        setTimeout(() => {
          setSaveMessage(null)
        }, 3000)
      }
    } catch (err) {
      setError('Failed to save product as draft')
    } finally {
      setSaving(false)
    }
  }

  // Handle publishing
  const handlePublish = async () => {
    if (!formData.title?.trim()) {
      setError('Product title is required')
      return
    }

    if (!product) {
      setError('No product selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)
      
      const publishData = { 
        ...formData, 
        is_published: true,
        featured_image: featuredImage || null,
        description: richTextContent || null,
        content_blocks: {
          ...product.content_blocks,
          _settings: {
            ...product.content_blocks?._settings,
            is_private: isPrivate
          }
        }
      }
      
      const response = await fetch(`/api/products/${product.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(publishData),
      })
      
      const result = await response.json()
      
      if (!response.ok || result.error) {
        setError(result.error || 'Failed to publish product')
        return
      }
      
      if (result.data) {
        if (selectedCategoryIds.length > 0) {
          bulkAssignCategoriesToContentAction(result.data.id, 'product', selectedCategoryIds).catch(() => {})
        }
        setSaveMessage(product?.is_published ? 'Product saved successfully!' : 'Product published successfully!')
        setIsSaved(true)
        
        // Call success callback with updated product
        if (onSuccess) {
          onSuccess(result.data)
        }
        
        // Clear success message after 3 seconds but keep modal open
        setTimeout(() => {
          setSaveMessage(null)
        }, 3000)
      }
    } catch (err) {
      setError('Failed to publish product')
    } finally {
      setSaving(false)
    }
  }

  // Handle form submission (default to save as draft)
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    await handleSaveDraft()
  }

  if (!product) {
    return null
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <AdminModalContent>
        <AdminModalHeader>
          <AdminModalTitle className="flex items-center gap-3">
            Configure settings for &quot;{product.title}&quot;
            <div className="flex items-center space-x-2">
              <div className={`w-2 h-2 rounded-full ${
                product?.is_published ? 'bg-green-500' : 'bg-gray-400'
              }`} />
              <span className="text-sm font-medium">
                {product?.is_published ? 'Published' : 'Draft'}
              </span>
            </div>
          </AdminModalTitle>
        </AdminModalHeader>

        <form onSubmit={handleSubmit} className="flex min-h-0 flex-1 flex-col">
          <AdminModalBody>
            <div className="space-y-4">
              {error && (
                <div className="rounded-lg border border-red-200 bg-red-50 p-3">
                  <p className="text-sm text-red-800">{error}</p>
                </div>
              )}

              {saveMessage && (
                <div className="rounded-lg border border-green-200 bg-green-50 p-3">
                  <p className="text-sm text-green-800">{saveMessage}</p>
                </div>
              )}
            </div>

            <FieldGroup className="gap-6">
              <Field>
                <FieldLabel htmlFor="modal-title">Product Title *</FieldLabel>
                <Input
                  id="modal-title"
                  value={formData.title || ''}
                  onChange={(e) => handleTitleChange(e.target.value)}
                  placeholder="Enter product title"
                  required
                />
              </Field>

              <Field>
                <FieldLabel htmlFor="modal-slug">Product URL</FieldLabel>
                <Input
                  id="modal-slug"
                  value={formData.slug || ''}
                  onChange={(e) => handleSlugChange(e.target.value)}
                  placeholder="product-url-slug"
                />
                <FieldDescription>
                  {slugManuallyEdited
                    ? "Custom URL slug. Clear this field to auto-generate from title again."
                    : "Auto-generated from title. You can edit this to customize the URL."}
                </FieldDescription>
              </Field>

              <Field className="*:data-[slot=field-label]:w-fit *:data-[slot=field-description]:max-w-md [&>div]:w-fit">
                <FieldLabel>Featured Image</FieldLabel>
                {featuredImage ? (
                  <div className="relative h-48 w-48 overflow-hidden rounded-lg bg-muted">
                    <img
                      src={featuredImage}
                      alt="Featured image preview"
                      className="h-full w-full object-contain"
                    />
                    <div className="absolute inset-0 bg-linear-to-t from-background/80 to-transparent" />
                    <button
                      type="button"
                      onClick={handleRemoveImage}
                      className="absolute top-2 right-2 rounded-full bg-red-500 p-1 text-white transition-colors hover:bg-red-600"
                    >
                      <X className="h-4 w-4" />
                    </button>
                    <div
                      className="absolute inset-0 flex cursor-pointer items-center justify-center bg-black/50 opacity-0 transition-opacity hover:opacity-100"
                      onClick={() => setShowImagePicker(true)}
                    >
                      <div className="text-center text-white">
                        <ImageIcon className="mx-auto mb-2 h-8 w-8" />
                        <p className="text-sm font-medium">Click to change image</p>
                      </div>
                    </div>
                  </div>
                ) : (
                  <div
                    className="flex h-48 w-48 cursor-pointer items-center justify-center rounded-lg border-2 border-dashed border-muted-foreground/25 bg-muted/50 transition-all hover:border-muted-foreground/40 hover:bg-muted/70"
                    onClick={() => setShowImagePicker(true)}
                  >
                    <div className="text-center">
                      <ImageIcon className="mx-auto h-8 w-8 text-muted-foreground/50" />
                      <p className="mt-2 text-sm text-muted-foreground">Click to select featured image</p>
                    </div>
                  </div>
                )}
                <FieldDescription>
                  Optional featured image for this product.
                </FieldDescription>
              </Field>

              <Field>
                <FieldLabel>Privacy Settings</FieldLabel>
                <Field orientation="horizontal" className="items-start gap-3">
                  <Checkbox
                    id="modal-is-private"
                    checked={isPrivate}
                    onCheckedChange={(checked) => {
                      setIsSaved(false)
                      setIsPrivate(!!checked)
                    }}
                  />
                  <FieldContent>
                    <FieldLabel htmlFor="modal-is-private" className="font-normal">
                      Private
                    </FieldLabel>
                    <FieldDescription>
                      Accessible only by direct URL and hidden from product listings.
                    </FieldDescription>
                  </FieldContent>
                </Field>
              </Field>

              {product.site_id && (
                <Field>
                  <FieldLabel>Categories</FieldLabel>
                  <CategoryPicker
                    siteId={product.site_id}
                    selectedCategoryIds={selectedCategoryIds}
                    onSelectionChange={setSelectedCategoryIds}
                  />
                  <FieldDescription>
                    Assign this product to one or more categories.
                  </FieldDescription>
                </Field>
              )}

              <Field>
                <FieldLabel htmlFor="rich_text">Product Description</FieldLabel>
                <RichTextEditor
                  content={{
                    content: richTextContent,
                    hideHeader: true,
                    hideEditorHeader: true
                  }}
                  onContentChange={(content) => {
                    setIsSaved(false)
                    setRichTextContent(content.content)
                  }}
                  compact={true}
                  inline={true}
                />
                <FieldDescription>
                  Rich text content for the product description. This is saved into the product content.
                </FieldDescription>
              </Field>
            </FieldGroup>
          </AdminModalBody>

          <AdminModalFooter>
            <Button 
              type="button" 
              variant="outline" 
              onClick={() => onOpenChange(false)}
              disabled={saving}
            >
              Cancel
            </Button>
            <div className="flex items-center space-x-2">
              {isSaved && (
                <div className="flex items-center space-x-1 text-green-600">
                  <Check className="h-4 w-4" />
                  <span className="text-sm font-medium">Saved!</span>
                </div>
              )}
              <Button 
                type="submit" 
                variant="outline"
                disabled={saving}
              >
                {saving ? "Saving..." : "Save as Draft"}
              </Button>
              <Button 
                type="button" 
                onClick={handlePublish}
                disabled={saving}
              >
                {saving ? "Saving..." : product?.is_published ? "Save" : "Publish"}
              </Button>
            </div>
          </AdminModalFooter>
        </form>

        {/* Image Picker Modal */}
        <MediaPicker
          open={showImagePicker}
          onOpenChange={setShowImagePicker}
          onSelectMedia={(imageUrl) => {
            handleImageChange(imageUrl)
            setShowImagePicker(false)
          }}
          currentMediaUrl={featuredImage || ''}
        />
      </AdminModalContent>
    </Dialog>
  )
}
