"use client"

import { useState, useEffect } from "react"
import { Dialog } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardGroup, CardHeader } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field"
import { DashboardModalCardTitle, DashboardModalContent, DashboardModalFooterActions } from "@/components/admin/layout/dashboard/modals"
import { generateSlug } from "@/lib/utils/slug"
import type { Page, UpdatePageData } from "@/lib/actions/pages/page-actions"
import type { SiteWithTheme } from "@/lib/actions/sites/site-actions"

interface PageSettingsModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  page: Page | null
  site: SiteWithTheme | null
  onSuccess?: (updatedPage: Page) => void
}

export function PageSettingsModal({
  open,
  onOpenChange,
  page,
  onSuccess,
}: PageSettingsModalProps) {
  const [formData, setFormData] = useState<UpdatePageData>({})
  const [savingAction, setSavingAction] = useState<"draft" | "publish" | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false)
  const saving = savingAction !== null

  const handleTitleChange = (title: string) => {
    setFormData((prev) => ({
      ...prev,
      title,
      slug: slugManuallyEdited ? prev.slug : generateSlug(title),
    }))
  }

  const handleSlugChange = (slug: string) => {
    if (slug === "") {
      setSlugManuallyEdited(false)
      setFormData((prev) => ({ ...prev, slug: generateSlug(prev.title || "") }))
      return
    }

    setSlugManuallyEdited(true)
    setFormData((prev) => ({ ...prev, slug }))
  }

  useEffect(() => {
    if (!page) return

    setFormData({
      title: page.title,
      slug: page.slug,
      meta_description: page.meta_description || "",
      is_homepage: page.is_homepage,
      is_published: page.is_published,
    })

    const autoGeneratedSlug = generateSlug(page.title)
    setSlugManuallyEdited(page.slug !== autoGeneratedSlug)
    setError(null)
  }, [page])

  useEffect(() => {
    if (!open) {
      setError(null)
    }
  }, [open])

  const handleSaveDraft = async () => {
    if (!formData.title?.trim()) {
      setError("Page title is required")
      return
    }

    if (!page) {
      setError("No page selected")
      return
    }

    try {
      setSavingAction("draft")
      setError(null)

      const draftData = { ...formData, is_published: false }
      const response = await fetch(`/api/pages/${page.id}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(draftData),
      })

      const result = await response.json()

      if (!response.ok || result.error) {
        setError(result.error || "Failed to save page as draft")
        return
      }

      if (result.data) {
        onSuccess?.(result.data)
        onOpenChange(false)
      }
    } catch (err) {
      setError("Failed to save page as draft")
    } finally {
      setSavingAction(null)
    }
  }

  const handlePublish = async () => {
    if (!formData.title?.trim()) {
      setError("Page title is required")
      return
    }

    if (!page) {
      setError("No page selected")
      return
    }

    try {
      setSavingAction("publish")
      setError(null)

      const publishData = { ...formData, is_published: true }
      const response = await fetch(`/api/pages/${page.id}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(publishData),
      })

      const result = await response.json()

      if (!response.ok || result.error) {
        setError(result.error || "Failed to publish page")
        return
      }

      if (result.data) {
        setFormData((prev) => ({ ...prev, is_published: true }))
        onSuccess?.(result.data)
        onOpenChange(false)
      }
    } catch (err) {
      setError("Failed to publish page")
    } finally {
      setSavingAction(null)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    await handleSaveDraft()
  }

  if (!page) {
    return null
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <form id="page-settings-form" onSubmit={handleSubmit} className="contents">
        <DashboardModalContent
          title={
            <span className="flex items-center gap-3">
              Configure settings for &quot;{page.title}&quot;
              <span className="flex items-center space-x-2">
                <span className={`h-2 w-2 rounded-full ${page.is_published ? "bg-green-500" : "bg-gray-400"}`} />
                <span className="text-sm font-medium">{page.is_published ? "Published" : "Draft"}</span>
              </span>
            </span>
          }
          footer={
            <>
              <div />
              <DashboardModalFooterActions>
                <Button type="button" variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>
                  Cancel
                </Button>
                <Button form="page-settings-form" type="submit" variant="outline" disabled={saving}>
                  {savingAction === "draft" ? "Saving..." : "Save as Draft"}
                </Button>
                <Button type="button" onClick={handlePublish} disabled={saving}>
                  {savingAction === "publish" ? (page.is_published ? "Saving..." : "Publishing...") : page.is_published ? "Save" : "Publish"}
                </Button>
              </DashboardModalFooterActions>
            </>
          }
          footerClassName="sm:justify-between"
        >
          {error && (
            <div className="px-6 pb-2">
              <div className="rounded-lg border border-red-200 bg-red-50 p-3">
                <p className="text-sm text-red-800">{error}</p>
              </div>
            </div>
          )}

          <CardGroup className="grid">
            <Card>
              <CardHeader>
                <DashboardModalCardTitle>Page setup</DashboardModalCardTitle>
              </CardHeader>
              <CardContent>
                <Field>
                  <FieldLabel htmlFor="modal-title">Page Title *</FieldLabel>
                  <Input
                    id="modal-title"
                    value={formData.title || ""}
                    onChange={(e) => handleTitleChange(e.target.value)}
                    placeholder="Enter page title"
                    required
                  />
                </Field>

                <Field>
                  <FieldLabel htmlFor="modal-slug">Page URL</FieldLabel>
                  <Input
                    id="modal-slug"
                    value={formData.slug || ""}
                    onChange={(e) => handleSlugChange(e.target.value)}
                    placeholder="page-url-slug"
                  />
                  <FieldDescription>
                    {slugManuallyEdited
                      ? "Custom URL slug. Clear this field to auto-generate from title again."
                      : "Auto-generated from title. You can edit this to customize the URL."}
                  </FieldDescription>
                </Field>

                <Field>
                  <label className="flex cursor-pointer items-center gap-2">
                    <Checkbox
                      id="modal-is_homepage"
                      checked={formData.is_homepage === true}
                      onCheckedChange={(checked) =>
                        setFormData((prev) => ({ ...prev, is_homepage: checked === true }))
                      }
                    />
                    <span className="text-sm font-medium">Set as homepage</span>
                  </label>
                  <FieldDescription>This page will be the main landing page for your site</FieldDescription>
                </Field>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <DashboardModalCardTitle>SEO</DashboardModalCardTitle>
              </CardHeader>
              <CardContent>
                <Field>
                  <FieldLabel htmlFor="modal-meta_description">Meta Description</FieldLabel>
                  <Textarea
                    id="modal-meta_description"
                    value={formData.meta_description || ""}
                    onChange={(e) => setFormData((prev) => ({ ...prev, meta_description: e.target.value }))}
                    placeholder="A brief description of this page for search engines"
                    rows={1}
                    className="min-h-10 field-sizing-content"
                  />
                  <FieldDescription>
                    Recommended length: 150-160 characters ({(formData.meta_description || "").length}/160)
                  </FieldDescription>
                </Field>
              </CardContent>
            </Card>
          </CardGroup>
        </DashboardModalContent>
      </form>
    </Dialog>
  )
}
