/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAlertLogRouteImport } from './routes/_authenticated/alert-log'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedIndicatorsRouteImport } from './routes/_authenticated/indicators'
import { Route as AuthenticatedPnlRouteImport } from './routes/_authenticated/pnl'
import { Route as AuthenticatedTradeRouteImport } from './routes/_authenticated/trade'
import { Route as AuthenticatedWalletsRouteImport } from './routes/_authenticated/wallets'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin/feedback'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAutomationsIndexRouteImport } from './routes/_authenticated/automations/index'
import { Route as AuthenticatedAutomationsAutomationIdRouteImport } from './routes/_authenticated/automations/$automationId'
import { Route as AuthenticatedBacktestIndexRouteImport } from './routes/_authenticated/backtest/index'
import { Route as AuthenticatedBacktestGroupIdRouteImport } from './routes/_authenticated/backtest/$groupId'
import { Route as AuthenticatedBacktestPracticeRouteImport } from './routes/_authenticated/backtest/practice'
import { Route as AuthenticatedBotsIndexRouteImport } from './routes/_authenticated/bots/index'
import { Route as AuthenticatedBotsBotIdRouteImport } from './routes/_authenticated/bots/$botId'
import { Route as AuthenticatedScannerIndexRouteImport } from './routes/_authenticated/scanner/index'
import { Route as AuthenticatedScannerBookRouteImport } from './routes/_authenticated/scanner/book'
import { Route as AuthenticatedScannerCrowdedRouteImport } from './routes/_authenticated/scanner/crowded'
import { Route as AuthenticatedScannerLeaderboardRouteImport } from './routes/_authenticated/scanner/leaderboard'
import { Route as AuthenticatedScannerMarketRouteImport } from './routes/_authenticated/scanner/market'
import { Route as AuthenticatedScannerMarketAlertsRouteImport } from './routes/_authenticated/scanner/market-alerts'
import { Route as AuthenticatedScannerPositionsRouteImport } from './routes/_authenticated/scanner/positions'
import { Route as AuthenticatedScannerWhaleTradesRouteImport } from './routes/_authenticated/scanner/whale-trades'
import { Route as AuthenticatedScannerWhalesRouteRouteImport } from './routes/_authenticated/scanner/whales/route'
import { Route as AuthenticatedAdminFeedbackCommentsRouteImport } from './routes/_authenticated/admin/feedback/comments'
import { Route as AuthenticatedAdminSettingsTabRouteImport } from './routes/_authenticated/admin/settings/$tab'
import { Route as AuthenticatedScannerWhalesIndexRouteImport } from './routes/_authenticated/scanner/whales/index'
import { Route as AuthenticatedScannerWhalesAddressRouteImport } from './routes/_authenticated/scanner/whales/$address'
import { Route as ApiV1MediaMediaIdFileRouteImport } from './routes/api/v1/media/$mediaId/file'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertLogRoute = AuthenticatedAlertLogRouteImport.update({
  id: '/alert-log',
  path: '/alert-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIndicatorsRoute = AuthenticatedIndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPnlRoute = AuthenticatedPnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradeRoute = AuthenticatedTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWalletsRoute = AuthenticatedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/admin/feedback',
    path: '/admin/feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutomationsIndexRoute =
  AuthenticatedAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutomationsAutomationIdRoute =
  AuthenticatedAutomationsAutomationIdRouteImport.update({
    id: '/automations/$automationId',
    path: '/automations/$automationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBacktestIndexRoute =
  AuthenticatedBacktestIndexRouteImport.update({
    id: '/backtest/',
    path: '/backtest/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBacktestGroupIdRoute =
  AuthenticatedBacktestGroupIdRouteImport.update({
    id: '/backtest/$groupId',
    path: '/backtest/$groupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBacktestPracticeRoute =
  AuthenticatedBacktestPracticeRouteImport.update({
    id: '/backtest/practice',
    path: '/backtest/practice',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBotsIndexRoute = AuthenticatedBotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBotsBotIdRoute = AuthenticatedBotsBotIdRouteImport.update({
  id: '/bots/$botId',
  path: '/bots/$botId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScannerIndexRoute =
  AuthenticatedScannerIndexRouteImport.update({
    id: '/scanner/',
    path: '/scanner/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScannerBookRoute =
  AuthenticatedScannerBookRouteImport.update({
    id: '/scanner/book',
    path: '/scanner/book',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScannerCrowdedRoute =
  AuthenticatedScannerCrowdedRouteImport.update({
    id: '/scanner/crowded',
    path: '/scanner/crowded',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScannerLeaderboardRoute =
  AuthenticatedScannerLeaderboardRouteImport.update({
    id: '/scanner/leaderboard',
    path: '/scanner/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScannerMarketRoute =
  AuthenticatedScannerMarketRouteImport.update({
    id: '/scanner/market',
    path: '/scanner/market',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScannerMarketAlertsRoute =
  AuthenticatedScannerMarketAlertsRouteImport.update({
    id: '/scanner/market-alerts',
    path: '/scanner/market-alerts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScannerPositionsRoute =
  AuthenticatedScannerPositionsRouteImport.update({
    id: '/scanner/positions',
    path: '/scanner/positions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScannerWhaleTradesRoute =
  AuthenticatedScannerWhaleTradesRouteImport.update({
    id: '/scanner/whale-trades',
    path: '/scanner/whale-trades',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScannerWhalesRouteRoute =
  AuthenticatedScannerWhalesRouteRouteImport.update({
    id: '/scanner/whales',
    path: '/scanner/whales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFeedbackCommentsRoute =
  AuthenticatedAdminFeedbackCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminFeedbackRoute,
  } as any)
const AuthenticatedAdminSettingsTabRoute =
  AuthenticatedAdminSettingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedScannerWhalesIndexRoute =
  AuthenticatedScannerWhalesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedScannerWhalesRouteRoute,
  } as any)
const AuthenticatedScannerWhalesAddressRoute =
  AuthenticatedScannerWhalesAddressRouteImport.update({
    id: '/$address',
    path: '/$address',
    getParentRoute: () => AuthenticatedScannerWhalesRouteRoute,
  } as any)
const ApiV1MediaMediaIdFileRoute = ApiV1MediaMediaIdFileRouteImport.update({
  id: '/api/v1/media/$mediaId/file',
  path: '/api/v1/media/$mediaId/file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/alert-log': typeof AuthenticatedAlertLogRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/indicators': typeof AuthenticatedIndicatorsRoute
  '/pnl': typeof AuthenticatedPnlRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/scanner/whales': typeof AuthenticatedScannerWhalesRouteRouteWithChildren
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/automations/$automationId': typeof AuthenticatedAutomationsAutomationIdRoute
  '/backtest/$groupId': typeof AuthenticatedBacktestGroupIdRoute
  '/backtest/practice': typeof AuthenticatedBacktestPracticeRoute
  '/bots/$botId': typeof AuthenticatedBotsBotIdRoute
  '/scanner/book': typeof AuthenticatedScannerBookRoute
  '/scanner/crowded': typeof AuthenticatedScannerCrowdedRoute
  '/scanner/leaderboard': typeof AuthenticatedScannerLeaderboardRoute
  '/scanner/market': typeof AuthenticatedScannerMarketRoute
  '/scanner/market-alerts': typeof AuthenticatedScannerMarketAlertsRoute
  '/scanner/positions': typeof AuthenticatedScannerPositionsRoute
  '/scanner/whale-trades': typeof AuthenticatedScannerWhaleTradesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/backtest/': typeof AuthenticatedBacktestIndexRoute
  '/bots/': typeof AuthenticatedBotsIndexRoute
  '/scanner/': typeof AuthenticatedScannerIndexRoute
  '/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/scanner/whales/$address': typeof AuthenticatedScannerWhalesAddressRoute
  '/scanner/whales/': typeof AuthenticatedScannerWhalesIndexRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/alert-log': typeof AuthenticatedAlertLogRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/indicators': typeof AuthenticatedIndicatorsRoute
  '/pnl': typeof AuthenticatedPnlRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/automations/$automationId': typeof AuthenticatedAutomationsAutomationIdRoute
  '/backtest/$groupId': typeof AuthenticatedBacktestGroupIdRoute
  '/backtest/practice': typeof AuthenticatedBacktestPracticeRoute
  '/bots/$botId': typeof AuthenticatedBotsBotIdRoute
  '/scanner/book': typeof AuthenticatedScannerBookRoute
  '/scanner/crowded': typeof AuthenticatedScannerCrowdedRoute
  '/scanner/leaderboard': typeof AuthenticatedScannerLeaderboardRoute
  '/scanner/market': typeof AuthenticatedScannerMarketRoute
  '/scanner/market-alerts': typeof AuthenticatedScannerMarketAlertsRoute
  '/scanner/positions': typeof AuthenticatedScannerPositionsRoute
  '/scanner/whale-trades': typeof AuthenticatedScannerWhaleTradesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/automations': typeof AuthenticatedAutomationsIndexRoute
  '/backtest': typeof AuthenticatedBacktestIndexRoute
  '/bots': typeof AuthenticatedBotsIndexRoute
  '/scanner': typeof AuthenticatedScannerIndexRoute
  '/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/scanner/whales/$address': typeof AuthenticatedScannerWhalesAddressRoute
  '/scanner/whales': typeof AuthenticatedScannerWhalesIndexRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/alert-log': typeof AuthenticatedAlertLogRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/indicators': typeof AuthenticatedIndicatorsRoute
  '/_authenticated/pnl': typeof AuthenticatedPnlRoute
  '/_authenticated/trade': typeof AuthenticatedTradeRoute
  '/_authenticated/wallets': typeof AuthenticatedWalletsRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/scanner/whales': typeof AuthenticatedScannerWhalesRouteRouteWithChildren
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/automations/$automationId': typeof AuthenticatedAutomationsAutomationIdRoute
  '/_authenticated/backtest/$groupId': typeof AuthenticatedBacktestGroupIdRoute
  '/_authenticated/backtest/practice': typeof AuthenticatedBacktestPracticeRoute
  '/_authenticated/bots/$botId': typeof AuthenticatedBotsBotIdRoute
  '/_authenticated/scanner/book': typeof AuthenticatedScannerBookRoute
  '/_authenticated/scanner/crowded': typeof AuthenticatedScannerCrowdedRoute
  '/_authenticated/scanner/leaderboard': typeof AuthenticatedScannerLeaderboardRoute
  '/_authenticated/scanner/market': typeof AuthenticatedScannerMarketRoute
  '/_authenticated/scanner/market-alerts': typeof AuthenticatedScannerMarketAlertsRoute
  '/_authenticated/scanner/positions': typeof AuthenticatedScannerPositionsRoute
  '/_authenticated/scanner/whale-trades': typeof AuthenticatedScannerWhaleTradesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/_authenticated/backtest/': typeof AuthenticatedBacktestIndexRoute
  '/_authenticated/bots/': typeof AuthenticatedBotsIndexRoute
  '/_authenticated/scanner/': typeof AuthenticatedScannerIndexRoute
  '/_authenticated/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/_authenticated/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/_authenticated/scanner/whales/$address': typeof AuthenticatedScannerWhalesAddressRoute
  '/_authenticated/scanner/whales/': typeof AuthenticatedScannerWhalesIndexRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alert-log'
    | '/alerts'
    | '/audit'
    | '/indicators'
    | '/pnl'
    | '/trade'
    | '/wallets'
    | '/workspaces'
    | '/scanner/whales'
    | '/admin/feedback'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/settings'
    | '/automations/$automationId'
    | '/backtest/$groupId'
    | '/backtest/practice'
    | '/bots/$botId'
    | '/scanner/book'
    | '/scanner/crowded'
    | '/scanner/leaderboard'
    | '/scanner/market'
    | '/scanner/market-alerts'
    | '/scanner/positions'
    | '/scanner/whale-trades'
    | '/admin/'
    | '/automations/'
    | '/backtest/'
    | '/bots/'
    | '/scanner/'
    | '/admin/feedback/comments'
    | '/admin/settings/$tab'
    | '/scanner/whales/$address'
    | '/scanner/whales/'
    | '/api/v1/media/$mediaId/file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/alert-log'
    | '/alerts'
    | '/audit'
    | '/indicators'
    | '/pnl'
    | '/trade'
    | '/wallets'
    | '/workspaces'
    | '/'
    | '/admin/feedback'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/settings'
    | '/automations/$automationId'
    | '/backtest/$groupId'
    | '/backtest/practice'
    | '/bots/$botId'
    | '/scanner/book'
    | '/scanner/crowded'
    | '/scanner/leaderboard'
    | '/scanner/market'
    | '/scanner/market-alerts'
    | '/scanner/positions'
    | '/scanner/whale-trades'
    | '/admin'
    | '/automations'
    | '/backtest'
    | '/bots'
    | '/scanner'
    | '/admin/feedback/comments'
    | '/admin/settings/$tab'
    | '/scanner/whales/$address'
    | '/scanner/whales'
    | '/api/v1/media/$mediaId/file'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/alert-log'
    | '/_authenticated/alerts'
    | '/_authenticated/audit'
    | '/_authenticated/indicators'
    | '/_authenticated/pnl'
    | '/_authenticated/trade'
    | '/_authenticated/wallets'
    | '/_authenticated/workspaces'
    | '/_authenticated/'
    | '/_authenticated/scanner/whales'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/settings'
    | '/_authenticated/automations/$automationId'
    | '/_authenticated/backtest/$groupId'
    | '/_authenticated/backtest/practice'
    | '/_authenticated/bots/$botId'
    | '/_authenticated/scanner/book'
    | '/_authenticated/scanner/crowded'
    | '/_authenticated/scanner/leaderboard'
    | '/_authenticated/scanner/market'
    | '/_authenticated/scanner/market-alerts'
    | '/_authenticated/scanner/positions'
    | '/_authenticated/scanner/whale-trades'
    | '/_authenticated/admin/'
    | '/_authenticated/automations/'
    | '/_authenticated/backtest/'
    | '/_authenticated/bots/'
    | '/_authenticated/scanner/'
    | '/_authenticated/admin/feedback/comments'
    | '/_authenticated/admin/settings/$tab'
    | '/_authenticated/scanner/whales/$address'
    | '/_authenticated/scanner/whales/'
    | '/api/v1/media/$mediaId/file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiV1MediaMediaIdFileRoute: typeof ApiV1MediaMediaIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alert-log': {
      id: '/_authenticated/alert-log'
      path: '/alert-log'
      fullPath: '/alert-log'
      preLoaderRoute: typeof AuthenticatedAlertLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indicators': {
      id: '/_authenticated/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof AuthenticatedIndicatorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pnl': {
      id: '/_authenticated/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof AuthenticatedPnlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trade': {
      id: '/_authenticated/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AuthenticatedTradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wallets': {
      id: '/_authenticated/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations/': {
      id: '/_authenticated/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AuthenticatedAutomationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automations/$automationId': {
      id: '/_authenticated/automations/$automationId'
      path: '/automations/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof AuthenticatedAutomationsAutomationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backtest/': {
      id: '/_authenticated/backtest/'
      path: '/backtest'
      fullPath: '/backtest/'
      preLoaderRoute: typeof AuthenticatedBacktestIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backtest/$groupId': {
      id: '/_authenticated/backtest/$groupId'
      path: '/backtest/$groupId'
      fullPath: '/backtest/$groupId'
      preLoaderRoute: typeof AuthenticatedBacktestGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backtest/practice': {
      id: '/_authenticated/backtest/practice'
      path: '/backtest/practice'
      fullPath: '/backtest/practice'
      preLoaderRoute: typeof AuthenticatedBacktestPracticeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bots/': {
      id: '/_authenticated/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof AuthenticatedBotsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bots/$botId': {
      id: '/_authenticated/bots/$botId'
      path: '/bots/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof AuthenticatedBotsBotIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner/': {
      id: '/_authenticated/scanner/'
      path: '/scanner'
      fullPath: '/scanner/'
      preLoaderRoute: typeof AuthenticatedScannerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner/book': {
      id: '/_authenticated/scanner/book'
      path: '/scanner/book'
      fullPath: '/scanner/book'
      preLoaderRoute: typeof AuthenticatedScannerBookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner/crowded': {
      id: '/_authenticated/scanner/crowded'
      path: '/scanner/crowded'
      fullPath: '/scanner/crowded'
      preLoaderRoute: typeof AuthenticatedScannerCrowdedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner/leaderboard': {
      id: '/_authenticated/scanner/leaderboard'
      path: '/scanner/leaderboard'
      fullPath: '/scanner/leaderboard'
      preLoaderRoute: typeof AuthenticatedScannerLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner/market': {
      id: '/_authenticated/scanner/market'
      path: '/scanner/market'
      fullPath: '/scanner/market'
      preLoaderRoute: typeof AuthenticatedScannerMarketRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner/market-alerts': {
      id: '/_authenticated/scanner/market-alerts'
      path: '/scanner/market-alerts'
      fullPath: '/scanner/market-alerts'
      preLoaderRoute: typeof AuthenticatedScannerMarketAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner/positions': {
      id: '/_authenticated/scanner/positions'
      path: '/scanner/positions'
      fullPath: '/scanner/positions'
      preLoaderRoute: typeof AuthenticatedScannerPositionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner/whale-trades': {
      id: '/_authenticated/scanner/whale-trades'
      path: '/scanner/whale-trades'
      fullPath: '/scanner/whale-trades'
      preLoaderRoute: typeof AuthenticatedScannerWhaleTradesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner/whales': {
      id: '/_authenticated/scanner/whales'
      path: '/scanner/whales'
      fullPath: '/scanner/whales'
      preLoaderRoute: typeof AuthenticatedScannerWhalesRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/feedback/comments': {
      id: '/_authenticated/admin/feedback/comments'
      path: '/comments'
      fullPath: '/admin/feedback/comments'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminFeedbackRoute
    }
    '/_authenticated/admin/settings/$tab': {
      id: '/_authenticated/admin/settings/$tab'
      path: '/$tab'
      fullPath: '/admin/settings/$tab'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTabRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/scanner/whales/': {
      id: '/_authenticated/scanner/whales/'
      path: '/'
      fullPath: '/scanner/whales/'
      preLoaderRoute: typeof AuthenticatedScannerWhalesIndexRouteImport
      parentRoute: typeof AuthenticatedScannerWhalesRouteRoute
    }
    '/_authenticated/scanner/whales/$address': {
      id: '/_authenticated/scanner/whales/$address'
      path: '/$address'
      fullPath: '/scanner/whales/$address'
      preLoaderRoute: typeof AuthenticatedScannerWhalesAddressRouteImport
      parentRoute: typeof AuthenticatedScannerWhalesRouteRoute
    }
    '/api/v1/media/$mediaId/file': {
      id: '/api/v1/media/$mediaId/file'
      path: '/api/v1/media/$mediaId/file'
      fullPath: '/api/v1/media/$mediaId/file'
      preLoaderRoute: typeof ApiV1MediaMediaIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedScannerWhalesRouteRouteChildren {
  AuthenticatedScannerWhalesAddressRoute: typeof AuthenticatedScannerWhalesAddressRoute
  AuthenticatedScannerWhalesIndexRoute: typeof AuthenticatedScannerWhalesIndexRoute
}

const AuthenticatedScannerWhalesRouteRouteChildren: AuthenticatedScannerWhalesRouteRouteChildren =
  {
    AuthenticatedScannerWhalesAddressRoute:
      AuthenticatedScannerWhalesAddressRoute,
    AuthenticatedScannerWhalesIndexRoute: AuthenticatedScannerWhalesIndexRoute,
  }

const AuthenticatedScannerWhalesRouteRouteWithChildren =
  AuthenticatedScannerWhalesRouteRoute._addFileChildren(
    AuthenticatedScannerWhalesRouteRouteChildren,
  )

interface AuthenticatedAdminFeedbackRouteChildren {
  AuthenticatedAdminFeedbackCommentsRoute: typeof AuthenticatedAdminFeedbackCommentsRoute
}

const AuthenticatedAdminFeedbackRouteChildren: AuthenticatedAdminFeedbackRouteChildren =
  {
    AuthenticatedAdminFeedbackCommentsRoute:
      AuthenticatedAdminFeedbackCommentsRoute,
  }

const AuthenticatedAdminFeedbackRouteWithChildren =
  AuthenticatedAdminFeedbackRoute._addFileChildren(
    AuthenticatedAdminFeedbackRouteChildren,
  )

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsTabRoute: typeof AuthenticatedAdminSettingsTabRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsTabRoute: AuthenticatedAdminSettingsTabRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAlertLogRoute: typeof AuthenticatedAlertLogRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedIndicatorsRoute: typeof AuthenticatedIndicatorsRoute
  AuthenticatedPnlRoute: typeof AuthenticatedPnlRoute
  AuthenticatedTradeRoute: typeof AuthenticatedTradeRoute
  AuthenticatedWalletsRoute: typeof AuthenticatedWalletsRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedScannerWhalesRouteRoute: typeof AuthenticatedScannerWhalesRouteRouteWithChildren
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRouteWithChildren
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAutomationsAutomationIdRoute: typeof AuthenticatedAutomationsAutomationIdRoute
  AuthenticatedBacktestGroupIdRoute: typeof AuthenticatedBacktestGroupIdRoute
  AuthenticatedBacktestPracticeRoute: typeof AuthenticatedBacktestPracticeRoute
  AuthenticatedBotsBotIdRoute: typeof AuthenticatedBotsBotIdRoute
  AuthenticatedScannerBookRoute: typeof AuthenticatedScannerBookRoute
  AuthenticatedScannerCrowdedRoute: typeof AuthenticatedScannerCrowdedRoute
  AuthenticatedScannerLeaderboardRoute: typeof AuthenticatedScannerLeaderboardRoute
  AuthenticatedScannerMarketRoute: typeof AuthenticatedScannerMarketRoute
  AuthenticatedScannerMarketAlertsRoute: typeof AuthenticatedScannerMarketAlertsRoute
  AuthenticatedScannerPositionsRoute: typeof AuthenticatedScannerPositionsRoute
  AuthenticatedScannerWhaleTradesRoute: typeof AuthenticatedScannerWhaleTradesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAutomationsIndexRoute: typeof AuthenticatedAutomationsIndexRoute
  AuthenticatedBacktestIndexRoute: typeof AuthenticatedBacktestIndexRoute
  AuthenticatedBotsIndexRoute: typeof AuthenticatedBotsIndexRoute
  AuthenticatedScannerIndexRoute: typeof AuthenticatedScannerIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertLogRoute: AuthenticatedAlertLogRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedIndicatorsRoute: AuthenticatedIndicatorsRoute,
  AuthenticatedPnlRoute: AuthenticatedPnlRoute,
  AuthenticatedTradeRoute: AuthenticatedTradeRoute,
  AuthenticatedWalletsRoute: AuthenticatedWalletsRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedScannerWhalesRouteRoute:
    AuthenticatedScannerWhalesRouteRouteWithChildren,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRouteWithChildren,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
  AuthenticatedAutomationsAutomationIdRoute:
    AuthenticatedAutomationsAutomationIdRoute,
  AuthenticatedBacktestGroupIdRoute: AuthenticatedBacktestGroupIdRoute,
  AuthenticatedBacktestPracticeRoute: AuthenticatedBacktestPracticeRoute,
  AuthenticatedBotsBotIdRoute: AuthenticatedBotsBotIdRoute,
  AuthenticatedScannerBookRoute: AuthenticatedScannerBookRoute,
  AuthenticatedScannerCrowdedRoute: AuthenticatedScannerCrowdedRoute,
  AuthenticatedScannerLeaderboardRoute: AuthenticatedScannerLeaderboardRoute,
  AuthenticatedScannerMarketRoute: AuthenticatedScannerMarketRoute,
  AuthenticatedScannerMarketAlertsRoute: AuthenticatedScannerMarketAlertsRoute,
  AuthenticatedScannerPositionsRoute: AuthenticatedScannerPositionsRoute,
  AuthenticatedScannerWhaleTradesRoute: AuthenticatedScannerWhaleTradesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAutomationsIndexRoute: AuthenticatedAutomationsIndexRoute,
  AuthenticatedBacktestIndexRoute: AuthenticatedBacktestIndexRoute,
  AuthenticatedBotsIndexRoute: AuthenticatedBotsIndexRoute,
  AuthenticatedScannerIndexRoute: AuthenticatedScannerIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiV1MediaMediaIdFileRoute: ApiV1MediaMediaIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
