"use client"

import { useState, useEffect } from "react"
import { Dialog } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardGroup, CardHeader } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field"
import { MediaPicker } from "@/components/admin/media-library/MediaPicker"
import { ImageIcon, X, Check } from "lucide-react"
import { DashboardModalContent, DashboardModalCardTitle } from "@/components/admin/layout/dashboard/modals"
import { updateCategoryAction, type Category, type UpdateCategoryData } from "@/lib/actions/categories/category-actions"
import { Combobox, type ComboboxOption } from "@/components/ui/combobox"
import { generateSlug } from "@/lib/utils/slug"

interface CategorySettingsModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  category: Category | null
  existingCategories: Category[]
  onSuccess?: (updatedCategory: Category) => void
}

export function CategorySettingsModal({
  open,
  onOpenChange,
  category,
  existingCategories,
  onSuccess
}: CategorySettingsModalProps) {
  const [formData, setFormData] = useState<UpdateCategoryData>({})
  const [featuredImage, setFeaturedImage] = useState('')
  const [parentId, setParentId] = useState<string>("")
  const [isPrivate, setIsPrivate] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [saveMessage, setSaveMessage] = useState<string | null>(null)
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false)
  const [showImagePicker, setShowImagePicker] = useState(false)
  const [isSaved, setIsSaved] = useState(false)

  const handleTitleChange = (title: string) => {
    setIsSaved(false)
    setFormData(prev => ({
      ...prev,
      title,
      slug: slugManuallyEdited ? prev.slug : generateSlug(title)
    }))
  }

  const handleSlugChange = (slug: string) => {
    setIsSaved(false)
    if (slug === '') {
      setSlugManuallyEdited(false)
      setFormData(prev => ({ ...prev, slug: generateSlug(prev.title || '') }))
    } else {
      setSlugManuallyEdited(true)
      setFormData(prev => ({ ...prev, slug }))
    }
  }

  const handleImageChange = async (newImageUrl: string) => {
    setIsSaved(false)
    setFeaturedImage(newImageUrl)
  }

  const handleRemoveImage = async () => {
    setIsSaved(false)
    setFeaturedImage('')
  }

  const isDescendant = (potentialDescendant: Category, ancestorId: string): boolean => {
    let current: Category | undefined = potentialDescendant
    while (current) {
      if (current.id === ancestorId) return true
      current = existingCategories.find(c => c.id === current?.parent_id)
    }
    return false
  }

  const buildParentOptions = (): ComboboxOption[] => {
    const options: ComboboxOption[] = []

    const addCategory = (cat: Category, ancestors: Category[] = []) => {
      if (category && (cat.id === category.id || isDescendant(cat, category.id))) {
        return
      }

      const path = ancestors.length > 0
        ? ancestors.map(a => a.title).join(' > ')
        : undefined

      options.push({
        value: cat.id,
        label: cat.title,
        path
      })

      const children = existingCategories.filter(c => c.parent_id === cat.id)
      children.forEach(child => addCategory(child, [...ancestors, cat]))
    }

    const topLevel = existingCategories.filter(c => !c.parent_id)
    topLevel.forEach(cat => addCategory(cat))

    return options
  }

  useEffect(() => {
    if (category) {
      setFormData({
        title: category.title,
        slug: category.slug,
        is_published: category.is_published,
        meta_description: category.meta_description || ''
      })
      setIsPrivate(category.content_blocks?._settings?.is_private === true)
      setFeaturedImage(category.featured_image || '')
      setParentId(category.parent_id || '')
      const autoGeneratedSlug = generateSlug(category.title)
      setSlugManuallyEdited(category.slug !== autoGeneratedSlug)
      setError(null)
      setSaveMessage(null)
    }
  }, [category])

  const handleSaveDraft = async () => {
    if (!formData.title?.trim()) {
      setError('Category title is required')
      return
    }

    if (!category) {
      setError('No category selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)

      const draftData: UpdateCategoryData = {
        ...formData,
        is_published: false,
        featured_image: featuredImage || null,
        parent_id: parentId || null,
        content_blocks: {
          ...category.content_blocks,
          _settings: {
            ...category.content_blocks?._settings,
            is_private: isPrivate
          }
        }
      }

      const { data, error: updateError } = await updateCategoryAction(category.id, draftData)

      if (updateError || !data) {
        setError(updateError || 'Failed to save category as draft')
        return
      }

      setSaveMessage('Category saved as draft successfully!')
      setIsSaved(true)

      if (onSuccess) {
        onSuccess(data)
      }

      setTimeout(() => {
        setSaveMessage(null)
      }, 3000)
    } catch (err) {
      setError('Failed to save category as draft')
    } finally {
      setSaving(false)
    }
  }

  const handlePublish = async () => {
    if (!formData.title?.trim()) {
      setError('Category title is required')
      return
    }

    if (!category) {
      setError('No category selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)

      const publishData: UpdateCategoryData = {
        ...formData,
        is_published: true,
        featured_image: featuredImage || null,
        parent_id: parentId || null,
        content_blocks: {
          ...category.content_blocks,
          _settings: {
            ...category.content_blocks?._settings,
            is_private: isPrivate
          }
        }
      }

      const { data, error: updateError } = await updateCategoryAction(category.id, publishData)

      if (updateError || !data) {
        setError(updateError || 'Failed to publish category')
        return
      }

      setSaveMessage(category?.is_published ? 'Category saved successfully!' : 'Category published successfully!')
      setIsSaved(true)

      if (onSuccess) {
        onSuccess(data)
      }

      setTimeout(() => {
        setSaveMessage(null)
      }, 3000)
    } catch (err) {
      setError('Failed to publish category')
    } finally {
      setSaving(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    await handleSaveDraft()
  }

  if (!category) {
    return null
  }

  const parentOptions = buildParentOptions()

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <form onSubmit={handleSubmit} className="contents">
        <DashboardModalContent
          title={
            <span className="flex items-center gap-3">
              Configure settings for &quot;{category.title}&quot;
              <span className="flex items-center space-x-2">
                <span className={`w-2 h-2 rounded-full ${category?.is_published ? 'bg-green-500' : 'bg-gray-400'}`} />
                <span className="text-sm font-medium">{category?.is_published ? 'Published' : 'Draft'}</span>
              </span>
            </span>
          }
          footer={
            <>
              <Button type="button" variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>
                Cancel
              </Button>
              <div className="flex items-center space-x-2">
                {isSaved && (
                  <div className="flex items-center space-x-1 text-green-600">
                    <Check className="h-4 w-4" />
                    <span className="text-sm font-medium">Saved!</span>
                  </div>
                )}
                <Button type="submit" variant="outline" disabled={saving}>
                  {saving ? "Saving..." : "Save as Draft"}
                </Button>
                <Button type="button" onClick={handlePublish} disabled={saving}>
                  {saving ? "Saving..." : category?.is_published ? "Save" : "Publish"}
                </Button>
              </div>
            </>
          }
          footerClassName="sm:justify-between"
        >
          {(error || saveMessage) && (
            <div className="px-6 pb-2 space-y-2">
              {error && (
                <div className="rounded-lg border border-red-200 bg-red-50 p-3">
                  <p className="text-sm text-red-800">{error}</p>
                </div>
              )}
              {saveMessage && (
                <div className="rounded-lg border border-green-200 bg-green-50 p-3">
                  <p className="text-sm text-green-800">{saveMessage}</p>
                </div>
              )}
            </div>
          )}
          <CardGroup className="grid">
            <Card>
              <CardHeader>
                <DashboardModalCardTitle>Setup</DashboardModalCardTitle>
              </CardHeader>
              <CardContent>
                <Field>
                  <FieldLabel htmlFor="modal-title">Category Title *</FieldLabel>
                  <Input
                    id="modal-title"
                    value={formData.title || ''}
                    onChange={(e) => handleTitleChange(e.target.value)}
                    placeholder="Enter category title"
                    required
                  />
                </Field>
                <Field>
                  <FieldLabel htmlFor="modal-slug">Category URL</FieldLabel>
                  <Input
                    id="modal-slug"
                    value={formData.slug || ''}
                    onChange={(e) => handleSlugChange(e.target.value)}
                    placeholder="category-url-slug"
                  />
                  <FieldDescription>
                    {slugManuallyEdited
                      ? "Custom URL slug. Clear this field to auto-generate from title again."
                      : "Auto-generated from title. You can edit this to customize the URL."}
                  </FieldDescription>
                </Field>
                <Field>
                  <FieldLabel htmlFor="parent">Parent Category (Optional)</FieldLabel>
                  <Combobox
                    options={parentOptions}
                    value={parentId}
                    onValueChange={(value) => {
                      setIsSaved(false)
                      setParentId(value)
                    }}
                    placeholder="None (top-level)"
                    searchPlaceholder="Search parent categories..."
                    emptyMessage="No parent categories found."
                    allowClear={true}
                  />
                  <FieldDescription>Create nested hierarchies. Search to find parent categories.</FieldDescription>
                </Field>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <DashboardModalCardTitle>Image</DashboardModalCardTitle>
              </CardHeader>
              <CardContent>
                <div className="[&>div]:w-fit">
                  {featuredImage ? (
                    <div className="relative w-48 h-48 rounded-lg overflow-hidden bg-muted">
                      <img
                        src={featuredImage}
                        alt="Featured image preview"
                        className="w-full h-full object-contain"
                      />
                      <button
                        type="button"
                        onClick={handleRemoveImage}
                        className="absolute top-2 right-2 p-1 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors"
                      >
                        <X className="h-4 w-4" />
                      </button>
                      <div className="absolute inset-0 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity bg-black/50 cursor-pointer"
                        onClick={() => setShowImagePicker(true)}
                      >
                        <div className="text-white text-center">
                          <ImageIcon className="mx-auto h-8 w-8 mb-2" />
                          <p className="text-sm font-medium">Click to change image</p>
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div
                      className="flex items-center justify-center w-48 h-48 rounded-lg border-2 border-dashed border-muted-foreground/25 bg-muted/50 cursor-pointer hover:bg-muted/70 hover:border-muted-foreground/40 transition-all"
                      onClick={() => setShowImagePicker(true)}
                    >
                      <div className="text-center">
                        <ImageIcon className="mx-auto h-8 w-8 text-muted-foreground/50" />
                        <p className="mt-2 text-sm text-muted-foreground">Click to select featured image</p>
                      </div>
                    </div>
                  )}
                </div>
                <p className="mt-2 text-xs text-muted-foreground">Optional featured image for this category</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <DashboardModalCardTitle>Settings</DashboardModalCardTitle>
              </CardHeader>
              <CardContent>
                <Field>
                  <label className="flex items-center gap-2 cursor-pointer">
                    <Checkbox
                      id="modal-is-private"
                      checked={isPrivate}
                      onCheckedChange={(checked) => {
                        setIsSaved(false)
                        setIsPrivate(!!checked)
                      }}
                    />
                    <span className="text-sm">Private (accessible only via direct URL, hidden from listings)</span>
                  </label>
                </Field>
                <Field>
                  <FieldLabel htmlFor="meta_description">Meta Description</FieldLabel>
                  <Textarea
                    id="meta_description"
                    value={formData.meta_description || ''}
                    onChange={(e) => {
                      setIsSaved(false)
                      setFormData(prev => ({ ...prev, meta_description: e.target.value }))
                    }}
                    placeholder="SEO meta description"
                    rows={3}
                  />
                  <FieldDescription>
                    Used for SEO. Keep it under 160 characters. Currently: {(formData.meta_description || '').length}/160
                  </FieldDescription>
                </Field>
              </CardContent>
            </Card>
          </CardGroup>

          <MediaPicker
            open={showImagePicker}
            onOpenChange={setShowImagePicker}
            onSelectMedia={(imageUrl) => {
              handleImageChange(imageUrl)
              setShowImagePicker(false)
            }}
            currentMediaUrl={featuredImage || ''}
          />
        </DashboardModalContent>
      </form>
    </Dialog>
  )
}
