"use client"

import { useState, useEffect } from "react"
import {
  Dialog,
  DialogHeader,
  DialogTitle,
  DialogPortal,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Checkbox } from "@/components/ui/checkbox"
import { MediaPicker } from "@/components/admin/media-library/MediaPicker"
import { RichTextEditor } from "@/components/admin/shared/RichTextEditor"
import { ImageIcon, X, Check } from "lucide-react"
import * as DialogPrimitive from "@radix-ui/react-dialog"
import { updateCategoryAction, type Category, type UpdateCategoryData } from "@/lib/actions/categories/category-actions"
import { Combobox, type ComboboxOption } from "@/components/ui/combobox"
import { generateSlug } from "@/lib/utils/slug"

interface CategorySettingsModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  category: Category | null
  existingCategories: Category[]
  onSuccess?: (updatedCategory: Category) => void
}

export function CategorySettingsModal({
  open,
  onOpenChange,
  category,
  existingCategories,
  onSuccess
}: CategorySettingsModalProps) {
  const [formData, setFormData] = useState<UpdateCategoryData>({})
  const [richTextContent, setRichTextContent] = useState('')
  const [featuredImage, setFeaturedImage] = useState('')
  const [parentId, setParentId] = useState<string>("")
  const [isPrivate, setIsPrivate] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [saveMessage, setSaveMessage] = useState<string | null>(null)
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false)
  const [showImagePicker, setShowImagePicker] = useState(false)
  const [isSaved, setIsSaved] = useState(false)

  const handleTitleChange = (title: string) => {
    setIsSaved(false)
    setFormData(prev => ({
      ...prev,
      title,
      slug: slugManuallyEdited ? prev.slug : generateSlug(title)
    }))
  }

  const handleSlugChange = (slug: string) => {
    setIsSaved(false)
    if (slug === '') {
      setSlugManuallyEdited(false)
      setFormData(prev => ({ ...prev, slug: generateSlug(prev.title || '') }))
    } else {
      setSlugManuallyEdited(true)
      setFormData(prev => ({ ...prev, slug }))
    }
  }

  const handleImageChange = async (newImageUrl: string) => {
    setIsSaved(false)
    setFeaturedImage(newImageUrl)
  }

  const handleRemoveImage = async () => {
    setIsSaved(false)
    setFeaturedImage('')
  }

  const isDescendant = (potentialDescendant: Category, ancestorId: string): boolean => {
    let current: Category | undefined = potentialDescendant
    while (current) {
      if (current.id === ancestorId) return true
      current = existingCategories.find(c => c.id === current?.parent_id)
    }
    return false
  }

  const buildParentOptions = (): ComboboxOption[] => {
    const options: ComboboxOption[] = []

    const addCategory = (cat: Category, ancestors: Category[] = []) => {
      if (category && (cat.id === category.id || isDescendant(cat, category.id))) {
        return
      }

      const path = ancestors.length > 0
        ? ancestors.reverse().map(a => a.title).join(' > ')
        : undefined

      options.push({
        value: cat.id,
        label: cat.title,
        path
      })

      const children = existingCategories.filter(c => c.parent_id === cat.id)
      children.forEach(child => addCategory(child, [...ancestors, cat]))
    }

    const topLevel = existingCategories.filter(c => !c.parent_id)
    topLevel.forEach(cat => addCategory(cat))

    return options
  }

  useEffect(() => {
    if (category) {
      setFormData({
        title: category.title,
        slug: category.slug,
        is_published: category.is_published
      })
      setIsPrivate(category.content_blocks?._settings?.is_private === true)
      setRichTextContent(category.description || '')
      setFeaturedImage(category.featured_image || '')
      setParentId(category.parent_id || '')
      const autoGeneratedSlug = generateSlug(category.title)
      setSlugManuallyEdited(category.slug !== autoGeneratedSlug)
      setError(null)
      setSaveMessage(null)
    }
  }, [category])

  const handleSaveDraft = async () => {
    if (!formData.title?.trim()) {
      setError('Category title is required')
      return
    }

    if (!category) {
      setError('No category selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)

      const draftData: UpdateCategoryData = {
        ...formData,
        is_published: false,
        featured_image: featuredImage || null,
        description: richTextContent || null,
        parent_id: parentId || null,
        content_blocks: {
          ...category.content_blocks,
          _settings: {
            ...category.content_blocks?._settings,
            is_private: isPrivate
          }
        }
      }

      const { data, error: updateError } = await updateCategoryAction(category.id, draftData)

      if (updateError || !data) {
        setError(updateError || 'Failed to save category as draft')
        return
      }

      setSaveMessage('Category saved as draft successfully!')
      setIsSaved(true)

      if (onSuccess) {
        onSuccess(data)
      }

      setTimeout(() => {
        setSaveMessage(null)
      }, 3000)
    } catch (err) {
      setError('Failed to save category as draft')
    } finally {
      setSaving(false)
    }
  }

  const handlePublish = async () => {
    if (!formData.title?.trim()) {
      setError('Category title is required')
      return
    }

    if (!category) {
      setError('No category selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)

      const publishData: UpdateCategoryData = {
        ...formData,
        is_published: true,
        featured_image: featuredImage || null,
        description: richTextContent || null,
        parent_id: parentId || null,
        content_blocks: {
          ...category.content_blocks,
          _settings: {
            ...category.content_blocks?._settings,
            is_private: isPrivate
          }
        }
      }

      const { data, error: updateError } = await updateCategoryAction(category.id, publishData)

      if (updateError || !data) {
        setError(updateError || 'Failed to publish category')
        return
      }

      setSaveMessage(category?.is_published ? 'Category saved successfully!' : 'Category published successfully!')
      setIsSaved(true)

      if (onSuccess) {
        onSuccess(data)
      }

      setTimeout(() => {
        setSaveMessage(null)
      }, 3000)
    } catch (err) {
      setError('Failed to publish category')
    } finally {
      setSaving(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    await handleSaveDraft()
  }

  if (!category) {
    return null
  }

  const parentOptions = buildParentOptions()

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogPortal>
        <div className="fixed inset-0 z-50 bg-black/50 flex items-start justify-center overflow-y-auto p-4"
             onClick={(e) => e.target === e.currentTarget && onOpenChange(false)}>
          <div className="bg-background rounded-lg border shadow-lg w-[840px] max-w-[95vw] p-10 relative my-8"
               style={{ width: '840px', maxWidth: '95vw' }}
               onClick={(e) => e.stopPropagation()}>
            <DialogPrimitive.Close className="absolute top-4 right-4 rounded-xs opacity-70 transition-opacity hover:opacity-100 focus:ring-2 focus:ring-offset-2 focus:outline-hidden">
              <X className="h-4 w-4" />
              <span className="sr-only">Close</span>
            </DialogPrimitive.Close>
        <DialogHeader className="mb-6">
          <DialogTitle className="flex items-center gap-3">
            Configure settings for &quot;{category.title}&quot;
            <div className="flex items-center space-x-2">
              <div className={`w-2 h-2 rounded-full ${
                category?.is_published ? 'bg-green-500' : 'bg-gray-400'
              }`} />
              <span className="text-sm font-medium">
                {category?.is_published ? 'Published' : 'Draft'}
              </span>
            </div>
          </DialogTitle>
        </DialogHeader>

        {error && (
          <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg">
            <p className="text-red-800 text-sm">{error}</p>
          </div>
        )}

        {saveMessage && (
          <div className="mb-4 p-3 bg-green-50 border border-green-200 rounded-lg">
            <p className="text-green-800 text-sm">{saveMessage}</p>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="modal-title">Category Title *</Label>
                <Input
                  id="modal-title"
                  value={formData.title || ''}
                  onChange={(e) => handleTitleChange(e.target.value)}
                  placeholder="Enter category title"
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="modal-slug">Category URL</Label>
                <Input
                  id="modal-slug"
                  value={formData.slug || ''}
                  onChange={(e) => handleSlugChange(e.target.value)}
                  placeholder="category-url-slug"
                />
                <p className="text-xs text-muted-foreground">
                  {slugManuallyEdited
                    ? "Custom URL slug. Clear this field to auto-generate from title again."
                    : "Auto-generated from title. You can edit this to customize the URL."}
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="parent">Parent Category (Optional)</Label>
                <Combobox
                  options={parentOptions}
                  value={parentId}
                  onValueChange={(value) => {
                    setIsSaved(false)
                    setParentId(value)
                  }}
                  placeholder="None (top-level)"
                  searchPlaceholder="Search parent categories..."
                  emptyMessage="No parent categories found."
                  allowClear={true}
                />
                <p className="text-xs text-muted-foreground">
                  Create nested hierarchies. Search to find parent categories.
                </p>
              </div>

              <div className="space-y-2">
                <Label htmlFor="featured_image">Featured Image</Label>
                <div className="mt-2">
                  {featuredImage ? (
                    <div className="relative w-48 h-48 rounded-lg overflow-hidden bg-muted">
                      <img
                        src={featuredImage}
                        alt="Featured image preview"
                        className="w-full h-full object-contain"
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-background/80 to-transparent" />
                      <button
                        type="button"
                        onClick={handleRemoveImage}
                        className="absolute top-2 right-2 p-1 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors"
                      >
                        <X className="h-4 w-4" />
                      </button>
                      <div className="absolute inset-0 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity bg-black/50 cursor-pointer"
                        onClick={() => setShowImagePicker(true)}
                      >
                        <div className="text-white text-center">
                          <ImageIcon className="mx-auto h-8 w-8 mb-2" />
                          <p className="text-sm font-medium">Click to change image</p>
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div
                      className="flex items-center justify-center w-48 h-48 rounded-lg border-2 border-dashed border-muted-foreground/25 bg-muted/50 cursor-pointer hover:bg-muted/70 hover:border-muted-foreground/40 transition-all"
                      onClick={() => setShowImagePicker(true)}
                    >
                      <div className="text-center">
                        <ImageIcon className="mx-auto h-8 w-8 text-muted-foreground/50" />
                        <p className="mt-2 text-sm text-muted-foreground">Click to select featured image</p>
                      </div>
                    </div>
                  )}
                </div>
                <p className="text-xs text-muted-foreground">
                  Optional featured image for this category
                </p>
              </div>

              <div className="space-y-2">
                <Label>Privacy Settings</Label>
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="modal-is-private"
                    checked={isPrivate}
                    onCheckedChange={(checked) => {
                      setIsSaved(false)
                      setIsPrivate(!!checked)
                    }}
                  />
                  <Label htmlFor="modal-is-private" className="text-sm font-normal">
                    Private (accessible only via direct URL, hidden from listings)
                  </Label>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="rich_text">Category Description</Label>
                <RichTextEditor
                  content={{
                    content: richTextContent,
                    hideHeader: true,
                    hideEditorHeader: true
                  }}
                  onContentChange={(content) => {
                    setIsSaved(false)
                    setRichTextContent(content.content)
                  }}
                  compact={true}
                  inline={true}
                />
                <p className="text-xs text-muted-foreground">
                  Rich text content for the category description
                </p>
              </div>

          <div className="flex justify-between pt-4">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={saving}
            >
              Cancel
            </Button>
            <div className="flex items-center space-x-2">
              {isSaved && (
                <div className="flex items-center space-x-1 text-green-600">
                  <Check className="h-4 w-4" />
                  <span className="text-sm font-medium">Saved!</span>
                </div>
              )}
              <Button
                type="submit"
                variant="outline"
                disabled={saving}
              >
                {saving ? "Saving..." : "Save as Draft"}
              </Button>
              <Button
                type="button"
                onClick={handlePublish}
                disabled={saving}
              >
                {saving ? "Saving..." : category?.is_published ? "Save" : "Publish"}
              </Button>
            </div>
          </div>
        </form>

        <MediaPicker
          open={showImagePicker}
          onOpenChange={setShowImagePicker}
          onSelectMedia={(imageUrl) => {
            handleImageChange(imageUrl)
            setShowImagePicker(false)
          }}
          currentMediaUrl={featuredImage || ''}
        />
          </div>
        </div>
      </DialogPortal>
    </Dialog>
  )
}
