"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { FieldLabel } from "@/components/ui/field-label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Card, CardGroup, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import AlertCircle from "lucide-react/dist/esm/icons/circle-alert.js"
import CheckCircle2 from "lucide-react/dist/esm/icons/circle-check.js"
import Copy from "lucide-react/dist/esm/icons/copy.js"
import { checkSubdomainAvailabilityAction } from "@/lib/actions/sites/site-actions"
import { CacheSettingsCard } from "@/components/admin/layout/settings/CacheSettingsCard"
import { SearchIndexSettingsCard } from "@/components/admin/layout/settings/SearchIndexSettingsCard"
import { ListingWidgetsSettingsCard } from "@/components/admin/layout/settings/ListingWidgetsSettingsCard"
import { TrackingSettingsCard } from "@/components/admin/layout/settings/TrackingSettingsCard"
import { Switch } from "@/components/ui/switch"

interface SiteDashboardProps {
  siteName: string
  status: string
  siteTag?: string
  subdomain?: string
  customDomain?: string
  trackingScripts?: string
  customAnalyticsEnabled?: boolean
  listingWidgetsEnabled?: boolean
  /** Only set in edit mode, where the maintenance cards need a site to act on. */
  siteId?: string
  isEditMode?: boolean
  maintenanceEnabled?: boolean
  loading?: boolean
  customDomainError?: string | null
  onSiteNameChange: (value: string) => void
  onStatusChange: (value: string) => void
  onSiteTagChange?: (value: string) => void
  onSubdomainChange?: (value: string) => void
  onCustomDomainChange?: (value: string) => void
  onTrackingScriptsChange?: (value: string) => void
  onCustomAnalyticsEnabledChange?: (value: boolean) => void
  onListingWidgetsEnabledChange?: (value: boolean) => void
  onMaintenanceChange?: (value: boolean) => void
}

export function SiteDashboard({
  siteName,
  status,
  siteTag = "",
  subdomain = "",
  customDomain = "",
  trackingScripts = "",
  customAnalyticsEnabled = false,
  listingWidgetsEnabled = true,
  siteId = "",
  isEditMode = false,
  maintenanceEnabled = false,
  loading = false,
  customDomainError = null,
  onSiteNameChange,
  onStatusChange,
  onSiteTagChange,
  onSubdomainChange,
  onCustomDomainChange,
  onTrackingScriptsChange,
  onCustomAnalyticsEnabledChange,
  onListingWidgetsEnabledChange,
  onMaintenanceChange
}: SiteDashboardProps) {
  const [subdomainManuallyEdited, setSubdomainManuallyEdited] = useState(false)
  const [copiedDnsField, setCopiedDnsField] = useState<"name" | "value" | null>(null)
  const [subdomainStatus, setSubdomainStatus] = useState<{
    checking: boolean
    available: boolean | null
    suggestion?: string
  }>({ checking: false, available: null })
  const customDomainVerification = customDomainError?.match(
    /^Add TXT record (.+) with value (.+) before using this domain$/
  )
  const dnsRecordName = customDomainVerification?.[1] || ""
  const dnsRecordValue = customDomainVerification?.[2] || ""

  // Generate subdomain from site name
  const generateSubdomain = (name: string) => {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "")
  }

  // Initialize subdomain manually edited state based on whether subdomain differs from auto-generated
  useEffect(() => {
    if (siteName && subdomain) {
      const autoGeneratedSubdomain = generateSubdomain(siteName)
      setSubdomainManuallyEdited(subdomain !== autoGeneratedSubdomain)
    }
  }, [siteName, subdomain])

  // Handle site name change and auto-generate subdomain if subdomain hasn't been manually edited
  const handleSiteNameChange = (name: string) => {
    onSiteNameChange(name)
    if (!subdomainManuallyEdited && onSubdomainChange) {
      const newSubdomain = generateSubdomain(name)
      onSubdomainChange(newSubdomain)
    }
  }

  // Handle manual subdomain changes
  const handleSubdomainChange = (newSubdomain: string) => {
    if (!onSubdomainChange) return

    // Mark as manually edited when user changes the field
    setSubdomainManuallyEdited(true)
    onSubdomainChange(newSubdomain)
  }

  // Check subdomain availability when subdomain changes (only in create mode)
  useEffect(() => {
    if (!isEditMode && subdomain.trim()) {
      checkSubdomainAvailability(subdomain)
    } else {
      setSubdomainStatus({ checking: false, available: null })
    }
  }, [subdomain, isEditMode])

  const checkSubdomainAvailability = async (subdomainToCheck: string) => {
    if (!subdomainToCheck) {
      setSubdomainStatus({ checking: false, available: null })
      return
    }

    try {
      setSubdomainStatus({ checking: true, available: null })
      const { available, suggestion } = await checkSubdomainAvailabilityAction(subdomainToCheck)
      setSubdomainStatus({
        checking: false,
        available,
        suggestion: available ? undefined : suggestion
      })
    } catch (err) {
      console.error("Error checking subdomain:", err)
      setSubdomainStatus({ checking: false, available: null })
    }
  }

  const copyDnsValue = async (field: "name" | "value", value: string) => {
    if (!value) return
    await navigator.clipboard.writeText(value)
    setCopiedDnsField(field)
    window.setTimeout(() => setCopiedDnsField(null), 1500)
  }

  if (loading) {
    return (
      <CardGroup className="grid">
        {[...Array(4)].map((_, i) => (
          <Card key={i}>
            <CardContent>
              {[...Array(3)].map((_, j) => (
                <div key={j} className="space-y-2">
                  <div className="h-4 bg-muted rounded animate-pulse w-24"></div>
                  <div className="h-10 bg-muted/60 rounded animate-pulse"></div>
                </div>
              ))}
            </CardContent>
          </Card>
        ))}
      </CardGroup>
    )
  }

  return (
    <CardGroup className="grid">
      <Card>
        <CardHeader>
          <CardTitle>Site Information</CardTitle>
        </CardHeader>
        <CardContent>
          {/* Site Name */}
          <div className="grid gap-2">
            <FieldLabel htmlFor="siteName" hint="This will be the name of your site.">
              Site Name *
            </FieldLabel>
            <div className="relative">
              <Input
                id="siteName"
                value={siteName}
                onChange={(e) => handleSiteNameChange(e.target.value)}
                placeholder="Enter site name (e.g., mysite)"
                required
                className={
                  subdomainStatus.available === false
                    ? "pr-10 border-red-300 focus:border-red-500"
                    : subdomainStatus.available === true
                      ? "pr-10 border-green-300 focus:border-green-500"
                      : ""
                }
              />
              {!subdomainStatus.checking && subdomainStatus.available === true && (
                <CheckCircle2 className="absolute right-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-green-500" />
              )}
              {!subdomainStatus.checking && subdomainStatus.available === false && (
                <AlertCircle className="absolute right-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-red-500" />
              )}
            </div>
            {subdomainStatus.checking && (
              <p className="text-xs text-muted-foreground" role="status">
                Checking availability...
              </p>
            )}
          </div>

          {/* Maintenance Mode */}
          {onMaintenanceChange && (
            <div className="grid gap-2">
              <Label htmlFor="maintenance">Maintenance Mode</Label>
              <div className="flex items-center justify-between border rounded-md p-3">
                <div>
                  <p className="text-sm font-medium">Enable maintenance mode</p>
                  <p className="text-xs text-muted-foreground">
                    Redirects visitors to the maintenance page. Admin routes unaffected.
                  </p>
                </div>
                <Switch id="maintenance" checked={!!maintenanceEnabled} onCheckedChange={onMaintenanceChange} />
              </div>
            </div>
          )}

          {/* Site Subdomain */}
          {onSubdomainChange && (
            <div className="grid gap-2">
              <FieldLabel
                htmlFor="subdomain"
                hint="Auto-generated from the site name. You can edit this to customize the URL."
              >
                Site URL
              </FieldLabel>
              <div className="relative">
                <Input
                  id="subdomain"
                  value={subdomain}
                  onChange={(e) => handleSubdomainChange(e.target.value)}
                  placeholder="site-url"
                  className={
                    subdomainStatus.available === false
                      ? "pr-10 border-red-300 focus:border-red-500"
                      : subdomainStatus.available === true
                        ? "pr-10 border-green-300 focus:border-green-500"
                        : ""
                  }
                />
                {!subdomainStatus.checking && subdomainStatus.available === true && (
                  <CheckCircle2 className="absolute right-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-green-500" />
                )}
                {!subdomainStatus.checking && subdomainStatus.available === false && (
                  <AlertCircle className="absolute right-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-red-500" />
                )}
              </div>
              <div className="text-xs text-muted-foreground space-y-1">
                {subdomainStatus.checking && <p role="status">Checking availability...</p>}
                <p>
                  Your site will be available at: <strong>{subdomain || "your-site"}.domain.com</strong>
                </p>
                {subdomainStatus.available === false && subdomainStatus.suggestion && (
                  <p className="text-amber-600">
                    Subdomain not available. Suggested: <strong>{subdomainStatus.suggestion}.domain.com</strong>
                  </p>
                )}
                {subdomainStatus.available === true && <p className="text-green-600">Subdomain is available!</p>}
              </div>
            </div>
          )}

          {/* Custom Domain */}
          {onCustomDomainChange && (
            <div className="grid gap-2">
              <FieldLabel
                htmlFor="customDomain"
                hint="Enter the main domain. Hub also wires the www version when available."
              >
                Custom Domain
              </FieldLabel>
              <Input
                id="customDomain"
                value={customDomain}
                onChange={(e) => onCustomDomainChange(e.target.value)}
                placeholder="example.com"
              />
              {customDomain && (
                <p className="text-xs text-blue-600">
                  Site will be accessible at: <strong>{customDomain}</strong>
                </p>
              )}
              {dnsRecordName && dnsRecordValue && (
                <div className="space-y-3 rounded-md border border-amber-200 bg-amber-50 p-3">
                  <p className="text-sm font-medium text-amber-900">
                    Add this TXT record at your DNS provider, then save again.
                  </p>
                  <div className="space-y-2">
                    <Label htmlFor="customDomainTxtName" className="text-xs text-amber-900">
                      TXT name
                    </Label>
                    <div className="flex gap-2">
                      <Input id="customDomainTxtName" value={dnsRecordName} readOnly className="font-mono text-xs" />
                      <Button
                        type="button"
                        variant="outline"
                        size="icon"
                        onClick={() => copyDnsValue("name", dnsRecordName)}
                        title={copiedDnsField === "name" ? "Copied" : "Copy TXT name"}
                      >
                        <Copy className="h-4 w-4" />
                        <span className="sr-only">{copiedDnsField === "name" ? "Copied" : "Copy TXT name"}</span>
                      </Button>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="customDomainTxtValue" className="text-xs text-amber-900">
                      TXT value
                    </Label>
                    <div className="flex gap-2">
                      <Input id="customDomainTxtValue" value={dnsRecordValue} readOnly className="font-mono text-xs" />
                      <Button
                        type="button"
                        variant="outline"
                        size="icon"
                        onClick={() => copyDnsValue("value", dnsRecordValue)}
                        title={copiedDnsField === "value" ? "Copied" : "Copy TXT value"}
                      >
                        <Copy className="h-4 w-4" />
                        <span className="sr-only">{copiedDnsField === "value" ? "Copied" : "Copy TXT value"}</span>
                      </Button>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {onSiteTagChange && (
            <div className="grid gap-2">
              <FieldLabel htmlFor="siteTag" hint="Used to filter sites in the dashboard.">
                Site Tag
              </FieldLabel>
              <Input
                id="siteTag"
                value={siteTag}
                onChange={(e) => onSiteTagChange(e.target.value)}
                placeholder="directory, store, client"
                maxLength={50}
              />
            </div>
          )}

          {/* Status */}
          <div className="grid gap-2">
            <Label htmlFor="status">Site Status</Label>
            <Select value={status} onValueChange={onStatusChange}>
              <SelectTrigger>
                <SelectValue placeholder="Select status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="draft">Draft</SelectItem>
                <SelectItem value="active">Active</SelectItem>
                <SelectItem value="inactive">Inactive</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Tracking Settings Card */}
      {onTrackingScriptsChange && (
        <TrackingSettingsCard
          trackingScripts={trackingScripts}
          customAnalyticsEnabled={customAnalyticsEnabled}
          onTrackingScriptsChange={onTrackingScriptsChange}
          onCustomAnalyticsEnabledChange={onCustomAnalyticsEnabledChange}
        />
      )}

      {onListingWidgetsEnabledChange && (
        <ListingWidgetsSettingsCard
          listingWidgetsEnabled={listingWidgetsEnabled}
          onListingWidgetsEnabledChange={onListingWidgetsEnabledChange}
        />
      )}

      {/* Maintenance cards - Only show in edit mode */}
      {isEditMode && siteId && <SearchIndexSettingsCard siteId={siteId} />}
      {isEditMode && <CacheSettingsCard />}
    </CardGroup>
  )
}

// claude.md followed
