"use client"

import { useState, useEffect } from "react"
import { 
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogPortal,
  DialogOverlay,
} from "@/components/ui/dialog"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { ImagePicker } from "@/components/admin/layout/image-library/ImagePicker"
import { RichTextEditor } from "@/components/admin/layout/page-builder/RichTextEditor"
import { ImageIcon, X, Check } from "lucide-react"
import * as DialogPrimitive from "@radix-ui/react-dialog"
import Link from "next/link"
import { updateProductAction } from "@/lib/actions/product-actions"
import type { Product, UpdateProductData } from "@/lib/actions/product-actions"
import type { SiteWithTheme } from "@/lib/actions/site-actions"

interface ProductSettingsModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  product: Product | null
  site: SiteWithTheme | null
  onSuccess?: (updatedProduct: Product) => void
}

export function ProductSettingsModal({ 
  open, 
  onOpenChange, 
  product, 
  site,
  onSuccess 
}: ProductSettingsModalProps) {
  const [formData, setFormData] = useState<UpdateProductData>({})
  const [richTextContent, setRichTextContent] = useState('')
  const [featuredImage, setFeaturedImage] = useState('')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [saveMessage, setSaveMessage] = useState<string | null>(null)
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false)
  const [showImagePicker, setShowImagePicker] = useState(false)
  const [isSaved, setIsSaved] = useState(false)

  // Generate slug from title
  const generateSlug = (title: string) => {
    return title
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
  }

  // Handle title change and auto-generate slug if slug hasn't been manually edited
  const handleTitleChange = (title: string) => {
    setIsSaved(false)
    setFormData(prev => ({
      ...prev,
      title,
      slug: slugManuallyEdited ? prev.slug : generateSlug(title)
    }))
  }

  // Handle manual slug changes
  const handleSlugChange = (slug: string) => {
    setIsSaved(false)
    if (slug === '') {
      // If user clears the field, reset to auto-generation
      setSlugManuallyEdited(false)
      setFormData(prev => ({ ...prev, slug: generateSlug(prev.title || '') }))
    } else {
      setSlugManuallyEdited(true)
      setFormData(prev => ({ ...prev, slug }))
    }
  }

  // Handle featured image changes
  const handleImageChange = async (newImageUrl: string) => {
    setIsSaved(false)
    setFeaturedImage(newImageUrl)
  }

  // Handle removing the featured image
  const handleRemoveImage = async () => {
    setIsSaved(false)
    setFeaturedImage('')
  }


  // Initialize form data when product changes
  useEffect(() => {
    if (product) {
      setFormData({
        title: product.title,
        slug: product.slug,
        is_published: product.is_published
      })
      
      // Get content from product columns
      setRichTextContent(product.description || '')
      setFeaturedImage(product.featured_image || '')
      
      // Check if slug was manually edited (different from auto-generated)
      const autoGeneratedSlug = generateSlug(product.title)
      setSlugManuallyEdited(product.slug !== autoGeneratedSlug)
      
      // Reset states
      setError(null)
      setSaveMessage(null)
    }
  }, [product])


  // Handle saving as draft
  const handleSaveDraft = async () => {
    if (!formData.title?.trim()) {
      setError('Product title is required')
      return
    }

    if (!product) {
      setError('No product selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)
      
      const draftData = { 
        ...formData, 
        is_published: false,
        featured_image: featuredImage || null,
        description: richTextContent || null
      }
      const { data, error: actionError } = await updateProductAction(product.id, draftData)
      
      if (actionError) {
        setError(actionError)
        return
      }
      
      if (data) {
        setSaveMessage('Product saved as draft successfully!')
        setIsSaved(true)
        
        // Call success callback with updated product
        if (onSuccess) {
          onSuccess(data)
        }
        
        // Clear success message after 3 seconds but keep modal open
        setTimeout(() => {
          setSaveMessage(null)
        }, 3000)
      }
    } catch (err) {
      setError('Failed to save product as draft')
    } finally {
      setSaving(false)
    }
  }

  // Handle publishing
  const handlePublish = async () => {
    if (!formData.title?.trim()) {
      setError('Product title is required')
      return
    }

    if (!product) {
      setError('No product selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)
      
      const publishData = { 
        ...formData, 
        is_published: true,
        featured_image: featuredImage || null,
        description: richTextContent || null
      }
      const { data, error: actionError } = await updateProductAction(product.id, publishData)
      
      if (actionError) {
        setError(actionError)
        return
      }
      
      if (data) {
        setSaveMessage(product?.is_published ? 'Product saved successfully!' : 'Product published successfully!')
        setIsSaved(true)
        
        // Call success callback with updated product
        if (onSuccess) {
          onSuccess(data)
        }
        
        // Clear success message after 3 seconds but keep modal open
        setTimeout(() => {
          setSaveMessage(null)
        }, 3000)
      }
    } catch (err) {
      setError('Failed to publish product')
    } finally {
      setSaving(false)
    }
  }

  // Handle form submission (default to save as draft)
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    await handleSaveDraft()
  }

  if (!product) {
    return null
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogPortal>
        <div className="fixed inset-0 z-50 bg-black/50 flex items-start justify-center overflow-y-auto p-4"
             onClick={(e) => e.target === e.currentTarget && onOpenChange(false)}>
          <div className="bg-background rounded-lg border shadow-lg w-[840px] max-w-[95vw] p-6 relative my-8"
               style={{ width: '840px', maxWidth: '95vw' }}
               onClick={(e) => e.stopPropagation()}>
            <DialogPrimitive.Close className="absolute top-4 right-4 rounded-xs opacity-70 transition-opacity hover:opacity-100 focus:ring-2 focus:ring-offset-2 focus:outline-hidden">
              <X className="h-4 w-4" />
              <span className="sr-only">Close</span>
            </DialogPrimitive.Close>
        <DialogHeader className="mb-6">
          <DialogTitle className="flex items-center gap-3">
            Configure settings for "{product.title}"
            <div className="flex items-center space-x-2">
              <div className={`w-2 h-2 rounded-full ${
                product?.is_published ? 'bg-green-500' : 'bg-gray-400'
              }`} />
              <span className="text-sm font-medium">
                {product?.is_published ? 'Published' : 'Draft'}
              </span>
            </div>
          </DialogTitle>
        </DialogHeader>

        {error && (
          <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg">
            <p className="text-red-800 text-sm">{error}</p>
          </div>
        )}

        {saveMessage && (
          <div className="mb-4 p-3 bg-green-50 border border-green-200 rounded-lg">
            <p className="text-green-800 text-sm">{saveMessage}</p>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Basic Information */}
          <Card className="shadow-sm">
            <CardHeader>
              <CardTitle>Basic Information</CardTitle>
              <CardDescription>
                Configure the basic settings for this product
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Product Title */}
              <div className="space-y-2">
                <Label htmlFor="modal-title">Product Title *</Label>
                <Input
                  id="modal-title"
                  value={formData.title || ''}
                  onChange={(e) => handleTitleChange(e.target.value)}
                  placeholder="Enter product title"
                  required
                />
              </div>

              {/* Product Slug */}
              <div className="space-y-2">
                <Label htmlFor="modal-slug">Product URL</Label>
                <Input
                  id="modal-slug"
                  value={formData.slug || ''}
                  onChange={(e) => handleSlugChange(e.target.value)}
                  placeholder="product-url-slug"
                />
                <p className="text-xs text-muted-foreground">
                  {slugManuallyEdited 
                    ? "Custom URL slug. Clear this field to auto-generate from title again." 
                    : "Auto-generated from title. You can edit this to customize the URL."}
                </p>
              </div>

              {/* Featured Image */}
              <div className="space-y-2">
                <Label htmlFor="featured_image">Featured Image</Label>
                <div className="mt-2">
                  {featuredImage ? (
                    <div className="relative w-48 h-48 rounded-lg overflow-hidden bg-muted">
                      <img 
                        src={featuredImage} 
                        alt="Featured image preview" 
                        className="w-full h-full object-cover"
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-background/80 to-transparent" />
                      <button
                        type="button"
                        onClick={handleRemoveImage}
                        className="absolute top-2 right-2 p-1 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors"
                      >
                        <X className="h-4 w-4" />
                      </button>
                      <div className="absolute inset-0 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity bg-black/50 cursor-pointer"
                        onClick={() => setShowImagePicker(true)}
                      >
                        <div className="text-white text-center">
                          <ImageIcon className="mx-auto h-8 w-8 mb-2" />
                          <p className="text-sm font-medium">Click to change image</p>
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div 
                      className="flex items-center justify-center w-48 h-48 rounded-lg border-2 border-dashed border-muted-foreground/25 bg-muted/50 cursor-pointer hover:bg-muted/70 hover:border-muted-foreground/40 transition-all"
                      onClick={() => setShowImagePicker(true)}
                    >
                      <div className="text-center">
                        <ImageIcon className="mx-auto h-8 w-8 text-muted-foreground/50" />
                        <p className="mt-2 text-sm text-muted-foreground">Click to select featured image</p>
                      </div>
                    </div>
                  )}
                </div>
                <p className="text-xs text-muted-foreground">
                  Optional featured image for this product
                </p>
              </div>

              {/* Rich Text Content */}
              <div className="space-y-2">
                <Label htmlFor="rich_text">Product Description</Label>
                <RichTextEditor
                  content={{
                    content: richTextContent,
                    hideHeader: true,
                    hideEditorHeader: true
                  }}
                  onContentChange={(content) => {
                    setIsSaved(false)
                    setRichTextContent(content.content)
                  }}
                  compact={true}
                />
                <p className="text-xs text-muted-foreground">
                  Rich text content for the product description (will be saved as a product block)
                </p>
              </div>
                
            </CardContent>
          </Card>



          {/* Form Actions */}
          <div className="flex justify-between pt-4">
            <Button 
              type="button" 
              variant="outline" 
              onClick={() => onOpenChange(false)}
              disabled={saving}
            >
              Cancel
            </Button>
            <div className="flex items-center space-x-2">
              {isSaved && (
                <div className="flex items-center space-x-1 text-green-600">
                  <Check className="h-4 w-4" />
                  <span className="text-sm font-medium">Saved!</span>
                </div>
              )}
              <Button 
                type="submit" 
                variant="outline"
                disabled={saving}
              >
                {saving ? "Saving..." : "Save as Draft"}
              </Button>
              <Button 
                type="button" 
                onClick={handlePublish}
                disabled={saving}
              >
                {saving ? "Saving..." : product?.is_published ? "Save" : "Publish"}
              </Button>
            </div>
          </div>
        </form>

        {/* Image Picker Modal */}
        <ImagePicker
          open={showImagePicker}
          onOpenChange={setShowImagePicker}
          onSelectImage={(imageUrl) => {
            handleImageChange(imageUrl)
            setShowImagePicker(false)
          }}
          currentImageUrl={featuredImage || ''}
        />
          </div>
        </div>
      </DialogPortal>
    </Dialog>
  )
}