/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminModulesRouteImport } from './routes/_authenticated/admin/modules'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin/feedback'
import { Route as AuthenticatedAdminSettingsTabRouteImport } from './routes/_authenticated/admin/settings/$tab'
import { Route as AuthenticatedAdminModulesUgcAdVideoRouteImport } from './routes/_authenticated/admin/modules/ugc-ad-video'
import { Route as AuthenticatedAdminMediaVideosRouteImport } from './routes/_authenticated/admin/media/videos'
import { Route as AuthenticatedAdminMediaImagesRouteImport } from './routes/_authenticated/admin/media/images'
import { Route as AuthenticatedAdminFeedbackCommentsRouteImport } from './routes/_authenticated/admin/feedback/comments'
import { Route as ApiV1MediaMediaIdFileRouteImport } from './routes/api/v1/media/$mediaId/file'
import { Route as AuthenticatedAdminModulesUgcAdVideoCreateRouteImport } from './routes/_authenticated/admin/modules/ugc-ad-video/create'
import { Route as AuthenticatedAdminModulesUgcAdVideoGenerationsGenerationIdRouteImport } from './routes/_authenticated/admin/modules/ugc-ad-video/generations/$generationId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminModulesRoute =
  AuthenticatedAdminModulesRouteImport.update({
    id: '/admin/modules',
    path: '/admin/modules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/admin/feedback',
    path: '/admin/feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsTabRoute =
  AuthenticatedAdminSettingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminModulesUgcAdVideoRoute =
  AuthenticatedAdminModulesUgcAdVideoRouteImport.update({
    id: '/ugc-ad-video',
    path: '/ugc-ad-video',
    getParentRoute: () => AuthenticatedAdminModulesRoute,
  } as any)
const AuthenticatedAdminMediaVideosRoute =
  AuthenticatedAdminMediaVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminMediaRoute,
  } as any)
const AuthenticatedAdminMediaImagesRoute =
  AuthenticatedAdminMediaImagesRouteImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => AuthenticatedAdminMediaRoute,
  } as any)
const AuthenticatedAdminFeedbackCommentsRoute =
  AuthenticatedAdminFeedbackCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminFeedbackRoute,
  } as any)
const ApiV1MediaMediaIdFileRoute = ApiV1MediaMediaIdFileRouteImport.update({
  id: '/api/v1/media/$mediaId/file',
  path: '/api/v1/media/$mediaId/file',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminModulesUgcAdVideoCreateRoute =
  AuthenticatedAdminModulesUgcAdVideoCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAdminModulesUgcAdVideoRoute,
  } as any)
const AuthenticatedAdminModulesUgcAdVideoGenerationsGenerationIdRoute =
  AuthenticatedAdminModulesUgcAdVideoGenerationsGenerationIdRouteImport.update({
    id: '/generations/$generationId',
    path: '/generations/$generationId',
    getParentRoute: () => AuthenticatedAdminModulesUgcAdVideoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminMediaRouteWithChildren
  '/admin/modules': typeof AuthenticatedAdminModulesRouteWithChildren
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/admin/media/images': typeof AuthenticatedAdminMediaImagesRoute
  '/admin/media/videos': typeof AuthenticatedAdminMediaVideosRoute
  '/admin/modules/ugc-ad-video': typeof AuthenticatedAdminModulesUgcAdVideoRouteWithChildren
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/admin/modules/ugc-ad-video/create': typeof AuthenticatedAdminModulesUgcAdVideoCreateRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
  '/admin/modules/ugc-ad-video/generations/$generationId': typeof AuthenticatedAdminModulesUgcAdVideoGenerationsGenerationIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminMediaRouteWithChildren
  '/admin/modules': typeof AuthenticatedAdminModulesRouteWithChildren
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/admin/media/images': typeof AuthenticatedAdminMediaImagesRoute
  '/admin/media/videos': typeof AuthenticatedAdminMediaVideosRoute
  '/admin/modules/ugc-ad-video': typeof AuthenticatedAdminModulesUgcAdVideoRouteWithChildren
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/admin/modules/ugc-ad-video/create': typeof AuthenticatedAdminModulesUgcAdVideoCreateRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
  '/admin/modules/ugc-ad-video/generations/$generationId': typeof AuthenticatedAdminModulesUgcAdVideoGenerationsGenerationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRouteWithChildren
  '/_authenticated/admin/modules': typeof AuthenticatedAdminModulesRouteWithChildren
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/_authenticated/admin/media/images': typeof AuthenticatedAdminMediaImagesRoute
  '/_authenticated/admin/media/videos': typeof AuthenticatedAdminMediaVideosRoute
  '/_authenticated/admin/modules/ugc-ad-video': typeof AuthenticatedAdminModulesUgcAdVideoRouteWithChildren
  '/_authenticated/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/_authenticated/admin/modules/ugc-ad-video/create': typeof AuthenticatedAdminModulesUgcAdVideoCreateRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
  '/_authenticated/admin/modules/ugc-ad-video/generations/$generationId': typeof AuthenticatedAdminModulesUgcAdVideoGenerationsGenerationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspaces'
    | '/admin/feedback'
    | '/admin/media'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/feedback/comments'
    | '/admin/media/images'
    | '/admin/media/videos'
    | '/admin/modules/ugc-ad-video'
    | '/admin/settings/$tab'
    | '/admin/modules/ugc-ad-video/create'
    | '/api/v1/media/$mediaId/file'
    | '/admin/modules/ugc-ad-video/generations/$generationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/workspaces'
    | '/'
    | '/admin/feedback'
    | '/admin/media'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/feedback/comments'
    | '/admin/media/images'
    | '/admin/media/videos'
    | '/admin/modules/ugc-ad-video'
    | '/admin/settings/$tab'
    | '/admin/modules/ugc-ad-video/create'
    | '/api/v1/media/$mediaId/file'
    | '/admin/modules/ugc-ad-video/generations/$generationId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/workspaces'
    | '/_authenticated/'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/modules'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/feedback/comments'
    | '/_authenticated/admin/media/images'
    | '/_authenticated/admin/media/videos'
    | '/_authenticated/admin/modules/ugc-ad-video'
    | '/_authenticated/admin/settings/$tab'
    | '/_authenticated/admin/modules/ugc-ad-video/create'
    | '/api/v1/media/$mediaId/file'
    | '/_authenticated/admin/modules/ugc-ad-video/generations/$generationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiV1MediaMediaIdFileRoute: typeof ApiV1MediaMediaIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/modules': {
      id: '/_authenticated/admin/modules'
      path: '/admin/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AuthenticatedAdminModulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings/$tab': {
      id: '/_authenticated/admin/settings/$tab'
      path: '/$tab'
      fullPath: '/admin/settings/$tab'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTabRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/modules/ugc-ad-video': {
      id: '/_authenticated/admin/modules/ugc-ad-video'
      path: '/ugc-ad-video'
      fullPath: '/admin/modules/ugc-ad-video'
      preLoaderRoute: typeof AuthenticatedAdminModulesUgcAdVideoRouteImport
      parentRoute: typeof AuthenticatedAdminModulesRoute
    }
    '/_authenticated/admin/media/videos': {
      id: '/_authenticated/admin/media/videos'
      path: '/videos'
      fullPath: '/admin/media/videos'
      preLoaderRoute: typeof AuthenticatedAdminMediaVideosRouteImport
      parentRoute: typeof AuthenticatedAdminMediaRoute
    }
    '/_authenticated/admin/media/images': {
      id: '/_authenticated/admin/media/images'
      path: '/images'
      fullPath: '/admin/media/images'
      preLoaderRoute: typeof AuthenticatedAdminMediaImagesRouteImport
      parentRoute: typeof AuthenticatedAdminMediaRoute
    }
    '/_authenticated/admin/feedback/comments': {
      id: '/_authenticated/admin/feedback/comments'
      path: '/comments'
      fullPath: '/admin/feedback/comments'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminFeedbackRoute
    }
    '/api/v1/media/$mediaId/file': {
      id: '/api/v1/media/$mediaId/file'
      path: '/api/v1/media/$mediaId/file'
      fullPath: '/api/v1/media/$mediaId/file'
      preLoaderRoute: typeof ApiV1MediaMediaIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/modules/ugc-ad-video/create': {
      id: '/_authenticated/admin/modules/ugc-ad-video/create'
      path: '/create'
      fullPath: '/admin/modules/ugc-ad-video/create'
      preLoaderRoute: typeof AuthenticatedAdminModulesUgcAdVideoCreateRouteImport
      parentRoute: typeof AuthenticatedAdminModulesUgcAdVideoRoute
    }
    '/_authenticated/admin/modules/ugc-ad-video/generations/$generationId': {
      id: '/_authenticated/admin/modules/ugc-ad-video/generations/$generationId'
      path: '/generations/$generationId'
      fullPath: '/admin/modules/ugc-ad-video/generations/$generationId'
      preLoaderRoute: typeof AuthenticatedAdminModulesUgcAdVideoGenerationsGenerationIdRouteImport
      parentRoute: typeof AuthenticatedAdminModulesUgcAdVideoRoute
    }
  }
}

interface AuthenticatedAdminFeedbackRouteChildren {
  AuthenticatedAdminFeedbackCommentsRoute: typeof AuthenticatedAdminFeedbackCommentsRoute
}

const AuthenticatedAdminFeedbackRouteChildren: AuthenticatedAdminFeedbackRouteChildren =
  {
    AuthenticatedAdminFeedbackCommentsRoute:
      AuthenticatedAdminFeedbackCommentsRoute,
  }

const AuthenticatedAdminFeedbackRouteWithChildren =
  AuthenticatedAdminFeedbackRoute._addFileChildren(
    AuthenticatedAdminFeedbackRouteChildren,
  )

interface AuthenticatedAdminMediaRouteChildren {
  AuthenticatedAdminMediaImagesRoute: typeof AuthenticatedAdminMediaImagesRoute
  AuthenticatedAdminMediaVideosRoute: typeof AuthenticatedAdminMediaVideosRoute
}

const AuthenticatedAdminMediaRouteChildren: AuthenticatedAdminMediaRouteChildren =
  {
    AuthenticatedAdminMediaImagesRoute: AuthenticatedAdminMediaImagesRoute,
    AuthenticatedAdminMediaVideosRoute: AuthenticatedAdminMediaVideosRoute,
  }

const AuthenticatedAdminMediaRouteWithChildren =
  AuthenticatedAdminMediaRoute._addFileChildren(
    AuthenticatedAdminMediaRouteChildren,
  )

interface AuthenticatedAdminModulesUgcAdVideoRouteChildren {
  AuthenticatedAdminModulesUgcAdVideoCreateRoute: typeof AuthenticatedAdminModulesUgcAdVideoCreateRoute
  AuthenticatedAdminModulesUgcAdVideoGenerationsGenerationIdRoute: typeof AuthenticatedAdminModulesUgcAdVideoGenerationsGenerationIdRoute
}

const AuthenticatedAdminModulesUgcAdVideoRouteChildren: AuthenticatedAdminModulesUgcAdVideoRouteChildren =
  {
    AuthenticatedAdminModulesUgcAdVideoCreateRoute:
      AuthenticatedAdminModulesUgcAdVideoCreateRoute,
    AuthenticatedAdminModulesUgcAdVideoGenerationsGenerationIdRoute:
      AuthenticatedAdminModulesUgcAdVideoGenerationsGenerationIdRoute,
  }

const AuthenticatedAdminModulesUgcAdVideoRouteWithChildren =
  AuthenticatedAdminModulesUgcAdVideoRoute._addFileChildren(
    AuthenticatedAdminModulesUgcAdVideoRouteChildren,
  )

interface AuthenticatedAdminModulesRouteChildren {
  AuthenticatedAdminModulesUgcAdVideoRoute: typeof AuthenticatedAdminModulesUgcAdVideoRouteWithChildren
}

const AuthenticatedAdminModulesRouteChildren: AuthenticatedAdminModulesRouteChildren =
  {
    AuthenticatedAdminModulesUgcAdVideoRoute:
      AuthenticatedAdminModulesUgcAdVideoRouteWithChildren,
  }

const AuthenticatedAdminModulesRouteWithChildren =
  AuthenticatedAdminModulesRoute._addFileChildren(
    AuthenticatedAdminModulesRouteChildren,
  )

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsTabRoute: typeof AuthenticatedAdminSettingsTabRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsTabRoute: AuthenticatedAdminSettingsTabRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRouteWithChildren
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRouteWithChildren
  AuthenticatedAdminModulesRoute: typeof AuthenticatedAdminModulesRouteWithChildren
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRouteWithChildren,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRouteWithChildren,
  AuthenticatedAdminModulesRoute: AuthenticatedAdminModulesRouteWithChildren,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiV1MediaMediaIdFileRoute: ApiV1MediaMediaIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
