/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminFirstFrameRouteImport } from './routes/_authenticated/admin/first-frame'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin/feedback'
import { Route as AuthenticatedAdminExportRouteImport } from './routes/_authenticated/admin/export'
import { Route as AuthenticatedAdminActorRouteImport } from './routes/_authenticated/admin/actor'
import { Route as AuthenticatedAdminViralArchiveIndexRouteImport } from './routes/_authenticated/admin/viral-archive/index'
import { Route as AuthenticatedAdminVideoEditorIndexRouteImport } from './routes/_authenticated/admin/video-editor/index'
import { Route as AuthenticatedAdminTemplatesIndexRouteImport } from './routes/_authenticated/admin/templates/index'
import { Route as AuthenticatedAdminCreatorsIndexRouteImport } from './routes/_authenticated/admin/creators/index'
import { Route as AuthenticatedAdminCarouselsIndexRouteImport } from './routes/_authenticated/admin/carousels/index'
import { Route as AuthenticatedAdminVideoEditorProjectIdRouteImport } from './routes/_authenticated/admin/video-editor/$projectId'
import { Route as AuthenticatedAdminSettingsTabRouteImport } from './routes/_authenticated/admin/settings/$tab'
import { Route as AuthenticatedAdminFeedbackCommentsRouteImport } from './routes/_authenticated/admin/feedback/comments'
import { Route as AuthenticatedAdminCreatorsCreatorIdRouteImport } from './routes/_authenticated/admin/creators/$creatorId'
import { Route as AuthenticatedAdminCarouselsCarouselIdRouteImport } from './routes/_authenticated/admin/carousels/$carouselId'
import { Route as ApiV1ViralVideosVideoIdThumbnailRouteImport } from './routes/api/v1/viral-videos/$videoId/thumbnail'
import { Route as ApiV1TemplatesTemplateIdThumbnailRouteImport } from './routes/api/v1/templates/$templateId/thumbnail'
import { Route as ApiV1ProjectsProjectIdRenderThumbnailRouteImport } from './routes/api/v1/projects/$projectId/render-thumbnail'
import { Route as ApiV1ProjectsProjectIdRenderRouteImport } from './routes/api/v1/projects/$projectId/render'
import { Route as ApiV1MediaMediaIdFileRouteImport } from './routes/api/v1/media/$mediaId/file'
import { Route as ApiV1CreatorsCreatorIdAvatarRouteImport } from './routes/api/v1/creators/$creatorId/avatar'
import { Route as ApiV1ActorsActorIdImageRouteImport } from './routes/api/v1/actors/$actorId/image'
import { Route as AuthenticatedAdminVideoEditorTemplateTemplateIdRouteImport } from './routes/_authenticated/admin/video-editor/template/$templateId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminFirstFrameRoute =
  AuthenticatedAdminFirstFrameRouteImport.update({
    id: '/admin/first-frame',
    path: '/admin/first-frame',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/admin/feedback',
    path: '/admin/feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminExportRoute =
  AuthenticatedAdminExportRouteImport.update({
    id: '/admin/export',
    path: '/admin/export',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminActorRoute = AuthenticatedAdminActorRouteImport.update({
  id: '/admin/actor',
  path: '/admin/actor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminViralArchiveIndexRoute =
  AuthenticatedAdminViralArchiveIndexRouteImport.update({
    id: '/admin/viral-archive/',
    path: '/admin/viral-archive/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVideoEditorIndexRoute =
  AuthenticatedAdminVideoEditorIndexRouteImport.update({
    id: '/admin/video-editor/',
    path: '/admin/video-editor/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTemplatesIndexRoute =
  AuthenticatedAdminTemplatesIndexRouteImport.update({
    id: '/admin/templates/',
    path: '/admin/templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCreatorsIndexRoute =
  AuthenticatedAdminCreatorsIndexRouteImport.update({
    id: '/admin/creators/',
    path: '/admin/creators/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCarouselsIndexRoute =
  AuthenticatedAdminCarouselsIndexRouteImport.update({
    id: '/admin/carousels/',
    path: '/admin/carousels/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVideoEditorProjectIdRoute =
  AuthenticatedAdminVideoEditorProjectIdRouteImport.update({
    id: '/admin/video-editor/$projectId',
    path: '/admin/video-editor/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsTabRoute =
  AuthenticatedAdminSettingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminFeedbackCommentsRoute =
  AuthenticatedAdminFeedbackCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminFeedbackRoute,
  } as any)
const AuthenticatedAdminCreatorsCreatorIdRoute =
  AuthenticatedAdminCreatorsCreatorIdRouteImport.update({
    id: '/admin/creators/$creatorId',
    path: '/admin/creators/$creatorId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCarouselsCarouselIdRoute =
  AuthenticatedAdminCarouselsCarouselIdRouteImport.update({
    id: '/admin/carousels/$carouselId',
    path: '/admin/carousels/$carouselId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiV1ViralVideosVideoIdThumbnailRoute =
  ApiV1ViralVideosVideoIdThumbnailRouteImport.update({
    id: '/api/v1/viral-videos/$videoId/thumbnail',
    path: '/api/v1/viral-videos/$videoId/thumbnail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1TemplatesTemplateIdThumbnailRoute =
  ApiV1TemplatesTemplateIdThumbnailRouteImport.update({
    id: '/api/v1/templates/$templateId/thumbnail',
    path: '/api/v1/templates/$templateId/thumbnail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsProjectIdRenderThumbnailRoute =
  ApiV1ProjectsProjectIdRenderThumbnailRouteImport.update({
    id: '/api/v1/projects/$projectId/render-thumbnail',
    path: '/api/v1/projects/$projectId/render-thumbnail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ProjectsProjectIdRenderRoute =
  ApiV1ProjectsProjectIdRenderRouteImport.update({
    id: '/api/v1/projects/$projectId/render',
    path: '/api/v1/projects/$projectId/render',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MediaMediaIdFileRoute = ApiV1MediaMediaIdFileRouteImport.update({
  id: '/api/v1/media/$mediaId/file',
  path: '/api/v1/media/$mediaId/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CreatorsCreatorIdAvatarRoute =
  ApiV1CreatorsCreatorIdAvatarRouteImport.update({
    id: '/api/v1/creators/$creatorId/avatar',
    path: '/api/v1/creators/$creatorId/avatar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ActorsActorIdImageRoute = ApiV1ActorsActorIdImageRouteImport.update({
  id: '/api/v1/actors/$actorId/image',
  path: '/api/v1/actors/$actorId/image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVideoEditorTemplateTemplateIdRoute =
  AuthenticatedAdminVideoEditorTemplateTemplateIdRouteImport.update({
    id: '/admin/video-editor/template/$templateId',
    path: '/admin/video-editor/template/$templateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/admin/actor': typeof AuthenticatedAdminActorRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/admin/first-frame': typeof AuthenticatedAdminFirstFrameRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/carousels/$carouselId': typeof AuthenticatedAdminCarouselsCarouselIdRoute
  '/admin/creators/$creatorId': typeof AuthenticatedAdminCreatorsCreatorIdRoute
  '/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/admin/video-editor/$projectId': typeof AuthenticatedAdminVideoEditorProjectIdRoute
  '/admin/carousels/': typeof AuthenticatedAdminCarouselsIndexRoute
  '/admin/creators/': typeof AuthenticatedAdminCreatorsIndexRoute
  '/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/video-editor/': typeof AuthenticatedAdminVideoEditorIndexRoute
  '/admin/viral-archive/': typeof AuthenticatedAdminViralArchiveIndexRoute
  '/admin/video-editor/template/$templateId': typeof AuthenticatedAdminVideoEditorTemplateTemplateIdRoute
  '/api/v1/actors/$actorId/image': typeof ApiV1ActorsActorIdImageRoute
  '/api/v1/creators/$creatorId/avatar': typeof ApiV1CreatorsCreatorIdAvatarRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
  '/api/v1/projects/$projectId/render': typeof ApiV1ProjectsProjectIdRenderRoute
  '/api/v1/projects/$projectId/render-thumbnail': typeof ApiV1ProjectsProjectIdRenderThumbnailRoute
  '/api/v1/templates/$templateId/thumbnail': typeof ApiV1TemplatesTemplateIdThumbnailRoute
  '/api/v1/viral-videos/$videoId/thumbnail': typeof ApiV1ViralVideosVideoIdThumbnailRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/actor': typeof AuthenticatedAdminActorRoute
  '/admin/export': typeof AuthenticatedAdminExportRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/admin/first-frame': typeof AuthenticatedAdminFirstFrameRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/carousels/$carouselId': typeof AuthenticatedAdminCarouselsCarouselIdRoute
  '/admin/creators/$creatorId': typeof AuthenticatedAdminCreatorsCreatorIdRoute
  '/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/admin/video-editor/$projectId': typeof AuthenticatedAdminVideoEditorProjectIdRoute
  '/admin/carousels': typeof AuthenticatedAdminCarouselsIndexRoute
  '/admin/creators': typeof AuthenticatedAdminCreatorsIndexRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesIndexRoute
  '/admin/video-editor': typeof AuthenticatedAdminVideoEditorIndexRoute
  '/admin/viral-archive': typeof AuthenticatedAdminViralArchiveIndexRoute
  '/admin/video-editor/template/$templateId': typeof AuthenticatedAdminVideoEditorTemplateTemplateIdRoute
  '/api/v1/actors/$actorId/image': typeof ApiV1ActorsActorIdImageRoute
  '/api/v1/creators/$creatorId/avatar': typeof ApiV1CreatorsCreatorIdAvatarRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
  '/api/v1/projects/$projectId/render': typeof ApiV1ProjectsProjectIdRenderRoute
  '/api/v1/projects/$projectId/render-thumbnail': typeof ApiV1ProjectsProjectIdRenderThumbnailRoute
  '/api/v1/templates/$templateId/thumbnail': typeof ApiV1TemplatesTemplateIdThumbnailRoute
  '/api/v1/viral-videos/$videoId/thumbnail': typeof ApiV1ViralVideosVideoIdThumbnailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/actor': typeof AuthenticatedAdminActorRoute
  '/_authenticated/admin/export': typeof AuthenticatedAdminExportRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/_authenticated/admin/first-frame': typeof AuthenticatedAdminFirstFrameRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/admin/carousels/$carouselId': typeof AuthenticatedAdminCarouselsCarouselIdRoute
  '/_authenticated/admin/creators/$creatorId': typeof AuthenticatedAdminCreatorsCreatorIdRoute
  '/_authenticated/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/_authenticated/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/_authenticated/admin/video-editor/$projectId': typeof AuthenticatedAdminVideoEditorProjectIdRoute
  '/_authenticated/admin/carousels/': typeof AuthenticatedAdminCarouselsIndexRoute
  '/_authenticated/admin/creators/': typeof AuthenticatedAdminCreatorsIndexRoute
  '/_authenticated/admin/templates/': typeof AuthenticatedAdminTemplatesIndexRoute
  '/_authenticated/admin/video-editor/': typeof AuthenticatedAdminVideoEditorIndexRoute
  '/_authenticated/admin/viral-archive/': typeof AuthenticatedAdminViralArchiveIndexRoute
  '/_authenticated/admin/video-editor/template/$templateId': typeof AuthenticatedAdminVideoEditorTemplateTemplateIdRoute
  '/api/v1/actors/$actorId/image': typeof ApiV1ActorsActorIdImageRoute
  '/api/v1/creators/$creatorId/avatar': typeof ApiV1CreatorsCreatorIdAvatarRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
  '/api/v1/projects/$projectId/render': typeof ApiV1ProjectsProjectIdRenderRoute
  '/api/v1/projects/$projectId/render-thumbnail': typeof ApiV1ProjectsProjectIdRenderThumbnailRoute
  '/api/v1/templates/$templateId/thumbnail': typeof ApiV1TemplatesTemplateIdThumbnailRoute
  '/api/v1/viral-videos/$videoId/thumbnail': typeof ApiV1ViralVideosVideoIdThumbnailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspaces'
    | '/admin/actor'
    | '/admin/export'
    | '/admin/feedback'
    | '/admin/first-frame'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/carousels/$carouselId'
    | '/admin/creators/$creatorId'
    | '/admin/feedback/comments'
    | '/admin/settings/$tab'
    | '/admin/video-editor/$projectId'
    | '/admin/carousels/'
    | '/admin/creators/'
    | '/admin/templates/'
    | '/admin/video-editor/'
    | '/admin/viral-archive/'
    | '/admin/video-editor/template/$templateId'
    | '/api/v1/actors/$actorId/image'
    | '/api/v1/creators/$creatorId/avatar'
    | '/api/v1/media/$mediaId/file'
    | '/api/v1/projects/$projectId/render'
    | '/api/v1/projects/$projectId/render-thumbnail'
    | '/api/v1/templates/$templateId/thumbnail'
    | '/api/v1/viral-videos/$videoId/thumbnail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/workspaces'
    | '/'
    | '/admin/actor'
    | '/admin/export'
    | '/admin/feedback'
    | '/admin/first-frame'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/carousels/$carouselId'
    | '/admin/creators/$creatorId'
    | '/admin/feedback/comments'
    | '/admin/settings/$tab'
    | '/admin/video-editor/$projectId'
    | '/admin/carousels'
    | '/admin/creators'
    | '/admin/templates'
    | '/admin/video-editor'
    | '/admin/viral-archive'
    | '/admin/video-editor/template/$templateId'
    | '/api/v1/actors/$actorId/image'
    | '/api/v1/creators/$creatorId/avatar'
    | '/api/v1/media/$mediaId/file'
    | '/api/v1/projects/$projectId/render'
    | '/api/v1/projects/$projectId/render-thumbnail'
    | '/api/v1/templates/$templateId/thumbnail'
    | '/api/v1/viral-videos/$videoId/thumbnail'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/workspaces'
    | '/_authenticated/'
    | '/_authenticated/admin/actor'
    | '/_authenticated/admin/export'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/first-frame'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/carousels/$carouselId'
    | '/_authenticated/admin/creators/$creatorId'
    | '/_authenticated/admin/feedback/comments'
    | '/_authenticated/admin/settings/$tab'
    | '/_authenticated/admin/video-editor/$projectId'
    | '/_authenticated/admin/carousels/'
    | '/_authenticated/admin/creators/'
    | '/_authenticated/admin/templates/'
    | '/_authenticated/admin/video-editor/'
    | '/_authenticated/admin/viral-archive/'
    | '/_authenticated/admin/video-editor/template/$templateId'
    | '/api/v1/actors/$actorId/image'
    | '/api/v1/creators/$creatorId/avatar'
    | '/api/v1/media/$mediaId/file'
    | '/api/v1/projects/$projectId/render'
    | '/api/v1/projects/$projectId/render-thumbnail'
    | '/api/v1/templates/$templateId/thumbnail'
    | '/api/v1/viral-videos/$videoId/thumbnail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiV1ActorsActorIdImageRoute: typeof ApiV1ActorsActorIdImageRoute
  ApiV1CreatorsCreatorIdAvatarRoute: typeof ApiV1CreatorsCreatorIdAvatarRoute
  ApiV1MediaMediaIdFileRoute: typeof ApiV1MediaMediaIdFileRoute
  ApiV1ProjectsProjectIdRenderRoute: typeof ApiV1ProjectsProjectIdRenderRoute
  ApiV1ProjectsProjectIdRenderThumbnailRoute: typeof ApiV1ProjectsProjectIdRenderThumbnailRoute
  ApiV1TemplatesTemplateIdThumbnailRoute: typeof ApiV1TemplatesTemplateIdThumbnailRoute
  ApiV1ViralVideosVideoIdThumbnailRoute: typeof ApiV1ViralVideosVideoIdThumbnailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/first-frame': {
      id: '/_authenticated/admin/first-frame'
      path: '/admin/first-frame'
      fullPath: '/admin/first-frame'
      preLoaderRoute: typeof AuthenticatedAdminFirstFrameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/export': {
      id: '/_authenticated/admin/export'
      path: '/admin/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AuthenticatedAdminExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/actor': {
      id: '/_authenticated/admin/actor'
      path: '/admin/actor'
      fullPath: '/admin/actor'
      preLoaderRoute: typeof AuthenticatedAdminActorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/viral-archive/': {
      id: '/_authenticated/admin/viral-archive/'
      path: '/admin/viral-archive'
      fullPath: '/admin/viral-archive/'
      preLoaderRoute: typeof AuthenticatedAdminViralArchiveIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/video-editor/': {
      id: '/_authenticated/admin/video-editor/'
      path: '/admin/video-editor'
      fullPath: '/admin/video-editor/'
      preLoaderRoute: typeof AuthenticatedAdminVideoEditorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/templates/': {
      id: '/_authenticated/admin/templates/'
      path: '/admin/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/creators/': {
      id: '/_authenticated/admin/creators/'
      path: '/admin/creators'
      fullPath: '/admin/creators/'
      preLoaderRoute: typeof AuthenticatedAdminCreatorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/carousels/': {
      id: '/_authenticated/admin/carousels/'
      path: '/admin/carousels'
      fullPath: '/admin/carousels/'
      preLoaderRoute: typeof AuthenticatedAdminCarouselsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/video-editor/$projectId': {
      id: '/_authenticated/admin/video-editor/$projectId'
      path: '/admin/video-editor/$projectId'
      fullPath: '/admin/video-editor/$projectId'
      preLoaderRoute: typeof AuthenticatedAdminVideoEditorProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings/$tab': {
      id: '/_authenticated/admin/settings/$tab'
      path: '/$tab'
      fullPath: '/admin/settings/$tab'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTabRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/feedback/comments': {
      id: '/_authenticated/admin/feedback/comments'
      path: '/comments'
      fullPath: '/admin/feedback/comments'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminFeedbackRoute
    }
    '/_authenticated/admin/creators/$creatorId': {
      id: '/_authenticated/admin/creators/$creatorId'
      path: '/admin/creators/$creatorId'
      fullPath: '/admin/creators/$creatorId'
      preLoaderRoute: typeof AuthenticatedAdminCreatorsCreatorIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/carousels/$carouselId': {
      id: '/_authenticated/admin/carousels/$carouselId'
      path: '/admin/carousels/$carouselId'
      fullPath: '/admin/carousels/$carouselId'
      preLoaderRoute: typeof AuthenticatedAdminCarouselsCarouselIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/viral-videos/$videoId/thumbnail': {
      id: '/api/v1/viral-videos/$videoId/thumbnail'
      path: '/api/v1/viral-videos/$videoId/thumbnail'
      fullPath: '/api/v1/viral-videos/$videoId/thumbnail'
      preLoaderRoute: typeof ApiV1ViralVideosVideoIdThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/templates/$templateId/thumbnail': {
      id: '/api/v1/templates/$templateId/thumbnail'
      path: '/api/v1/templates/$templateId/thumbnail'
      fullPath: '/api/v1/templates/$templateId/thumbnail'
      preLoaderRoute: typeof ApiV1TemplatesTemplateIdThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$projectId/render-thumbnail': {
      id: '/api/v1/projects/$projectId/render-thumbnail'
      path: '/api/v1/projects/$projectId/render-thumbnail'
      fullPath: '/api/v1/projects/$projectId/render-thumbnail'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdRenderThumbnailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/projects/$projectId/render': {
      id: '/api/v1/projects/$projectId/render'
      path: '/api/v1/projects/$projectId/render'
      fullPath: '/api/v1/projects/$projectId/render'
      preLoaderRoute: typeof ApiV1ProjectsProjectIdRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/$mediaId/file': {
      id: '/api/v1/media/$mediaId/file'
      path: '/api/v1/media/$mediaId/file'
      fullPath: '/api/v1/media/$mediaId/file'
      preLoaderRoute: typeof ApiV1MediaMediaIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/creators/$creatorId/avatar': {
      id: '/api/v1/creators/$creatorId/avatar'
      path: '/api/v1/creators/$creatorId/avatar'
      fullPath: '/api/v1/creators/$creatorId/avatar'
      preLoaderRoute: typeof ApiV1CreatorsCreatorIdAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/actors/$actorId/image': {
      id: '/api/v1/actors/$actorId/image'
      path: '/api/v1/actors/$actorId/image'
      fullPath: '/api/v1/actors/$actorId/image'
      preLoaderRoute: typeof ApiV1ActorsActorIdImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/video-editor/template/$templateId': {
      id: '/_authenticated/admin/video-editor/template/$templateId'
      path: '/admin/video-editor/template/$templateId'
      fullPath: '/admin/video-editor/template/$templateId'
      preLoaderRoute: typeof AuthenticatedAdminVideoEditorTemplateTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminFeedbackRouteChildren {
  AuthenticatedAdminFeedbackCommentsRoute: typeof AuthenticatedAdminFeedbackCommentsRoute
}

const AuthenticatedAdminFeedbackRouteChildren: AuthenticatedAdminFeedbackRouteChildren =
  {
    AuthenticatedAdminFeedbackCommentsRoute:
      AuthenticatedAdminFeedbackCommentsRoute,
  }

const AuthenticatedAdminFeedbackRouteWithChildren =
  AuthenticatedAdminFeedbackRoute._addFileChildren(
    AuthenticatedAdminFeedbackRouteChildren,
  )

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsTabRoute: typeof AuthenticatedAdminSettingsTabRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsTabRoute: AuthenticatedAdminSettingsTabRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminActorRoute: typeof AuthenticatedAdminActorRoute
  AuthenticatedAdminExportRoute: typeof AuthenticatedAdminExportRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRouteWithChildren
  AuthenticatedAdminFirstFrameRoute: typeof AuthenticatedAdminFirstFrameRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAdminCarouselsCarouselIdRoute: typeof AuthenticatedAdminCarouselsCarouselIdRoute
  AuthenticatedAdminCreatorsCreatorIdRoute: typeof AuthenticatedAdminCreatorsCreatorIdRoute
  AuthenticatedAdminVideoEditorProjectIdRoute: typeof AuthenticatedAdminVideoEditorProjectIdRoute
  AuthenticatedAdminCarouselsIndexRoute: typeof AuthenticatedAdminCarouselsIndexRoute
  AuthenticatedAdminCreatorsIndexRoute: typeof AuthenticatedAdminCreatorsIndexRoute
  AuthenticatedAdminTemplatesIndexRoute: typeof AuthenticatedAdminTemplatesIndexRoute
  AuthenticatedAdminVideoEditorIndexRoute: typeof AuthenticatedAdminVideoEditorIndexRoute
  AuthenticatedAdminViralArchiveIndexRoute: typeof AuthenticatedAdminViralArchiveIndexRoute
  AuthenticatedAdminVideoEditorTemplateTemplateIdRoute: typeof AuthenticatedAdminVideoEditorTemplateTemplateIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminActorRoute: AuthenticatedAdminActorRoute,
  AuthenticatedAdminExportRoute: AuthenticatedAdminExportRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRouteWithChildren,
  AuthenticatedAdminFirstFrameRoute: AuthenticatedAdminFirstFrameRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
  AuthenticatedAdminCarouselsCarouselIdRoute:
    AuthenticatedAdminCarouselsCarouselIdRoute,
  AuthenticatedAdminCreatorsCreatorIdRoute:
    AuthenticatedAdminCreatorsCreatorIdRoute,
  AuthenticatedAdminVideoEditorProjectIdRoute:
    AuthenticatedAdminVideoEditorProjectIdRoute,
  AuthenticatedAdminCarouselsIndexRoute: AuthenticatedAdminCarouselsIndexRoute,
  AuthenticatedAdminCreatorsIndexRoute: AuthenticatedAdminCreatorsIndexRoute,
  AuthenticatedAdminTemplatesIndexRoute: AuthenticatedAdminTemplatesIndexRoute,
  AuthenticatedAdminVideoEditorIndexRoute:
    AuthenticatedAdminVideoEditorIndexRoute,
  AuthenticatedAdminViralArchiveIndexRoute:
    AuthenticatedAdminViralArchiveIndexRoute,
  AuthenticatedAdminVideoEditorTemplateTemplateIdRoute:
    AuthenticatedAdminVideoEditorTemplateTemplateIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiV1ActorsActorIdImageRoute: ApiV1ActorsActorIdImageRoute,
  ApiV1CreatorsCreatorIdAvatarRoute: ApiV1CreatorsCreatorIdAvatarRoute,
  ApiV1MediaMediaIdFileRoute: ApiV1MediaMediaIdFileRoute,
  ApiV1ProjectsProjectIdRenderRoute: ApiV1ProjectsProjectIdRenderRoute,
  ApiV1ProjectsProjectIdRenderThumbnailRoute:
    ApiV1ProjectsProjectIdRenderThumbnailRoute,
  ApiV1TemplatesTemplateIdThumbnailRoute:
    ApiV1TemplatesTemplateIdThumbnailRoute,
  ApiV1ViralVideosVideoIdThumbnailRoute: ApiV1ViralVideosVideoIdThumbnailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
