import { randomUUID } from 'node:crypto'
import { NEWSLETTER_SUBJECT_MAX } from '@/features/automations/domain/nodes/newsletter'
import type { NewsletterAutomationNode, StructuredArticle } from '@/features/automations/domain/types'
import {
  DEFAULT_NEWSLETTER_RICH_TEXT_CONTENT,
  escapeHtml,
  NEWSLETTER_RICH_TEXT_BLOCK_TYPE,
} from '@/lib/actions/newsletters/render'
import { sanitizeRichMediaHtml } from '@/lib/utils/html-sanitizer'
import { sanitizeExternalHttpUrl } from '@/lib/utils/url-validator'

/**
 * The blocks a drafted newsletter opens with in the newsletter builder.
 *
 * The chosen newsletter template owns the whole email frame — logo header, dividers,
 * footer, unsubscribe link — and only the body of its first Rich Text block is
 * replaced, so the draft renders the way that template was designed to. Nothing is
 * invented: a template with no Rich Text block is refused by name rather than quietly
 * patched, because a draft that renders broken in the builder is worse than none.
 *
 * With no template chosen (the builder's own "Blank" option) the newsletter gets one
 * Rich Text block, identical to the one the builder's block palette would add.
 */
export function buildAutomationNewsletterBlocks(
  templateBlocks: Record<string, unknown>,
  article: StructuredArticle
): Record<string, unknown> {
  const htmlContent = buildNewsletterBodyHtml(article)
  const blocks = Object.values(templateBlocks).filter(isStoredBlock)

  if (blocks.length === 0) {
    const id = `${NEWSLETTER_RICH_TEXT_BLOCK_TYPE}-${randomUUID()}`
    return {
      [id]: {
        id,
        type: NEWSLETTER_RICH_TEXT_BLOCK_TYPE,
        content: { ...DEFAULT_NEWSLETTER_RICH_TEXT_CONTENT, htmlContent },
        display_order: 0,
      },
    }
  }

  const body = [...blocks]
    .filter((block) => block.type === NEWSLETTER_RICH_TEXT_BLOCK_TYPE)
    .sort((first, second) => displayOrder(first) - displayOrder(second))[0]
  if (!body) throw new Error('The Newsletter template needs a Rich Text block')

  const result: Record<string, unknown> = {}
  for (const block of blocks) {
    result[block.id] = block === body
      ? { ...block, content: { ...DEFAULT_NEWSLETTER_RICH_TEXT_CONTENT, ...asContent(block.content), htmlContent } }
      : { ...block }
  }
  return result
}

/**
 * The subject line for the draft. Fixed text may use `{{title}}` for the AI's own
 * title, so a weekly roundup can read "Austin Weekly: <this week's headline>".
 */
export function resolveNewsletterSubject(
  config: NewsletterAutomationNode['config'],
  article: StructuredArticle
): string {
  // Replaced through a function, not a string: a title containing `$&` or `$$` — a
  // price in a headline is all it takes — would otherwise be read as a replacement
  // pattern and come out mangled.
  const subject = config.subjectMode === 'fixed'
    ? config.subjectText.replace(/\{\{\s*title\s*\}\}/gi, () => article.title)
    : article.title
  const trimmed = subject.trim()
  if (!trimmed) throw new Error('The newsletter subject line came out empty')
  return trimmed.slice(0, NEWSLETTER_SUBJECT_MAX)
}

/**
 * The article as an email body. Images are kept (unlike a Post's body) because the
 * newsletter renderer styles them for email, which is what carries a featured image
 * generated by an AI Image node into the newsletter as its header picture.
 */
function buildNewsletterBodyHtml(article: StructuredArticle): string {
  const body = sanitizeRichMediaHtml(article.html)
  if (!body.trim()) throw new Error('AI Agent article body was empty after safety checks')
  const featuredImage = sanitizeExternalHttpUrl(article.featuredImage)
  if (!featuredImage) return body
  return `<img src="${escapeHtml(featuredImage)}" alt="${escapeHtml(article.title)}" />${body}`
}

interface StoredNewsletterBlock {
  id: string
  type: string
  content?: unknown
  display_order?: unknown
}

// The shape the newsletter builder reads back: anything without an id and a type is
// ignored by the builder too, so it is dropped here rather than copied forward.
function isStoredBlock(value: unknown): value is StoredNewsletterBlock {
  return isRecord(value) && typeof value.id === 'string' && !!value.id && typeof value.type === 'string' && !!value.type
}

function displayOrder(block: StoredNewsletterBlock) {
  return typeof block.display_order === 'number' && Number.isFinite(block.display_order) ? block.display_order : 0
}

function asContent(value: unknown): Record<string, unknown> {
  return isRecord(value) ? value : {}
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}
