/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ChangeEmailRouteImport } from './routes/change-email'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportUnwantedSignInRouteImport } from './routes/report-unwanted-sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RevokeEmailChangeRouteImport } from './routes/revoke-email-change'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignInLinkRouteImport } from './routes/sign-in-link'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBacktestsRouteImport } from './routes/_authenticated/backtests'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated/changelog'
import { Route as AuthenticatedFlowRunsRouteImport } from './routes/_authenticated/flow-runs'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedTradeRouteImport } from './routes/_authenticated/trade'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin/ai'
import { Route as AuthenticatedAdminAiUsageRouteImport } from './routes/_authenticated/admin/ai-usage'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminAsterRouteImport } from './routes/_authenticated/admin/aster'
import { Route as AuthenticatedAdminAutomationsRouteImport } from './routes/_authenticated/admin/automations'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin/billing'
import { Route as AuthenticatedAdminContactsRouteImport } from './routes/_authenticated/admin/contacts'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminDevOutboxRouteImport } from './routes/_authenticated/admin/dev-outbox'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin/feedback'
import { Route as AuthenticatedAdminHyperLiquidRouteImport } from './routes/_authenticated/admin/hyper-liquid'
import { Route as AuthenticatedAdminKucoinRouteImport } from './routes/_authenticated/admin/kucoin'
import { Route as AuthenticatedAdminLighterRouteImport } from './routes/_authenticated/admin/lighter'
import { Route as AuthenticatedAdminMarketsRouteImport } from './routes/_authenticated/admin/markets'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminMembershipRouteImport } from './routes/_authenticated/admin/membership'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin/newsletter'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin/pages'
import { Route as AuthenticatedAdminPhemexRouteImport } from './routes/_authenticated/admin/phemex'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminRecipesRouteImport } from './routes/_authenticated/admin/recipes'
import { Route as AuthenticatedAdminReferralsRouteImport } from './routes/_authenticated/admin/referrals'
import { Route as AuthenticatedAdminSegmentsRouteImport } from './routes/_authenticated/admin/segments'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSolanaRouteImport } from './routes/_authenticated/admin/solana'
import { Route as AuthenticatedAdminSystemEmailsRouteImport } from './routes/_authenticated/admin/system-emails'
import { Route as AuthenticatedAdminTradingOverviewRouteImport } from './routes/_authenticated/admin/trading-overview'
import { Route as AuthenticatedAdminTrafficRouteImport } from './routes/_authenticated/admin/traffic'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedBacktestsGroupIdRouteImport } from './routes/_authenticated/backtests_.$groupId'
import { Route as AuthenticatedChangelogIndexRouteImport } from './routes/_authenticated/changelog/index'
import { Route as AuthenticatedChangelogWhatsNewRouteImport } from './routes/_authenticated/changelog/whats-new'
import { Route as AuthenticatedFlowRunsRunIdRouteImport } from './routes/_authenticated/flow-runs_.$runId'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiWebhooksResendRouteImport } from './routes/api/webhooks/resend'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as AuthenticatedAccountBillingSuccessRouteImport } from './routes/_authenticated/account/billing_.success'
import { Route as AuthenticatedAdminAutomationsAutomationIdRouteImport } from './routes/_authenticated/admin/automations_.$automationId'
import { Route as AuthenticatedAdminAutomationsTemplatesRouteImport } from './routes/_authenticated/admin/automations_.templates'
import { Route as AuthenticatedAdminNewsletterBroadcastIdRouteImport } from './routes/_authenticated/admin/newsletter_.$broadcastId'
import { Route as AuthenticatedAdminRecipesRecipeIdRouteImport } from './routes/_authenticated/admin/recipes_.$recipeId'
import { Route as AuthenticatedAdminSettingsTabRouteImport } from './routes/_authenticated/admin/settings/$tab'
import { Route as AuthenticatedAdminSettingsMarketsRouteImport } from './routes/_authenticated/admin/settings_.markets'
import { Route as AuthenticatedAdminSettingsTradingEngineRouteImport } from './routes/_authenticated/admin/settings_.trading-engine'
import { Route as AuthenticatedAdminSettingsTradingRulesRouteImport } from './routes/_authenticated/admin/settings_.trading-rules'
import { Route as AuthenticatedAdminSettingsTradingWidgetsRouteImport } from './routes/_authenticated/admin/settings_.trading-widgets'
import { Route as AuthenticatedAdminSystemEmailsKindRouteImport } from './routes/_authenticated/admin/system-emails_.$kind'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google_.callback'
import { Route as ApiV1NotificationsStreamRouteImport } from './routes/api/v1/notifications/stream'
import { Route as ApiV1TrafficViewRouteImport } from './routes/api/v1/traffic/view'
import { Route as AuthenticatedAdminAutomationsTemplatesTemplateKeyRouteImport } from './routes/_authenticated/admin/automations_.templates_.$templateKey'
import { Route as ApiV1MediaMediaIdFileRouteImport } from './routes/api/v1/media/$mediaId/file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeEmailRoute = ChangeEmailRouteImport.update({
  id: '/change-email',
  path: '/change-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportUnwantedSignInRoute = ReportUnwantedSignInRouteImport.update({
  id: '/report-unwanted-sign-in',
  path: '/report-unwanted-sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RevokeEmailChangeRoute = RevokeEmailChangeRouteImport.update({
  id: '/revoke-email-change',
  path: '/revoke-email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInLinkRoute = SignInLinkRouteImport.update({
  id: '/sign-in-link',
  path: '/sign-in-link',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBacktestsRoute = AuthenticatedBacktestsRouteImport.update({
  id: '/backtests',
  path: '/backtests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlowRunsRoute = AuthenticatedFlowRunsRouteImport.update({
  id: '/flow-runs',
  path: '/flow-runs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradeRoute = AuthenticatedTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAiUsageRoute =
  AuthenticatedAdminAiUsageRouteImport.update({
    id: '/ai-usage',
    path: '/ai-usage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAsterRoute = AuthenticatedAdminAsterRouteImport.update({
  id: '/aster',
  path: '/aster',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAutomationsRoute =
  AuthenticatedAdminAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactsRoute =
  AuthenticatedAdminContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDevOutboxRoute =
  AuthenticatedAdminDevOutboxRouteImport.update({
    id: '/dev-outbox',
    path: '/dev-outbox',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHyperLiquidRoute =
  AuthenticatedAdminHyperLiquidRouteImport.update({
    id: '/hyper-liquid',
    path: '/hyper-liquid',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKucoinRoute =
  AuthenticatedAdminKucoinRouteImport.update({
    id: '/kucoin',
    path: '/kucoin',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLighterRoute =
  AuthenticatedAdminLighterRouteImport.update({
    id: '/lighter',
    path: '/lighter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketsRoute =
  AuthenticatedAdminMarketsRouteImport.update({
    id: '/markets',
    path: '/markets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMembershipRoute =
  AuthenticatedAdminMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPhemexRoute =
  AuthenticatedAdminPhemexRouteImport.update({
    id: '/phemex',
    path: '/phemex',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRecipesRoute =
  AuthenticatedAdminRecipesRouteImport.update({
    id: '/recipes',
    path: '/recipes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReferralsRoute =
  AuthenticatedAdminReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSegmentsRoute =
  AuthenticatedAdminSegmentsRouteImport.update({
    id: '/segments',
    path: '/segments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSolanaRoute =
  AuthenticatedAdminSolanaRouteImport.update({
    id: '/solana',
    path: '/solana',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSystemEmailsRoute =
  AuthenticatedAdminSystemEmailsRouteImport.update({
    id: '/system-emails',
    path: '/system-emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTradingOverviewRoute =
  AuthenticatedAdminTradingOverviewRouteImport.update({
    id: '/trading-overview',
    path: '/trading-overview',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTrafficRoute =
  AuthenticatedAdminTrafficRouteImport.update({
    id: '/traffic',
    path: '/traffic',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedBacktestsGroupIdRoute =
  AuthenticatedBacktestsGroupIdRouteImport.update({
    id: '/backtests_/$groupId',
    path: '/backtests/$groupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChangelogIndexRoute =
  AuthenticatedChangelogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChangelogRoute,
  } as any)
const AuthenticatedChangelogWhatsNewRoute =
  AuthenticatedChangelogWhatsNewRouteImport.update({
    id: '/whats-new',
    path: '/whats-new',
    getParentRoute: () => AuthenticatedChangelogRoute,
  } as any)
const AuthenticatedFlowRunsRunIdRoute =
  AuthenticatedFlowRunsRunIdRouteImport.update({
    id: '/flow-runs_/$runId',
    path: '/flow-runs/$runId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksResendRoute = ApiWebhooksResendRouteImport.update({
  id: '/api/webhooks/resend',
  path: '/api/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountBillingSuccessRoute =
  AuthenticatedAccountBillingSuccessRouteImport.update({
    id: '/billing_/success',
    path: '/billing/success',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminAutomationsAutomationIdRoute =
  AuthenticatedAdminAutomationsAutomationIdRouteImport.update({
    id: '/automations_/$automationId',
    path: '/automations/$automationId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAutomationsTemplatesRoute =
  AuthenticatedAdminAutomationsTemplatesRouteImport.update({
    id: '/automations_/templates',
    path: '/automations/templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsletterBroadcastIdRoute =
  AuthenticatedAdminNewsletterBroadcastIdRouteImport.update({
    id: '/newsletter_/$broadcastId',
    path: '/newsletter/$broadcastId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecipesRecipeIdRoute =
  AuthenticatedAdminRecipesRecipeIdRouteImport.update({
    id: '/recipes_/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsTabRoute =
  AuthenticatedAdminSettingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsMarketsRoute =
  AuthenticatedAdminSettingsMarketsRouteImport.update({
    id: '/settings_/markets',
    path: '/settings/markets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsTradingEngineRoute =
  AuthenticatedAdminSettingsTradingEngineRouteImport.update({
    id: '/settings_/trading-engine',
    path: '/settings/trading-engine',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsTradingRulesRoute =
  AuthenticatedAdminSettingsTradingRulesRouteImport.update({
    id: '/settings_/trading-rules',
    path: '/settings/trading-rules',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsTradingWidgetsRoute =
  AuthenticatedAdminSettingsTradingWidgetsRouteImport.update({
    id: '/settings_/trading-widgets',
    path: '/settings/trading-widgets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSystemEmailsKindRoute =
  AuthenticatedAdminSystemEmailsKindRouteImport.update({
    id: '/system-emails_/$kind',
    path: '/system-emails/$kind',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google_/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1NotificationsStreamRoute =
  ApiV1NotificationsStreamRouteImport.update({
    id: '/api/v1/notifications/stream',
    path: '/api/v1/notifications/stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1TrafficViewRoute = ApiV1TrafficViewRouteImport.update({
  id: '/api/v1/traffic/view',
  path: '/api/v1/traffic/view',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAutomationsTemplatesTemplateKeyRoute =
  AuthenticatedAdminAutomationsTemplatesTemplateKeyRouteImport.update({
    id: '/automations_/templates_/$templateKey',
    path: '/automations/templates/$templateKey',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiV1MediaMediaIdFileRoute = ApiV1MediaMediaIdFileRouteImport.update({
  id: '/api/v1/media/$mediaId/file',
  path: '/api/v1/media/$mediaId/file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/change-email': typeof ChangeEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/report-unwanted-sign-in': typeof ReportUnwantedSignInRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revoke-email-change': typeof RevokeEmailChangeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sign-in-link': typeof SignInLinkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/backtests': typeof AuthenticatedBacktestsRoute
  '/changelog': typeof AuthenticatedChangelogRouteWithChildren
  '/flow-runs': typeof AuthenticatedFlowRunsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/ai-usage': typeof AuthenticatedAdminAiUsageRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/aster': typeof AuthenticatedAdminAsterRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dev-outbox': typeof AuthenticatedAdminDevOutboxRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/hyper-liquid': typeof AuthenticatedAdminHyperLiquidRoute
  '/admin/kucoin': typeof AuthenticatedAdminKucoinRoute
  '/admin/lighter': typeof AuthenticatedAdminLighterRoute
  '/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/membership': typeof AuthenticatedAdminMembershipRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/phemex': typeof AuthenticatedAdminPhemexRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/recipes': typeof AuthenticatedAdminRecipesRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/segments': typeof AuthenticatedAdminSegmentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/solana': typeof AuthenticatedAdminSolanaRoute
  '/admin/system-emails': typeof AuthenticatedAdminSystemEmailsRoute
  '/admin/trading-overview': typeof AuthenticatedAdminTradingOverviewRoute
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/backtests/$groupId': typeof AuthenticatedBacktestsGroupIdRoute
  '/changelog/whats-new': typeof AuthenticatedChangelogWhatsNewRoute
  '/flow-runs/$runId': typeof AuthenticatedFlowRunsRunIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/changelog/': typeof AuthenticatedChangelogIndexRoute
  '/account/billing/success': typeof AuthenticatedAccountBillingSuccessRoute
  '/admin/automations/$automationId': typeof AuthenticatedAdminAutomationsAutomationIdRoute
  '/admin/automations/templates': typeof AuthenticatedAdminAutomationsTemplatesRoute
  '/admin/newsletter/$broadcastId': typeof AuthenticatedAdminNewsletterBroadcastIdRoute
  '/admin/recipes/$recipeId': typeof AuthenticatedAdminRecipesRecipeIdRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/admin/settings/markets': typeof AuthenticatedAdminSettingsMarketsRoute
  '/admin/settings/trading-engine': typeof AuthenticatedAdminSettingsTradingEngineRoute
  '/admin/settings/trading-rules': typeof AuthenticatedAdminSettingsTradingRulesRoute
  '/admin/settings/trading-widgets': typeof AuthenticatedAdminSettingsTradingWidgetsRoute
  '/admin/system-emails/$kind': typeof AuthenticatedAdminSystemEmailsKindRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/v1/notifications/stream': typeof ApiV1NotificationsStreamRoute
  '/api/v1/traffic/view': typeof ApiV1TrafficViewRoute
  '/admin/automations/templates/$templateKey': typeof AuthenticatedAdminAutomationsTemplatesTemplateKeyRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/change-email': typeof ChangeEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/report-unwanted-sign-in': typeof ReportUnwantedSignInRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revoke-email-change': typeof RevokeEmailChangeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sign-in-link': typeof SignInLinkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/backtests': typeof AuthenticatedBacktestsRoute
  '/flow-runs': typeof AuthenticatedFlowRunsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/ai-usage': typeof AuthenticatedAdminAiUsageRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/aster': typeof AuthenticatedAdminAsterRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dev-outbox': typeof AuthenticatedAdminDevOutboxRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/hyper-liquid': typeof AuthenticatedAdminHyperLiquidRoute
  '/admin/kucoin': typeof AuthenticatedAdminKucoinRoute
  '/admin/lighter': typeof AuthenticatedAdminLighterRoute
  '/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/membership': typeof AuthenticatedAdminMembershipRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/phemex': typeof AuthenticatedAdminPhemexRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/recipes': typeof AuthenticatedAdminRecipesRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/segments': typeof AuthenticatedAdminSegmentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/solana': typeof AuthenticatedAdminSolanaRoute
  '/admin/system-emails': typeof AuthenticatedAdminSystemEmailsRoute
  '/admin/trading-overview': typeof AuthenticatedAdminTradingOverviewRoute
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/backtests/$groupId': typeof AuthenticatedBacktestsGroupIdRoute
  '/changelog/whats-new': typeof AuthenticatedChangelogWhatsNewRoute
  '/flow-runs/$runId': typeof AuthenticatedFlowRunsRunIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/changelog': typeof AuthenticatedChangelogIndexRoute
  '/account/billing/success': typeof AuthenticatedAccountBillingSuccessRoute
  '/admin/automations/$automationId': typeof AuthenticatedAdminAutomationsAutomationIdRoute
  '/admin/automations/templates': typeof AuthenticatedAdminAutomationsTemplatesRoute
  '/admin/newsletter/$broadcastId': typeof AuthenticatedAdminNewsletterBroadcastIdRoute
  '/admin/recipes/$recipeId': typeof AuthenticatedAdminRecipesRecipeIdRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/admin/settings/markets': typeof AuthenticatedAdminSettingsMarketsRoute
  '/admin/settings/trading-engine': typeof AuthenticatedAdminSettingsTradingEngineRoute
  '/admin/settings/trading-rules': typeof AuthenticatedAdminSettingsTradingRulesRoute
  '/admin/settings/trading-widgets': typeof AuthenticatedAdminSettingsTradingWidgetsRoute
  '/admin/system-emails/$kind': typeof AuthenticatedAdminSystemEmailsKindRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/v1/notifications/stream': typeof ApiV1NotificationsStreamRoute
  '/api/v1/traffic/view': typeof ApiV1TrafficViewRoute
  '/admin/automations/templates/$templateKey': typeof AuthenticatedAdminAutomationsTemplatesTemplateKeyRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-email': typeof ChangeEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/report-unwanted-sign-in': typeof ReportUnwantedSignInRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revoke-email-change': typeof RevokeEmailChangeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sign-in-link': typeof SignInLinkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/backtests': typeof AuthenticatedBacktestsRoute
  '/_authenticated/changelog': typeof AuthenticatedChangelogRouteWithChildren
  '/_authenticated/flow-runs': typeof AuthenticatedFlowRunsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/trade': typeof AuthenticatedTradeRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/api/health': typeof ApiHealthRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/ai-usage': typeof AuthenticatedAdminAiUsageRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/aster': typeof AuthenticatedAdminAsterRoute
  '/_authenticated/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/dev-outbox': typeof AuthenticatedAdminDevOutboxRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin/hyper-liquid': typeof AuthenticatedAdminHyperLiquidRoute
  '/_authenticated/admin/kucoin': typeof AuthenticatedAdminKucoinRoute
  '/_authenticated/admin/lighter': typeof AuthenticatedAdminLighterRoute
  '/_authenticated/admin/markets': typeof AuthenticatedAdminMarketsRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/membership': typeof AuthenticatedAdminMembershipRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/phemex': typeof AuthenticatedAdminPhemexRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/recipes': typeof AuthenticatedAdminRecipesRoute
  '/_authenticated/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/_authenticated/admin/segments': typeof AuthenticatedAdminSegmentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/admin/solana': typeof AuthenticatedAdminSolanaRoute
  '/_authenticated/admin/system-emails': typeof AuthenticatedAdminSystemEmailsRoute
  '/_authenticated/admin/trading-overview': typeof AuthenticatedAdminTradingOverviewRoute
  '/_authenticated/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/backtests_/$groupId': typeof AuthenticatedBacktestsGroupIdRoute
  '/_authenticated/changelog/whats-new': typeof AuthenticatedChangelogWhatsNewRoute
  '/_authenticated/flow-runs_/$runId': typeof AuthenticatedFlowRunsRunIdRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/webhooks/resend': typeof ApiWebhooksResendRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/changelog/': typeof AuthenticatedChangelogIndexRoute
  '/_authenticated/account/billing_/success': typeof AuthenticatedAccountBillingSuccessRoute
  '/_authenticated/admin/automations_/$automationId': typeof AuthenticatedAdminAutomationsAutomationIdRoute
  '/_authenticated/admin/automations_/templates': typeof AuthenticatedAdminAutomationsTemplatesRoute
  '/_authenticated/admin/newsletter_/$broadcastId': typeof AuthenticatedAdminNewsletterBroadcastIdRoute
  '/_authenticated/admin/recipes_/$recipeId': typeof AuthenticatedAdminRecipesRecipeIdRoute
  '/_authenticated/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/_authenticated/admin/settings_/markets': typeof AuthenticatedAdminSettingsMarketsRoute
  '/_authenticated/admin/settings_/trading-engine': typeof AuthenticatedAdminSettingsTradingEngineRoute
  '/_authenticated/admin/settings_/trading-rules': typeof AuthenticatedAdminSettingsTradingRulesRoute
  '/_authenticated/admin/settings_/trading-widgets': typeof AuthenticatedAdminSettingsTradingWidgetsRoute
  '/_authenticated/admin/system-emails_/$kind': typeof AuthenticatedAdminSystemEmailsKindRoute
  '/api/auth/google_/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/v1/notifications/stream': typeof ApiV1NotificationsStreamRoute
  '/api/v1/traffic/view': typeof ApiV1TrafficViewRoute
  '/_authenticated/admin/automations_/templates_/$templateKey': typeof AuthenticatedAdminAutomationsTemplatesTemplateKeyRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/change-email'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/pricing'
    | '/register'
    | '/report-unwanted-sign-in'
    | '/reset-password'
    | '/revoke-email-change'
    | '/robots.txt'
    | '/search'
    | '/sign-in-link'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/verify-email'
    | '/account'
    | '/admin'
    | '/backtests'
    | '/changelog'
    | '/flow-runs'
    | '/home'
    | '/trade'
    | '/workspaces'
    | '/api/health'
    | '/admin/ai'
    | '/admin/ai-usage'
    | '/admin/announcements'
    | '/admin/aster'
    | '/admin/automations'
    | '/admin/billing'
    | '/admin/contacts'
    | '/admin/dashboard'
    | '/admin/dev-outbox'
    | '/admin/feedback'
    | '/admin/hyper-liquid'
    | '/admin/kucoin'
    | '/admin/lighter'
    | '/admin/markets'
    | '/admin/media'
    | '/admin/membership'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/phemex'
    | '/admin/plans'
    | '/admin/recipes'
    | '/admin/referrals'
    | '/admin/segments'
    | '/admin/settings'
    | '/admin/solana'
    | '/admin/system-emails'
    | '/admin/trading-overview'
    | '/admin/traffic'
    | '/admin/users'
    | '/backtests/$groupId'
    | '/changelog/whats-new'
    | '/flow-runs/$runId'
    | '/api/auth/google'
    | '/api/webhooks/resend'
    | '/api/webhooks/stripe'
    | '/admin/'
    | '/changelog/'
    | '/account/billing/success'
    | '/admin/automations/$automationId'
    | '/admin/automations/templates'
    | '/admin/newsletter/$broadcastId'
    | '/admin/recipes/$recipeId'
    | '/admin/settings/$tab'
    | '/admin/settings/markets'
    | '/admin/settings/trading-engine'
    | '/admin/settings/trading-rules'
    | '/admin/settings/trading-widgets'
    | '/admin/system-emails/$kind'
    | '/api/auth/google/callback'
    | '/api/v1/notifications/stream'
    | '/api/v1/traffic/view'
    | '/admin/automations/templates/$templateKey'
    | '/api/v1/media/$mediaId/file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/change-email'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/pricing'
    | '/register'
    | '/report-unwanted-sign-in'
    | '/reset-password'
    | '/revoke-email-change'
    | '/robots.txt'
    | '/search'
    | '/sign-in-link'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/verify-email'
    | '/account'
    | '/backtests'
    | '/flow-runs'
    | '/home'
    | '/trade'
    | '/workspaces'
    | '/api/health'
    | '/admin/ai'
    | '/admin/ai-usage'
    | '/admin/announcements'
    | '/admin/aster'
    | '/admin/automations'
    | '/admin/billing'
    | '/admin/contacts'
    | '/admin/dashboard'
    | '/admin/dev-outbox'
    | '/admin/feedback'
    | '/admin/hyper-liquid'
    | '/admin/kucoin'
    | '/admin/lighter'
    | '/admin/markets'
    | '/admin/media'
    | '/admin/membership'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/phemex'
    | '/admin/plans'
    | '/admin/recipes'
    | '/admin/referrals'
    | '/admin/segments'
    | '/admin/settings'
    | '/admin/solana'
    | '/admin/system-emails'
    | '/admin/trading-overview'
    | '/admin/traffic'
    | '/admin/users'
    | '/backtests/$groupId'
    | '/changelog/whats-new'
    | '/flow-runs/$runId'
    | '/api/auth/google'
    | '/api/webhooks/resend'
    | '/api/webhooks/stripe'
    | '/admin'
    | '/changelog'
    | '/account/billing/success'
    | '/admin/automations/$automationId'
    | '/admin/automations/templates'
    | '/admin/newsletter/$broadcastId'
    | '/admin/recipes/$recipeId'
    | '/admin/settings/$tab'
    | '/admin/settings/markets'
    | '/admin/settings/trading-engine'
    | '/admin/settings/trading-rules'
    | '/admin/settings/trading-widgets'
    | '/admin/system-emails/$kind'
    | '/api/auth/google/callback'
    | '/api/v1/notifications/stream'
    | '/api/v1/traffic/view'
    | '/admin/automations/templates/$templateKey'
    | '/api/v1/media/$mediaId/file'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/change-email'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/pricing'
    | '/register'
    | '/report-unwanted-sign-in'
    | '/reset-password'
    | '/revoke-email-change'
    | '/robots.txt'
    | '/search'
    | '/sign-in-link'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/verify-email'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/backtests'
    | '/_authenticated/changelog'
    | '/_authenticated/flow-runs'
    | '/_authenticated/home'
    | '/_authenticated/trade'
    | '/_authenticated/workspaces'
    | '/api/health'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/ai-usage'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/aster'
    | '/_authenticated/admin/automations'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/contacts'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/dev-outbox'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/hyper-liquid'
    | '/_authenticated/admin/kucoin'
    | '/_authenticated/admin/lighter'
    | '/_authenticated/admin/markets'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/membership'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/phemex'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/recipes'
    | '/_authenticated/admin/referrals'
    | '/_authenticated/admin/segments'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/solana'
    | '/_authenticated/admin/system-emails'
    | '/_authenticated/admin/trading-overview'
    | '/_authenticated/admin/traffic'
    | '/_authenticated/admin/users'
    | '/_authenticated/backtests_/$groupId'
    | '/_authenticated/changelog/whats-new'
    | '/_authenticated/flow-runs_/$runId'
    | '/api/auth/google'
    | '/api/webhooks/resend'
    | '/api/webhooks/stripe'
    | '/_authenticated/admin/'
    | '/_authenticated/changelog/'
    | '/_authenticated/account/billing_/success'
    | '/_authenticated/admin/automations_/$automationId'
    | '/_authenticated/admin/automations_/templates'
    | '/_authenticated/admin/newsletter_/$broadcastId'
    | '/_authenticated/admin/recipes_/$recipeId'
    | '/_authenticated/admin/settings/$tab'
    | '/_authenticated/admin/settings_/markets'
    | '/_authenticated/admin/settings_/trading-engine'
    | '/_authenticated/admin/settings_/trading-rules'
    | '/_authenticated/admin/settings_/trading-widgets'
    | '/_authenticated/admin/system-emails_/$kind'
    | '/api/auth/google_/callback'
    | '/api/v1/notifications/stream'
    | '/api/v1/traffic/view'
    | '/_authenticated/admin/automations_/templates_/$templateKey'
    | '/api/v1/media/$mediaId/file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangeEmailRoute: typeof ChangeEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ReportUnwantedSignInRoute: typeof ReportUnwantedSignInRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RevokeEmailChangeRoute: typeof RevokeEmailChangeRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SignInLinkRoute: typeof SignInLinkRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiWebhooksResendRoute: typeof ApiWebhooksResendRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiV1NotificationsStreamRoute: typeof ApiV1NotificationsStreamRoute
  ApiV1TrafficViewRoute: typeof ApiV1TrafficViewRoute
  ApiV1MediaMediaIdFileRoute: typeof ApiV1MediaMediaIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-email': {
      id: '/change-email'
      path: '/change-email'
      fullPath: '/change-email'
      preLoaderRoute: typeof ChangeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-unwanted-sign-in': {
      id: '/report-unwanted-sign-in'
      path: '/report-unwanted-sign-in'
      fullPath: '/report-unwanted-sign-in'
      preLoaderRoute: typeof ReportUnwantedSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revoke-email-change': {
      id: '/revoke-email-change'
      path: '/revoke-email-change'
      fullPath: '/revoke-email-change'
      preLoaderRoute: typeof RevokeEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in-link': {
      id: '/sign-in-link'
      path: '/sign-in-link'
      fullPath: '/sign-in-link'
      preLoaderRoute: typeof SignInLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backtests': {
      id: '/_authenticated/backtests'
      path: '/backtests'
      fullPath: '/backtests'
      preLoaderRoute: typeof AuthenticatedBacktestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flow-runs': {
      id: '/_authenticated/flow-runs'
      path: '/flow-runs'
      fullPath: '/flow-runs'
      preLoaderRoute: typeof AuthenticatedFlowRunsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trade': {
      id: '/_authenticated/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AuthenticatedTradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai-usage': {
      id: '/_authenticated/admin/ai-usage'
      path: '/ai-usage'
      fullPath: '/admin/ai-usage'
      preLoaderRoute: typeof AuthenticatedAdminAiUsageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aster': {
      id: '/_authenticated/admin/aster'
      path: '/aster'
      fullPath: '/admin/aster'
      preLoaderRoute: typeof AuthenticatedAdminAsterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/automations': {
      id: '/_authenticated/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contacts': {
      id: '/_authenticated/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AuthenticatedAdminContactsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dev-outbox': {
      id: '/_authenticated/admin/dev-outbox'
      path: '/dev-outbox'
      fullPath: '/admin/dev-outbox'
      preLoaderRoute: typeof AuthenticatedAdminDevOutboxRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hyper-liquid': {
      id: '/_authenticated/admin/hyper-liquid'
      path: '/hyper-liquid'
      fullPath: '/admin/hyper-liquid'
      preLoaderRoute: typeof AuthenticatedAdminHyperLiquidRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kucoin': {
      id: '/_authenticated/admin/kucoin'
      path: '/kucoin'
      fullPath: '/admin/kucoin'
      preLoaderRoute: typeof AuthenticatedAdminKucoinRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lighter': {
      id: '/_authenticated/admin/lighter'
      path: '/lighter'
      fullPath: '/admin/lighter'
      preLoaderRoute: typeof AuthenticatedAdminLighterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/markets': {
      id: '/_authenticated/admin/markets'
      path: '/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AuthenticatedAdminMarketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/membership': {
      id: '/_authenticated/admin/membership'
      path: '/membership'
      fullPath: '/admin/membership'
      preLoaderRoute: typeof AuthenticatedAdminMembershipRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/phemex': {
      id: '/_authenticated/admin/phemex'
      path: '/phemex'
      fullPath: '/admin/phemex'
      preLoaderRoute: typeof AuthenticatedAdminPhemexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recipes': {
      id: '/_authenticated/admin/recipes'
      path: '/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AuthenticatedAdminRecipesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/referrals': {
      id: '/_authenticated/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AuthenticatedAdminReferralsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/segments': {
      id: '/_authenticated/admin/segments'
      path: '/segments'
      fullPath: '/admin/segments'
      preLoaderRoute: typeof AuthenticatedAdminSegmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/solana': {
      id: '/_authenticated/admin/solana'
      path: '/solana'
      fullPath: '/admin/solana'
      preLoaderRoute: typeof AuthenticatedAdminSolanaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/system-emails': {
      id: '/_authenticated/admin/system-emails'
      path: '/system-emails'
      fullPath: '/admin/system-emails'
      preLoaderRoute: typeof AuthenticatedAdminSystemEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trading-overview': {
      id: '/_authenticated/admin/trading-overview'
      path: '/trading-overview'
      fullPath: '/admin/trading-overview'
      preLoaderRoute: typeof AuthenticatedAdminTradingOverviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/traffic': {
      id: '/_authenticated/admin/traffic'
      path: '/traffic'
      fullPath: '/admin/traffic'
      preLoaderRoute: typeof AuthenticatedAdminTrafficRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/backtests_/$groupId': {
      id: '/_authenticated/backtests_/$groupId'
      path: '/backtests/$groupId'
      fullPath: '/backtests/$groupId'
      preLoaderRoute: typeof AuthenticatedBacktestsGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/changelog/': {
      id: '/_authenticated/changelog/'
      path: '/'
      fullPath: '/changelog/'
      preLoaderRoute: typeof AuthenticatedChangelogIndexRouteImport
      parentRoute: typeof AuthenticatedChangelogRoute
    }
    '/_authenticated/changelog/whats-new': {
      id: '/_authenticated/changelog/whats-new'
      path: '/whats-new'
      fullPath: '/changelog/whats-new'
      preLoaderRoute: typeof AuthenticatedChangelogWhatsNewRouteImport
      parentRoute: typeof AuthenticatedChangelogRoute
    }
    '/_authenticated/flow-runs_/$runId': {
      id: '/_authenticated/flow-runs_/$runId'
      path: '/flow-runs/$runId'
      fullPath: '/flow-runs/$runId'
      preLoaderRoute: typeof AuthenticatedFlowRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/resend': {
      id: '/api/webhooks/resend'
      path: '/api/webhooks/resend'
      fullPath: '/api/webhooks/resend'
      preLoaderRoute: typeof ApiWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/billing_/success': {
      id: '/_authenticated/account/billing_/success'
      path: '/billing/success'
      fullPath: '/account/billing/success'
      preLoaderRoute: typeof AuthenticatedAccountBillingSuccessRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/automations_/$automationId': {
      id: '/_authenticated/admin/automations_/$automationId'
      path: '/automations/$automationId'
      fullPath: '/admin/automations/$automationId'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsAutomationIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/automations_/templates': {
      id: '/_authenticated/admin/automations_/templates'
      path: '/automations/templates'
      fullPath: '/admin/automations/templates'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/newsletter_/$broadcastId': {
      id: '/_authenticated/admin/newsletter_/$broadcastId'
      path: '/newsletter/$broadcastId'
      fullPath: '/admin/newsletter/$broadcastId'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterBroadcastIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recipes_/$recipeId': {
      id: '/_authenticated/admin/recipes_/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/admin/recipes/$recipeId'
      preLoaderRoute: typeof AuthenticatedAdminRecipesRecipeIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/$tab': {
      id: '/_authenticated/admin/settings/$tab'
      path: '/$tab'
      fullPath: '/admin/settings/$tab'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTabRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/settings_/markets': {
      id: '/_authenticated/admin/settings_/markets'
      path: '/settings/markets'
      fullPath: '/admin/settings/markets'
      preLoaderRoute: typeof AuthenticatedAdminSettingsMarketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings_/trading-engine': {
      id: '/_authenticated/admin/settings_/trading-engine'
      path: '/settings/trading-engine'
      fullPath: '/admin/settings/trading-engine'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTradingEngineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings_/trading-rules': {
      id: '/_authenticated/admin/settings_/trading-rules'
      path: '/settings/trading-rules'
      fullPath: '/admin/settings/trading-rules'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTradingRulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings_/trading-widgets': {
      id: '/_authenticated/admin/settings_/trading-widgets'
      path: '/settings/trading-widgets'
      fullPath: '/admin/settings/trading-widgets'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTradingWidgetsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/system-emails_/$kind': {
      id: '/_authenticated/admin/system-emails_/$kind'
      path: '/system-emails/$kind'
      fullPath: '/admin/system-emails/$kind'
      preLoaderRoute: typeof AuthenticatedAdminSystemEmailsKindRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/auth/google_/callback': {
      id: '/api/auth/google_/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/notifications/stream': {
      id: '/api/v1/notifications/stream'
      path: '/api/v1/notifications/stream'
      fullPath: '/api/v1/notifications/stream'
      preLoaderRoute: typeof ApiV1NotificationsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/traffic/view': {
      id: '/api/v1/traffic/view'
      path: '/api/v1/traffic/view'
      fullPath: '/api/v1/traffic/view'
      preLoaderRoute: typeof ApiV1TrafficViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/automations_/templates_/$templateKey': {
      id: '/_authenticated/admin/automations_/templates_/$templateKey'
      path: '/automations/templates/$templateKey'
      fullPath: '/admin/automations/templates/$templateKey'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsTemplatesTemplateKeyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/v1/media/$mediaId/file': {
      id: '/api/v1/media/$mediaId/file'
      path: '/api/v1/media/$mediaId/file'
      fullPath: '/api/v1/media/$mediaId/file'
      preLoaderRoute: typeof ApiV1MediaMediaIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountBillingSuccessRoute: typeof AuthenticatedAccountBillingSuccessRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountBillingSuccessRoute:
    AuthenticatedAccountBillingSuccessRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsTabRoute: typeof AuthenticatedAdminSettingsTabRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsTabRoute: AuthenticatedAdminSettingsTabRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAiUsageRoute: typeof AuthenticatedAdminAiUsageRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminAsterRoute: typeof AuthenticatedAdminAsterRoute
  AuthenticatedAdminAutomationsRoute: typeof AuthenticatedAdminAutomationsRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminContactsRoute: typeof AuthenticatedAdminContactsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDevOutboxRoute: typeof AuthenticatedAdminDevOutboxRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminHyperLiquidRoute: typeof AuthenticatedAdminHyperLiquidRoute
  AuthenticatedAdminKucoinRoute: typeof AuthenticatedAdminKucoinRoute
  AuthenticatedAdminLighterRoute: typeof AuthenticatedAdminLighterRoute
  AuthenticatedAdminMarketsRoute: typeof AuthenticatedAdminMarketsRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMembershipRoute: typeof AuthenticatedAdminMembershipRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPhemexRoute: typeof AuthenticatedAdminPhemexRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminRecipesRoute: typeof AuthenticatedAdminRecipesRoute
  AuthenticatedAdminReferralsRoute: typeof AuthenticatedAdminReferralsRoute
  AuthenticatedAdminSegmentsRoute: typeof AuthenticatedAdminSegmentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAdminSolanaRoute: typeof AuthenticatedAdminSolanaRoute
  AuthenticatedAdminSystemEmailsRoute: typeof AuthenticatedAdminSystemEmailsRoute
  AuthenticatedAdminTradingOverviewRoute: typeof AuthenticatedAdminTradingOverviewRoute
  AuthenticatedAdminTrafficRoute: typeof AuthenticatedAdminTrafficRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAutomationsAutomationIdRoute: typeof AuthenticatedAdminAutomationsAutomationIdRoute
  AuthenticatedAdminAutomationsTemplatesRoute: typeof AuthenticatedAdminAutomationsTemplatesRoute
  AuthenticatedAdminNewsletterBroadcastIdRoute: typeof AuthenticatedAdminNewsletterBroadcastIdRoute
  AuthenticatedAdminRecipesRecipeIdRoute: typeof AuthenticatedAdminRecipesRecipeIdRoute
  AuthenticatedAdminSettingsMarketsRoute: typeof AuthenticatedAdminSettingsMarketsRoute
  AuthenticatedAdminSettingsTradingEngineRoute: typeof AuthenticatedAdminSettingsTradingEngineRoute
  AuthenticatedAdminSettingsTradingRulesRoute: typeof AuthenticatedAdminSettingsTradingRulesRoute
  AuthenticatedAdminSettingsTradingWidgetsRoute: typeof AuthenticatedAdminSettingsTradingWidgetsRoute
  AuthenticatedAdminSystemEmailsKindRoute: typeof AuthenticatedAdminSystemEmailsKindRoute
  AuthenticatedAdminAutomationsTemplatesTemplateKeyRoute: typeof AuthenticatedAdminAutomationsTemplatesTemplateKeyRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminAiUsageRoute: AuthenticatedAdminAiUsageRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminAsterRoute: AuthenticatedAdminAsterRoute,
  AuthenticatedAdminAutomationsRoute: AuthenticatedAdminAutomationsRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminContactsRoute: AuthenticatedAdminContactsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDevOutboxRoute: AuthenticatedAdminDevOutboxRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminHyperLiquidRoute: AuthenticatedAdminHyperLiquidRoute,
  AuthenticatedAdminKucoinRoute: AuthenticatedAdminKucoinRoute,
  AuthenticatedAdminLighterRoute: AuthenticatedAdminLighterRoute,
  AuthenticatedAdminMarketsRoute: AuthenticatedAdminMarketsRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminMembershipRoute: AuthenticatedAdminMembershipRoute,
  AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminPhemexRoute: AuthenticatedAdminPhemexRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminRecipesRoute: AuthenticatedAdminRecipesRoute,
  AuthenticatedAdminReferralsRoute: AuthenticatedAdminReferralsRoute,
  AuthenticatedAdminSegmentsRoute: AuthenticatedAdminSegmentsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
  AuthenticatedAdminSolanaRoute: AuthenticatedAdminSolanaRoute,
  AuthenticatedAdminSystemEmailsRoute: AuthenticatedAdminSystemEmailsRoute,
  AuthenticatedAdminTradingOverviewRoute:
    AuthenticatedAdminTradingOverviewRoute,
  AuthenticatedAdminTrafficRoute: AuthenticatedAdminTrafficRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAutomationsAutomationIdRoute:
    AuthenticatedAdminAutomationsAutomationIdRoute,
  AuthenticatedAdminAutomationsTemplatesRoute:
    AuthenticatedAdminAutomationsTemplatesRoute,
  AuthenticatedAdminNewsletterBroadcastIdRoute:
    AuthenticatedAdminNewsletterBroadcastIdRoute,
  AuthenticatedAdminRecipesRecipeIdRoute:
    AuthenticatedAdminRecipesRecipeIdRoute,
  AuthenticatedAdminSettingsMarketsRoute:
    AuthenticatedAdminSettingsMarketsRoute,
  AuthenticatedAdminSettingsTradingEngineRoute:
    AuthenticatedAdminSettingsTradingEngineRoute,
  AuthenticatedAdminSettingsTradingRulesRoute:
    AuthenticatedAdminSettingsTradingRulesRoute,
  AuthenticatedAdminSettingsTradingWidgetsRoute:
    AuthenticatedAdminSettingsTradingWidgetsRoute,
  AuthenticatedAdminSystemEmailsKindRoute:
    AuthenticatedAdminSystemEmailsKindRoute,
  AuthenticatedAdminAutomationsTemplatesTemplateKeyRoute:
    AuthenticatedAdminAutomationsTemplatesTemplateKeyRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedChangelogRouteChildren {
  AuthenticatedChangelogWhatsNewRoute: typeof AuthenticatedChangelogWhatsNewRoute
  AuthenticatedChangelogIndexRoute: typeof AuthenticatedChangelogIndexRoute
}

const AuthenticatedChangelogRouteChildren: AuthenticatedChangelogRouteChildren =
  {
    AuthenticatedChangelogWhatsNewRoute: AuthenticatedChangelogWhatsNewRoute,
    AuthenticatedChangelogIndexRoute: AuthenticatedChangelogIndexRoute,
  }

const AuthenticatedChangelogRouteWithChildren =
  AuthenticatedChangelogRoute._addFileChildren(
    AuthenticatedChangelogRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBacktestsRoute: typeof AuthenticatedBacktestsRoute
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRouteWithChildren
  AuthenticatedFlowRunsRoute: typeof AuthenticatedFlowRunsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedTradeRoute: typeof AuthenticatedTradeRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedBacktestsGroupIdRoute: typeof AuthenticatedBacktestsGroupIdRoute
  AuthenticatedFlowRunsRunIdRoute: typeof AuthenticatedFlowRunsRunIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBacktestsRoute: AuthenticatedBacktestsRoute,
  AuthenticatedChangelogRoute: AuthenticatedChangelogRouteWithChildren,
  AuthenticatedFlowRunsRoute: AuthenticatedFlowRunsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedTradeRoute: AuthenticatedTradeRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedBacktestsGroupIdRoute: AuthenticatedBacktestsGroupIdRoute,
  AuthenticatedFlowRunsRunIdRoute: AuthenticatedFlowRunsRunIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangeEmailRoute: ChangeEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ReportUnwantedSignInRoute: ReportUnwantedSignInRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RevokeEmailChangeRoute: RevokeEmailChangeRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SignInLinkRoute: SignInLinkRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiWebhooksResendRoute: ApiWebhooksResendRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiV1NotificationsStreamRoute: ApiV1NotificationsStreamRoute,
  ApiV1TrafficViewRoute: ApiV1TrafficViewRoute,
  ApiV1MediaMediaIdFileRoute: ApiV1MediaMediaIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
