"use client"

import { useState, useEffect } from "react"
import { Dialog } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardGroup, CardHeader } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field"
import { CheckCircle } from "lucide-react"
import { DashboardModalContent, DashboardModalCardTitle } from "@/components/admin/layout/dashboard/modals"
import { generateSlug } from "@/lib/utils/slug"
import type { AccountPage } from "@/lib/actions/account-pages/account-pages-actions"
import type { SiteWithTheme } from "@/lib/actions/sites/site-actions"

interface UpdateAccountPageFormData {
  title?: string
  slug?: string
  meta_description?: string | null
  is_default?: boolean
  is_published?: boolean
}

interface AccountPageSettingsModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  page: AccountPage | null
  site: SiteWithTheme | null
  onSuccess?: (updatedPage: AccountPage) => void
}

export function AccountPageSettingsModal({
  open,
  onOpenChange,
  page,
  onSuccess,
}: AccountPageSettingsModalProps) {
  const [formData, setFormData] = useState<UpdateAccountPageFormData>({})
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [saveMessage, setSaveMessage] = useState<string | null>(null)
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false)

  const handleTitleChange = (title: string) => {
    setFormData((prev) => ({
      ...prev,
      title,
      slug: slugManuallyEdited ? prev.slug : generateSlug(title),
    }))
  }

  const handleSlugChange = (slug: string) => {
    if (slug === "") {
      setSlugManuallyEdited(false)
      setFormData((prev) => ({ ...prev, slug: generateSlug(prev.title || "") }))
      return
    }

    setSlugManuallyEdited(true)
    setFormData((prev) => ({ ...prev, slug }))
  }

  useEffect(() => {
    if (!page) return

    setFormData({
      title: page.title,
      slug: page.slug,
      meta_description: page.meta_description || "",
      is_default: page.is_default,
      is_published: page.is_published,
    })

    const autoGeneratedSlug = generateSlug(page.title)
    setSlugManuallyEdited(page.slug !== autoGeneratedSlug)
    setError(null)
  }, [page])

  useEffect(() => {
    if (!open) {
      setSaveMessage(null)
      setError(null)
    }
  }, [open])

  const handleSaveDraft = async () => {
    if (!formData.title?.trim()) {
      setError("Page title is required")
      return
    }

    if (!page) {
      setError("No page selected")
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)

      const draftData = { ...formData, is_published: false }
      const response = await fetch(`/api/account-pages/${page.id}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(draftData),
      })

      const result = await response.json()

      if (!response.ok || result.error) {
        setError(result.error || "Failed to save account page as draft")
        return
      }

      if (result.data) {
        setSaveMessage("Account page saved as draft")
        onSuccess?.(result.data)
        setTimeout(() => {
          setSaveMessage(null)
        }, 3000)
      }
    } catch (err) {
      setError("Failed to save account page as draft")
    } finally {
      setSaving(false)
    }
  }

  const handlePublish = async () => {
    if (!formData.title?.trim()) {
      setError("Page title is required")
      return
    }

    if (!page) {
      setError("No page selected")
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)

      const publishData = { ...formData, is_published: true }
      const response = await fetch(`/api/account-pages/${page.id}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(publishData),
      })

      const result = await response.json()

      if (!response.ok || result.error) {
        setError(result.error || "Failed to publish account page")
        return
      }

      if (result.data) {
        setSaveMessage(page.is_published ? "Account page updated" : "Account page published")
        setFormData((prev) => ({ ...prev, is_published: true }))
        onSuccess?.(result.data)
        setTimeout(() => {
          setSaveMessage(null)
        }, 3000)
      }
    } catch (err) {
      setError("Failed to publish account page")
    } finally {
      setSaving(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    await handleSaveDraft()
  }

  if (!page) {
    return null
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <form onSubmit={handleSubmit} className="contents">
        <DashboardModalContent
          title={
            <span className="flex items-center gap-3">
              Configure settings for &quot;{page.title}&quot;
              <span className="flex items-center space-x-2">
                <span className={`h-2 w-2 rounded-full ${page.is_published ? "bg-green-500" : "bg-gray-400"}`} />
                <span className="text-sm font-medium">{page.is_published ? "Published" : "Draft"}</span>
              </span>
            </span>
          }
          footer={
            <>
              {saveMessage ? (
                <div className="flex items-center gap-2 rounded-md border border-green-200 bg-green-50 px-3 py-1.5">
                  <CheckCircle className="h-4 w-4 text-green-600" />
                  <span className="text-sm font-medium text-green-700">{saveMessage}</span>
                </div>
              ) : (
                <div />
              )}
              <div className="flex items-center space-x-2">
                <Button type="button" variant="outline" onClick={() => onOpenChange(false)} disabled={saving}>
                  Cancel
                </Button>
                <Button type="submit" variant="outline" disabled={saving}>
                  {saving ? "Saving..." : "Save as Draft"}
                </Button>
                <Button type="button" onClick={handlePublish} disabled={saving}>
                  {saving ? (page.is_published ? "Saving..." : "Publishing...") : page.is_published ? "Save" : "Publish"}
                </Button>
              </div>
            </>
          }
          footerClassName="sm:justify-between"
        >
          {error && (
            <div className="px-6 pb-2">
              <div className="rounded-lg border border-red-200 bg-red-50 p-3">
                <p className="text-sm text-red-800">{error}</p>
              </div>
            </div>
          )}
          <CardGroup className="grid">
            <Card>
              <CardHeader className="p-4 pb-3">
                <DashboardModalCardTitle>Page setup</DashboardModalCardTitle>
              </CardHeader>
              <CardContent className="grid gap-4 p-4 pt-0">
                <Field>
                  <FieldLabel htmlFor="modal-title">Page Title *</FieldLabel>
                  <Input
                    id="modal-title"
                    value={formData.title || ""}
                    onChange={(e) => handleTitleChange(e.target.value)}
                    placeholder="Enter page title"
                    required
                  />
                </Field>
                <Field>
                  <FieldLabel htmlFor="modal-slug">Page URL</FieldLabel>
                  <Input
                    id="modal-slug"
                    value={formData.slug || ""}
                    onChange={(e) => handleSlugChange(e.target.value)}
                    placeholder="page-url-slug"
                  />
                  <FieldDescription>
                    {slugManuallyEdited
                      ? "Custom URL slug. Clear this field to auto-generate from title again."
                      : "Auto-generated from title. Account pages render under /account."}
                  </FieldDescription>
                  {formData.slug && (
                    <FieldDescription className="text-blue-600">
                      Page URL: /account/{formData.slug}
                    </FieldDescription>
                  )}
                </Field>
                <Field>
                  <label className="flex items-start gap-2 cursor-pointer">
                    <Checkbox
                      id="modal-is_default"
                      checked={formData.is_default === true}
                      onCheckedChange={(checked) =>
                        setFormData((prev) => ({ ...prev, is_default: checked === true }))
                      }
                    />
                    <div>
                      <span className="text-sm font-medium">Set as default page</span>
                      <p className="text-xs text-muted-foreground">
                        The default page is the first non-auth account page used when a signed-in user needs a landing page
                      </p>
                    </div>
                  </label>
                </Field>
              </CardContent>
            </Card>
            <Card>
              <CardHeader className="p-4 pb-3">
                <DashboardModalCardTitle>SEO</DashboardModalCardTitle>
              </CardHeader>
              <CardContent className="grid gap-4 p-4 pt-0">
                <Field>
                  <FieldLabel htmlFor="modal-meta_description">Meta Description</FieldLabel>
                  <Textarea
                    id="modal-meta_description"
                    value={formData.meta_description || ""}
                    onChange={(e) => setFormData((prev) => ({ ...prev, meta_description: e.target.value }))}
                    placeholder="A brief description of this page for search engines"
                    rows={3}
                  />
                  <FieldDescription>
                    Recommended length: 150-160 characters ({(formData.meta_description || "").length}/160)
                  </FieldDescription>
                </Field>
              </CardContent>
            </Card>
          </CardGroup>
        </DashboardModalContent>
      </form>
    </Dialog>
  )
}
