services:
  postgres:
    image: postgres:18
    ports:
      - "${POMODER_POSTGRES_PORT:-54326}:5432"
    environment:
      POSTGRES_PASSWORD: localdev
    volumes:
      - pomoder_pgdata:/var/lib/postgresql

volumes:
  pomoder_pgdata:
