-- One free trial per account.
--
-- Without this, cancelling and subscribing again started a brand new free trial
-- every time, so anyone willing to click cancel once a month never paid.
--
-- The moment the first trial actually begins, and null for an account that has
-- never had one. Written by the Stripe webhook when a trialing subscription
-- arrives, never at checkout: an abandoned checkout must not burn somebody's
-- trial. Written once and never again — the column answers "have they had one",
-- and the *first* one is the answer to that.
--
-- Deliberately not backfilled. Nothing recorded who had already trialled before
-- this existed, and inventing a date would take the trial away from people who
-- never used it. Everyone starts clean and the rule holds from here on.
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "first_trial_at" timestamp with time zone;
