/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin/feedback'
import { Route as AuthenticatedAdminContactsIndexRouteImport } from './routes/_authenticated/admin/contacts/index'
import { Route as AuthenticatedAdminCampaignsIndexRouteImport } from './routes/_authenticated/admin/campaigns/index'
import { Route as AuthenticatedAdminCallsIndexRouteImport } from './routes/_authenticated/admin/calls/index'
import { Route as AuthenticatedAdminAutomationIndexRouteImport } from './routes/_authenticated/admin/automation/index'
import { Route as AuthenticatedAdminAgentsIndexRouteImport } from './routes/_authenticated/admin/agents/index'
import { Route as ApiV1VapiWebhookRouteImport } from './routes/api/v1/vapi/webhook'
import { Route as AuthenticatedAdminSettingsTabRouteImport } from './routes/_authenticated/admin/settings/$tab'
import { Route as AuthenticatedAdminFeedbackCommentsRouteImport } from './routes/_authenticated/admin/feedback/comments'
import { Route as AuthenticatedAdminCampaignsCampaignIdRouteImport } from './routes/_authenticated/admin/campaigns/$campaignId'
import { Route as AuthenticatedAdminAgentsAgentIdRouteImport } from './routes/_authenticated/admin/agents/$agentId'
import { Route as ApiV1MediaMediaIdFileRouteImport } from './routes/api/v1/media/$mediaId/file'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/admin/feedback',
    path: '/admin/feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminContactsIndexRoute =
  AuthenticatedAdminContactsIndexRouteImport.update({
    id: '/admin/contacts/',
    path: '/admin/contacts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCampaignsIndexRoute =
  AuthenticatedAdminCampaignsIndexRouteImport.update({
    id: '/admin/campaigns/',
    path: '/admin/campaigns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCallsIndexRoute =
  AuthenticatedAdminCallsIndexRouteImport.update({
    id: '/admin/calls/',
    path: '/admin/calls/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAutomationIndexRoute =
  AuthenticatedAdminAutomationIndexRouteImport.update({
    id: '/admin/automation/',
    path: '/admin/automation/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAgentsIndexRoute =
  AuthenticatedAdminAgentsIndexRouteImport.update({
    id: '/admin/agents/',
    path: '/admin/agents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiV1VapiWebhookRoute = ApiV1VapiWebhookRouteImport.update({
  id: '/api/v1/vapi/webhook',
  path: '/api/v1/vapi/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSettingsTabRoute =
  AuthenticatedAdminSettingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminFeedbackCommentsRoute =
  AuthenticatedAdminFeedbackCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminFeedbackRoute,
  } as any)
const AuthenticatedAdminCampaignsCampaignIdRoute =
  AuthenticatedAdminCampaignsCampaignIdRouteImport.update({
    id: '/admin/campaigns/$campaignId',
    path: '/admin/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAgentsAgentIdRoute =
  AuthenticatedAdminAgentsAgentIdRouteImport.update({
    id: '/admin/agents/$agentId',
    path: '/admin/agents/$agentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiV1MediaMediaIdFileRoute = ApiV1MediaMediaIdFileRouteImport.update({
  id: '/api/v1/media/$mediaId/file',
  path: '/api/v1/media/$mediaId/file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/agents/$agentId': typeof AuthenticatedAdminAgentsAgentIdRoute
  '/admin/campaigns/$campaignId': typeof AuthenticatedAdminCampaignsCampaignIdRoute
  '/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/api/v1/vapi/webhook': typeof ApiV1VapiWebhookRoute
  '/admin/agents/': typeof AuthenticatedAdminAgentsIndexRoute
  '/admin/automation/': typeof AuthenticatedAdminAutomationIndexRoute
  '/admin/calls/': typeof AuthenticatedAdminCallsIndexRoute
  '/admin/campaigns/': typeof AuthenticatedAdminCampaignsIndexRoute
  '/admin/contacts/': typeof AuthenticatedAdminContactsIndexRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/agents/$agentId': typeof AuthenticatedAdminAgentsAgentIdRoute
  '/admin/campaigns/$campaignId': typeof AuthenticatedAdminCampaignsCampaignIdRoute
  '/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/api/v1/vapi/webhook': typeof ApiV1VapiWebhookRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsIndexRoute
  '/admin/automation': typeof AuthenticatedAdminAutomationIndexRoute
  '/admin/calls': typeof AuthenticatedAdminCallsIndexRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsIndexRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsIndexRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/admin/agents/$agentId': typeof AuthenticatedAdminAgentsAgentIdRoute
  '/_authenticated/admin/campaigns/$campaignId': typeof AuthenticatedAdminCampaignsCampaignIdRoute
  '/_authenticated/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/_authenticated/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/api/v1/vapi/webhook': typeof ApiV1VapiWebhookRoute
  '/_authenticated/admin/agents/': typeof AuthenticatedAdminAgentsIndexRoute
  '/_authenticated/admin/automation/': typeof AuthenticatedAdminAutomationIndexRoute
  '/_authenticated/admin/calls/': typeof AuthenticatedAdminCallsIndexRoute
  '/_authenticated/admin/campaigns/': typeof AuthenticatedAdminCampaignsIndexRoute
  '/_authenticated/admin/contacts/': typeof AuthenticatedAdminContactsIndexRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/workspaces'
    | '/admin/feedback'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/agents/$agentId'
    | '/admin/campaigns/$campaignId'
    | '/admin/feedback/comments'
    | '/admin/settings/$tab'
    | '/api/v1/vapi/webhook'
    | '/admin/agents/'
    | '/admin/automation/'
    | '/admin/calls/'
    | '/admin/campaigns/'
    | '/admin/contacts/'
    | '/api/v1/media/$mediaId/file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/workspaces'
    | '/'
    | '/admin/feedback'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/agents/$agentId'
    | '/admin/campaigns/$campaignId'
    | '/admin/feedback/comments'
    | '/admin/settings/$tab'
    | '/api/v1/vapi/webhook'
    | '/admin/agents'
    | '/admin/automation'
    | '/admin/calls'
    | '/admin/campaigns'
    | '/admin/contacts'
    | '/api/v1/media/$mediaId/file'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/workspaces'
    | '/_authenticated/'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/agents/$agentId'
    | '/_authenticated/admin/campaigns/$campaignId'
    | '/_authenticated/admin/feedback/comments'
    | '/_authenticated/admin/settings/$tab'
    | '/api/v1/vapi/webhook'
    | '/_authenticated/admin/agents/'
    | '/_authenticated/admin/automation/'
    | '/_authenticated/admin/calls/'
    | '/_authenticated/admin/campaigns/'
    | '/_authenticated/admin/contacts/'
    | '/api/v1/media/$mediaId/file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiV1VapiWebhookRoute: typeof ApiV1VapiWebhookRoute
  ApiV1MediaMediaIdFileRoute: typeof ApiV1MediaMediaIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/contacts/': {
      id: '/_authenticated/admin/contacts/'
      path: '/admin/contacts'
      fullPath: '/admin/contacts/'
      preLoaderRoute: typeof AuthenticatedAdminContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/campaigns/': {
      id: '/_authenticated/admin/campaigns/'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns/'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/calls/': {
      id: '/_authenticated/admin/calls/'
      path: '/admin/calls'
      fullPath: '/admin/calls/'
      preLoaderRoute: typeof AuthenticatedAdminCallsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/automation/': {
      id: '/_authenticated/admin/automation/'
      path: '/admin/automation'
      fullPath: '/admin/automation/'
      preLoaderRoute: typeof AuthenticatedAdminAutomationIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/agents/': {
      id: '/_authenticated/admin/agents/'
      path: '/admin/agents'
      fullPath: '/admin/agents/'
      preLoaderRoute: typeof AuthenticatedAdminAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/vapi/webhook': {
      id: '/api/v1/vapi/webhook'
      path: '/api/v1/vapi/webhook'
      fullPath: '/api/v1/vapi/webhook'
      preLoaderRoute: typeof ApiV1VapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/settings/$tab': {
      id: '/_authenticated/admin/settings/$tab'
      path: '/$tab'
      fullPath: '/admin/settings/$tab'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTabRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/feedback/comments': {
      id: '/_authenticated/admin/feedback/comments'
      path: '/comments'
      fullPath: '/admin/feedback/comments'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminFeedbackRoute
    }
    '/_authenticated/admin/campaigns/$campaignId': {
      id: '/_authenticated/admin/campaigns/$campaignId'
      path: '/admin/campaigns/$campaignId'
      fullPath: '/admin/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/agents/$agentId': {
      id: '/_authenticated/admin/agents/$agentId'
      path: '/admin/agents/$agentId'
      fullPath: '/admin/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAdminAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/media/$mediaId/file': {
      id: '/api/v1/media/$mediaId/file'
      path: '/api/v1/media/$mediaId/file'
      fullPath: '/api/v1/media/$mediaId/file'
      preLoaderRoute: typeof ApiV1MediaMediaIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminFeedbackRouteChildren {
  AuthenticatedAdminFeedbackCommentsRoute: typeof AuthenticatedAdminFeedbackCommentsRoute
}

const AuthenticatedAdminFeedbackRouteChildren: AuthenticatedAdminFeedbackRouteChildren =
  {
    AuthenticatedAdminFeedbackCommentsRoute:
      AuthenticatedAdminFeedbackCommentsRoute,
  }

const AuthenticatedAdminFeedbackRouteWithChildren =
  AuthenticatedAdminFeedbackRoute._addFileChildren(
    AuthenticatedAdminFeedbackRouteChildren,
  )

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsTabRoute: typeof AuthenticatedAdminSettingsTabRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsTabRoute: AuthenticatedAdminSettingsTabRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRouteWithChildren
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAdminAgentsAgentIdRoute: typeof AuthenticatedAdminAgentsAgentIdRoute
  AuthenticatedAdminCampaignsCampaignIdRoute: typeof AuthenticatedAdminCampaignsCampaignIdRoute
  AuthenticatedAdminAgentsIndexRoute: typeof AuthenticatedAdminAgentsIndexRoute
  AuthenticatedAdminAutomationIndexRoute: typeof AuthenticatedAdminAutomationIndexRoute
  AuthenticatedAdminCallsIndexRoute: typeof AuthenticatedAdminCallsIndexRoute
  AuthenticatedAdminCampaignsIndexRoute: typeof AuthenticatedAdminCampaignsIndexRoute
  AuthenticatedAdminContactsIndexRoute: typeof AuthenticatedAdminContactsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRouteWithChildren,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
  AuthenticatedAdminAgentsAgentIdRoute: AuthenticatedAdminAgentsAgentIdRoute,
  AuthenticatedAdminCampaignsCampaignIdRoute:
    AuthenticatedAdminCampaignsCampaignIdRoute,
  AuthenticatedAdminAgentsIndexRoute: AuthenticatedAdminAgentsIndexRoute,
  AuthenticatedAdminAutomationIndexRoute:
    AuthenticatedAdminAutomationIndexRoute,
  AuthenticatedAdminCallsIndexRoute: AuthenticatedAdminCallsIndexRoute,
  AuthenticatedAdminCampaignsIndexRoute: AuthenticatedAdminCampaignsIndexRoute,
  AuthenticatedAdminContactsIndexRoute: AuthenticatedAdminContactsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiV1VapiWebhookRoute: ApiV1VapiWebhookRoute,
  ApiV1MediaMediaIdFileRoute: ApiV1MediaMediaIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
