"use client"

import { useState, useEffect } from "react"
import { 
  Dialog,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardGroup, CardHeader } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { MediaPicker } from "@/components/admin/media-library/MediaPicker"
import { CategoryPicker } from "@/components/admin/layout/builder/CategoryPicker"
import { ImageIcon, X, CheckCircle } from "lucide-react"
import { DashboardModalCardTitle, DashboardModalContent, DashboardModalFooterActions } from "@/components/admin/layout/dashboard/modals"
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field"
import { getContentCategoriesAction, bulkAssignCategoriesToContentAction } from "@/lib/actions/categories/category-relationship-actions"
import { generateSlug } from "@/lib/utils/slug"
import type { Post, UpdatePostData } from "@/lib/actions/posts/post-actions"
import type { SiteWithTheme } from "@/lib/actions/sites/site-actions"

interface PostSettingsModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  post: Post | null
  site: SiteWithTheme | null
  onSuccess?: (updatedPost: Post) => void
}

export function PostSettingsModal({ 
  open, 
  onOpenChange, 
  post, 
  onSuccess
}: PostSettingsModalProps) {
  const [formData, setFormData] = useState<UpdatePostData>({})
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [saveMessage, setSaveMessage] = useState<string | null>(null)
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false)
  const [showImagePicker, setShowImagePicker] = useState(false)
  const [selectedCategoryIds, setSelectedCategoryIds] = useState<string[]>([])
  const [primaryCategoryId, setPrimaryCategoryId] = useState<string | null>(null)
  const [loadingCategories, setLoadingCategories] = useState(false)

  // Handle title change and auto-generate slug if slug hasn't been manually edited
  const handleTitleChange = (title: string) => {
    setFormData(prev => ({
      ...prev,
      title,
      slug: slugManuallyEdited ? prev.slug : generateSlug(title)
    }))
  }

  // Handle manual slug changes
  const handleSlugChange = (slug: string) => {
    if (slug === '') {
      // If user clears the field, reset to auto-generation
      setSlugManuallyEdited(false)
      setFormData(prev => ({ ...prev, slug: generateSlug(prev.title || '') }))
    } else {
      setSlugManuallyEdited(true)
      setFormData(prev => ({ ...prev, slug }))
    }
  }

  // Handle featured image changes
  const handleImageChange = async (newImageUrl: string) => {
    setFormData(prev => ({ ...prev, featured_image: newImageUrl }))
  }

  // Handle removing the featured image
  const handleRemoveImage = async () => {
    setFormData(prev => ({ ...prev, featured_image: '' }))
  }


  // Initialize form data when post changes
  useEffect(() => {
    let cancelled = false

    if (post) {
      setFormData({
        title: post.title,
        slug: post.slug,
        meta_description: post.meta_description || '',
        featured_image: post.featured_image || '',
        excerpt: post.excerpt || '',
        is_published: post.is_published
      })
      
      // Check if slug was manually edited (different from auto-generated)
      const autoGeneratedSlug = generateSlug(post.title)
      setSlugManuallyEdited(post.slug !== autoGeneratedSlug)
      
      // Only reset error state, preserve success message if it exists
      setError(null)
      // Don't reset saveMessage here as it clears the success message after save

      setSelectedCategoryIds([])
      setPrimaryCategoryId(null)
      setLoadingCategories(true)
      getContentCategoriesAction(post.id, 'post').then(({ data }) => {
        if (cancelled) return
        if (data) {
          setSelectedCategoryIds(data.map((c) => c.id))
          setPrimaryCategoryId(data.find((c) => c.is_primary)?.id || data[0]?.id || null)
        }
      }).finally(() => {
        if (cancelled) return
        setLoadingCategories(false)
      })
    }

    return () => {
      cancelled = true
    }
  }, [post])

  // Clear messages when modal is closed
  useEffect(() => {
    if (!open) {
      setSaveMessage(null)
      setError(null)
    }
  }, [open])


  // Handle saving as draft
  const handleSaveDraft = async () => {
    if (!formData.title?.trim()) {
      setError('Post title is required')
      return
    }

    if (!post) {
      setError('No post selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)
      
      const draftData = { 
        ...formData, 
        is_published: false
      }
      const response = await fetch(`/api/posts/${post.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(draftData),
      })
      
      const result = await response.json()
      
      if (!response.ok || result.error) {
        setError(result.error || 'Failed to save post as draft')
        return
      }
      
      if (result.data) {
        const categoryResult = await bulkAssignCategoriesToContentAction(post.id, 'post', selectedCategoryIds, primaryCategoryId)
        if (!categoryResult.success) {
          setError(categoryResult.error || 'Failed to save categories')
          return
        }

        setSaveMessage('Post saved as draft')

        // Call success callback
        if (onSuccess) {
          onSuccess({
            ...post,
            ...formData,
            featured_image: formData.featured_image?.trim() || null,
            meta_description: formData.meta_description?.trim() || null,
            excerpt: formData.excerpt?.trim() || null,
            is_published: false,
            content_blocks: post.content_blocks,
            updated_at: new Date().toISOString(),
          })
        }

        // Close modal after successful save
        onOpenChange(false)
      }
    } catch (err) {
      setError('Failed to save post as draft')
    } finally {
      setSaving(false)
    }
  }

  // Handle publishing
  const handlePublish = async () => {
    if (!formData.title?.trim()) {
      setError('Post title is required')
      return
    }

    if (!post) {
      setError('No post selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)
      
      const publishData = { 
        ...formData, 
        is_published: true
      }
      const response = await fetch(`/api/posts/${post.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(publishData),
      })
      
      const result = await response.json()
      
      if (!response.ok || result.error) {
        setError(result.error || 'Failed to publish post')
        return
      }
      
      if (result.data) {
        const categoryResult = await bulkAssignCategoriesToContentAction(post.id, 'post', selectedCategoryIds, primaryCategoryId)
        if (!categoryResult.success) {
          setError(categoryResult.error || 'Failed to save categories')
          return
        }

        setSaveMessage(post?.is_published ? 'Post updated' : 'Post published')

        // Update the form data to reflect the new published state
        setFormData(prev => ({ ...prev, is_published: true }))

        // Call success callback
        if (onSuccess) {
          onSuccess({
            ...post,
            ...formData,
            featured_image: formData.featured_image?.trim() || null,
            meta_description: formData.meta_description?.trim() || null,
            excerpt: formData.excerpt?.trim() || null,
            is_published: true,
            content_blocks: post.content_blocks,
            updated_at: new Date().toISOString(),
          })
        }

        // Close modal after successful save
        onOpenChange(false)
      }
    } catch (err) {
      setError('Failed to publish post')
    } finally {
      setSaving(false)
    }
  }

  // Handle form submission (default to save as draft)
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    await handleSaveDraft()
  }

  if (!post) {
    return null
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DashboardModalContent
        title={(
          <div className="flex min-w-0 items-center gap-3">
            <span className="truncate">{post.title}</span>
            <div className="flex shrink-0 items-center space-x-2">
              <div className={`w-2 h-2 rounded-full ${
                post?.is_published ? 'bg-green-500' : 'bg-gray-400'
              }`} />
              <span className="text-sm font-medium">
                {post?.is_published ? 'Published' : 'Draft'}
              </span>
            </div>
          </div>
        )}
        footerClassName="sm:justify-between"
        footer={(
          <>
            {saveMessage ? (
              <div className="flex items-center gap-2 rounded-md border border-green-200 bg-green-50 px-3 py-1.5">
                <CheckCircle className="w-4 h-4 text-green-600" />
                <span className="text-sm font-medium text-green-700">{saveMessage}</span>
              </div>
            ) : (
              <div />
            )}
            <DashboardModalFooterActions>
              <Button
                type="button"
                variant="outline"
                onClick={() => onOpenChange(false)}
                disabled={saving}
              >
                Cancel
              </Button>
              <Button
                type="submit"
                form="post-settings-form"
                variant="outline"
                disabled={saving}
              >
                {saving ? "Saving..." : "Save as Draft"}
              </Button>
              <Button
                type="button"
                onClick={handlePublish}
                disabled={saving}
              >
                {saving ? (post?.is_published ? "Saving..." : "Publishing...") : (post?.is_published ? "Save" : "Publish")}
              </Button>
            </DashboardModalFooterActions>
          </>
        )}
      >
        <form id="post-settings-form" onSubmit={handleSubmit} className="contents">
          {error && (
            <div className="px-6 pb-2">
              <div className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>
            </div>
          )}

          <CardGroup className="grid">
            <Card>
              <CardHeader>
                <DashboardModalCardTitle>Post details</DashboardModalCardTitle>
                <CardDescription>Name the post, set its URL, image, and summary.</CardDescription>
              </CardHeader>
              <CardContent>
                <Field>
                  <FieldLabel htmlFor="modal-title">Post Title *</FieldLabel>
                  <Input
                    id="modal-title"
                    value={formData.title || ''}
                    onChange={(e) => handleTitleChange(e.target.value)}
                    placeholder="Enter post title"
                    required
                  />
                </Field>

                <Field>
                  <FieldLabel htmlFor="modal-slug">Post URL</FieldLabel>
                  <Input
                    id="modal-slug"
                    value={formData.slug || ''}
                    onChange={(e) => handleSlugChange(e.target.value)}
                    placeholder="post-url-slug"
                  />
                  {slugManuallyEdited && (
                    <FieldDescription>
                      Custom URL slug. Clear this field to auto-generate from title again.
                    </FieldDescription>
                  )}
                </Field>

                <Field className="[&>div]:w-fit">
                  <FieldLabel>Featured Image</FieldLabel>
                  <div>
                    {formData.featured_image ? (
                      <div className="relative aspect-square w-48 rounded-lg overflow-hidden bg-muted">
                        <img
                          src={formData.featured_image}
                          alt="Featured image preview"
                          className="w-full h-full object-cover"
                        />
                        <button
                          type="button"
                          onClick={handleRemoveImage}
                          className="absolute top-2 right-2 p-1 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors"
                        >
                          <X className="h-4 w-4" />
                        </button>
                        <div
                          className="absolute inset-0 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity bg-black/50 cursor-pointer"
                          onClick={() => setShowImagePicker(true)}
                        >
                          <div className="text-white text-center">
                            <ImageIcon className="mx-auto h-8 w-8 mb-2" />
                            <p className="text-sm font-medium">Click to change image</p>
                          </div>
                        </div>
                      </div>
                    ) : (
                      <div
                        className="flex aspect-square w-48 cursor-pointer items-center justify-center rounded-lg border-2 border-dashed border-muted-foreground/25 bg-muted/50 transition-all hover:border-muted-foreground/40 hover:bg-muted/70"
                        onClick={() => setShowImagePicker(true)}
                      >
                        <div className="text-center">
                          <ImageIcon className="mx-auto h-8 w-8 text-muted-foreground/50" />
                          <p className="mt-2 text-sm text-muted-foreground">Click to select featured image</p>
                        </div>
                      </div>
                    )}
                  </div>
                  <FieldDescription>Optional featured image for this post</FieldDescription>
                </Field>

                <Field>
                  <FieldLabel htmlFor="excerpt">Post Excerpt</FieldLabel>
                  <Input
                    id="excerpt"
                    value={formData.excerpt || ''}
                    onChange={(e) => setFormData(prev => ({ ...prev, excerpt: e.target.value }))}
                    placeholder="A brief summary of your post"
                  />
                </Field>
              </CardContent>
            </Card>

            {post?.site_id && (
              <Card>
                <CardHeader>
                  <DashboardModalCardTitle>Categories</DashboardModalCardTitle>
                  <CardDescription>Organize this post by topic.</CardDescription>
                </CardHeader>
                <CardContent>
                  <Field>
                    <FieldLabel>Categories</FieldLabel>
                    <CategoryPicker
                      siteId={post.site_id}
                      selectedCategoryIds={selectedCategoryIds}
                      onSelectionChange={setSelectedCategoryIds}
                      primaryCategoryId={primaryCategoryId}
                      onPrimaryCategoryChange={setPrimaryCategoryId}
                      loadingSelectedCategories={loadingCategories}
                      variant="combobox"
                    />
                  </Field>
                </CardContent>
              </Card>
            )}

            <Card>
              <CardHeader>
                <DashboardModalCardTitle>SEO</DashboardModalCardTitle>
                <CardDescription>Set the search description for this post.</CardDescription>
              </CardHeader>
              <CardContent>
                <Field>
                  <FieldLabel htmlFor="modal-meta_description">Meta Description</FieldLabel>
                  <Textarea
                    id="modal-meta_description"
                    value={formData.meta_description || ''}
                    onChange={(e) => setFormData(prev => ({ ...prev, meta_description: e.target.value }))}
                    placeholder="A brief description of this post for search engines"
                    rows={1}
                    className="min-h-10 [field-sizing:content]"
                  />
                  <FieldDescription>
                    Recommended length: 150-160 characters ({(formData.meta_description || '').length}/160)
                  </FieldDescription>
                </Field>
              </CardContent>
            </Card>
          </CardGroup>
        </form>

        {/* Image Picker Modal */}
        <MediaPicker
          open={showImagePicker}
          onOpenChange={setShowImagePicker}
          onSelectMedia={(imageUrl) => {
            handleImageChange(imageUrl)
            setShowImagePicker(false)
          }}
          currentMediaUrl={formData.featured_image || ''}
        />
      </DashboardModalContent>
    </Dialog>
  )
}
