"use client"

import { useState, useEffect } from "react"
import { 
  Dialog,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { MediaPicker } from "@/components/admin/media-library/MediaPicker"
import { RichTextEditor } from "@/components/admin/layout/builder/RichTextEditor"
import { CategoryPicker } from "@/components/admin/layout/builder/CategoryPicker"
import { ImageIcon, X, CheckCircle } from "lucide-react"
import {
  AdminModalBody,
  AdminModalContent,
  AdminModalFooter,
  AdminModalHeader,
  AdminModalTitle,
} from "@/components/admin/layout/builder/AdminModalLayout"
import { getContentCategoriesAction, bulkAssignCategoriesToContentAction } from "@/lib/actions/categories/category-relationship-actions"
import { generateSlug } from "@/lib/utils/slug"
import type { Post, UpdatePostData } from "@/lib/actions/posts/post-actions"
import type { SiteWithTheme } from "@/lib/actions/sites/site-actions"

interface PostSettingsModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  post: Post | null
  site: SiteWithTheme | null
  onSuccess?: (updatedPost: Post) => void
}

export function PostSettingsModal({ 
  open, 
  onOpenChange, 
  post, 
  site,
  onSuccess
}: PostSettingsModalProps) {
  const [formData, setFormData] = useState<UpdatePostData>({})
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [saveMessage, setSaveMessage] = useState<string | null>(null)
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false)
  const [showImagePicker, setShowImagePicker] = useState(false)
  const [extractedContent, setExtractedContent] = useState('')
  const [showFeaturedImage, setShowFeaturedImage] = useState(true)
  const [selectedCategoryIds, setSelectedCategoryIds] = useState<string[]>([])
  const [primaryCategoryId, setPrimaryCategoryId] = useState<string | null>(null)

  // Handle title change and auto-generate slug if slug hasn't been manually edited
  const handleTitleChange = (title: string) => {
    setFormData(prev => ({
      ...prev,
      title,
      slug: slugManuallyEdited ? prev.slug : generateSlug(title)
    }))
  }

  // Handle manual slug changes
  const handleSlugChange = (slug: string) => {
    if (slug === '') {
      // If user clears the field, reset to auto-generation
      setSlugManuallyEdited(false)
      setFormData(prev => ({ ...prev, slug: generateSlug(prev.title || '') }))
    } else {
      setSlugManuallyEdited(true)
      setFormData(prev => ({ ...prev, slug }))
    }
  }

  // Handle featured image changes
  const handleImageChange = async (newImageUrl: string) => {
    setFormData(prev => ({ ...prev, featured_image: newImageUrl }))
  }

  // Handle removing the featured image
  const handleRemoveImage = async () => {
    setFormData(prev => ({ ...prev, featured_image: '' }))
  }


  // Initialize form data when post changes
  useEffect(() => {
    if (post) {
      // Extract content from content_blocks structure
      let content = ''
      if (post.content_blocks && typeof post.content_blocks === 'object') {
        const blocks = Object.values(post.content_blocks)
        const firstBlock = blocks.find((block: any) => block.type === 'post-content')
        if (firstBlock && firstBlock.content) {
          content = firstBlock.content.body || firstBlock.content.text || ''
        }
      }
      setExtractedContent(content)
      
      // Get show_featured_image from content_blocks
      const showFeaturedImageSetting = (post.content_blocks as any)?.show_featured_image ?? true
      setShowFeaturedImage(showFeaturedImageSetting)
      
      setFormData({
        title: post.title,
        slug: post.slug,
        meta_description: post.meta_description || '',
        featured_image: post.featured_image || '',
        excerpt: post.excerpt || '',
        is_published: post.is_published
      })
      
      // Check if slug was manually edited (different from auto-generated)
      const autoGeneratedSlug = generateSlug(post.title)
      setSlugManuallyEdited(post.slug !== autoGeneratedSlug)
      
      // Only reset error state, preserve success message if it exists
      setError(null)
      // Don't reset saveMessage here as it clears the success message after save

      // Fetch existing category assignments
      getContentCategoriesAction(post.id, 'post').then(({ data }) => {
        if (data) {
          setSelectedCategoryIds(data.map((c) => c.id))
          setPrimaryCategoryId(data.find((c) => c.is_primary)?.id || data[0]?.id || null)
        }
      })
    }
  }, [post])

  // Clear messages when modal is closed
  useEffect(() => {
    if (!open) {
      setSaveMessage(null)
      setError(null)
    }
  }, [open])


  // Handle saving as draft
  const handleSaveDraft = async () => {
    if (!formData.title?.trim()) {
      setError('Post title is required')
      return
    }

    if (!post) {
      setError('No post selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)
      
      const draftData = { 
        ...formData, 
        is_published: false,
        content_blocks: {
          ...post.content_blocks,
          show_featured_image: showFeaturedImage
        }
      }
      const response = await fetch(`/api/posts/${post.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(draftData),
      })
      
      const result = await response.json()
      
      if (!response.ok || result.error) {
        setError(result.error || 'Failed to save post as draft')
        return
      }
      
      if (result.data) {
        const categoryResult = await bulkAssignCategoriesToContentAction(post.id, 'post', selectedCategoryIds, primaryCategoryId)
        if (!categoryResult.success) {
          setError(categoryResult.error || 'Failed to save categories')
          return
        }

        setSaveMessage('Post saved as draft')

        // Call success callback
        if (onSuccess) {
          onSuccess({
            ...post,
            ...formData,
            featured_image: formData.featured_image?.trim() || null,
            meta_description: formData.meta_description?.trim() || null,
            excerpt: formData.excerpt?.trim() || null,
            is_published: false,
            content_blocks: draftData.content_blocks as unknown as Post["content_blocks"],
            updated_at: new Date().toISOString(),
          })
        }

        // Close modal after successful save
        onOpenChange(false)
      }
    } catch (err) {
      setError('Failed to save post as draft')
    } finally {
      setSaving(false)
    }
  }

  // Handle publishing
  const handlePublish = async () => {
    if (!formData.title?.trim()) {
      setError('Post title is required')
      return
    }

    if (!post) {
      setError('No post selected')
      return
    }

    try {
      setSaving(true)
      setError(null)
      setSaveMessage(null)
      
      const publishData = { 
        ...formData, 
        is_published: true,
        content_blocks: {
          ...post.content_blocks,
          show_featured_image: showFeaturedImage
        }
      }
      const response = await fetch(`/api/posts/${post.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(publishData),
      })
      
      const result = await response.json()
      
      if (!response.ok || result.error) {
        setError(result.error || 'Failed to publish post')
        return
      }
      
      if (result.data) {
        const categoryResult = await bulkAssignCategoriesToContentAction(post.id, 'post', selectedCategoryIds, primaryCategoryId)
        if (!categoryResult.success) {
          setError(categoryResult.error || 'Failed to save categories')
          return
        }

        setSaveMessage(post?.is_published ? 'Post updated' : 'Post published')

        // Update the form data to reflect the new published state
        setFormData(prev => ({ ...prev, is_published: true }))

        // Call success callback
        if (onSuccess) {
          onSuccess({
            ...post,
            ...formData,
            featured_image: formData.featured_image?.trim() || null,
            meta_description: formData.meta_description?.trim() || null,
            excerpt: formData.excerpt?.trim() || null,
            is_published: true,
            content_blocks: publishData.content_blocks as unknown as Post["content_blocks"],
            updated_at: new Date().toISOString(),
          })
        }

        // Close modal after successful save
        onOpenChange(false)
      }
    } catch (err) {
      setError('Failed to publish post')
    } finally {
      setSaving(false)
    }
  }

  // Handle form submission (default to save as draft)
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    await handleSaveDraft()
  }

  if (!post) {
    return null
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <AdminModalContent>
        <AdminModalHeader>
          <AdminModalTitle className="flex items-center gap-3">
            Configure settings for &quot;{post.title}&quot;
                <div className="flex items-center space-x-2">
                  <div className={`w-2 h-2 rounded-full ${
                    post?.is_published ? 'bg-green-500' : 'bg-gray-400'
                  }`} />
                  <span className="text-sm font-medium">
                    {post?.is_published ? 'Published' : 'Draft'}
                  </span>
                </div>
              </AdminModalTitle>
            </AdminModalHeader>

        <form onSubmit={handleSubmit} className="flex min-h-0 flex-1 flex-col">
          <AdminModalBody className="space-y-6 [&_label+input]:mt-2 [&_label+textarea]:mt-2">
            {error && (
              <div className="rounded-lg border border-red-200 bg-red-50 p-3">
                <p className="text-sm text-red-800">{error}</p>
              </div>
            )}

          {/* Post Title */}
          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2">
              <Label htmlFor="modal-title">Post Title *</Label>
              <Input
                id="modal-title"
                value={formData.title || ''}
                onChange={(e) => handleTitleChange(e.target.value)}
                placeholder="Enter post title"
                required
              />
            </div>

            {/* Post Slug */}
            <div className="col-span-2">
              <Label htmlFor="modal-slug">Post URL</Label>
            <Input
              id="modal-slug"
              value={formData.slug || ''}
              onChange={(e) => handleSlugChange(e.target.value)}
              placeholder="post-url-slug"
            />
              <p className="mt-1 text-xs text-muted-foreground">
                {slugManuallyEdited
                  ? "Custom URL slug. Clear this field to auto-generate from title again."
                  : "Auto-generated from title. You can edit this to customize the URL."}
              </p>
            </div>
          </div>

          {/* Featured Image */}
          <div>
            <Label htmlFor="featured_image">Featured Image</Label>
            <div className="mt-2">
              {formData.featured_image ? (
                <div className="relative w-48 h-48 rounded-lg overflow-hidden bg-muted">
                  <img
                    src={formData.featured_image}
                    alt="Featured image preview"
                    className="w-full h-full object-contain"
                  />
                  <div className="absolute inset-0 bg-linear-to-t from-background/80 to-transparent" />
                  <button
                    type="button"
                    onClick={handleRemoveImage}
                    className="absolute top-2 right-2 p-1 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors"
                  >
                    <X className="h-4 w-4" />
                  </button>
                  <div className="absolute inset-0 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity bg-black/50 cursor-pointer"
                    onClick={() => setShowImagePicker(true)}
                  >
                    <div className="text-white text-center">
                      <ImageIcon className="mx-auto h-8 w-8 mb-2" />
                      <p className="text-sm font-medium">Click to change image</p>
                    </div>
                  </div>
                </div>
              ) : (
                <div
                  className="flex items-center justify-center w-48 h-48 rounded-lg border-2 border-dashed border-muted-foreground/25 bg-muted/50 cursor-pointer hover:bg-muted/70 hover:border-muted-foreground/40 transition-all"
                  onClick={() => setShowImagePicker(true)}
                >
                  <div className="text-center">
                    <ImageIcon className="mx-auto h-8 w-8 text-muted-foreground/50" />
                    <p className="mt-2 text-sm text-muted-foreground">Click to select featured image</p>
                  </div>
                </div>
              )}
            </div>
            <p className="text-xs text-muted-foreground mt-1">
              Optional featured image for this post
            </p>
          </div>

          {/* Show Featured Image Toggle */}
          {formData.featured_image && (
            <div>
              <div className="flex items-center justify-between">
                <div className="space-y-0.5">
                  <Label htmlFor="show_featured_image">Show featured image on post page</Label>
                  <p className="text-xs text-muted-foreground">
                    Control whether the featured image appears at the top of the post page
                  </p>
                </div>
                <Switch
                  id="show_featured_image"
                  checked={showFeaturedImage}
                  onCheckedChange={setShowFeaturedImage}
                />
              </div>
            </div>
          )}

          {/* Post Excerpt */}
          <div>
            <Label htmlFor="excerpt">Post Excerpt</Label>
            <Input
              id="excerpt"
              value={formData.excerpt || ''}
              onChange={(e) => setFormData(prev => ({ ...prev, excerpt: e.target.value }))}
              placeholder="A brief summary of your post content"
            />
            <p className="mt-1 text-xs text-muted-foreground">
              Brief summary shown in post listings and previews
            </p>
          </div>

          {/* Categories */}
          {post?.site_id && (
            <div>
              <Label>Categories</Label>
              <CategoryPicker
                siteId={post.site_id}
                selectedCategoryIds={selectedCategoryIds}
                onSelectionChange={setSelectedCategoryIds}
                primaryCategoryId={primaryCategoryId}
                onPrimaryCategoryChange={setPrimaryCategoryId}
              />
              <p className="mt-1 text-xs text-muted-foreground">
                Assign this post to one or more categories
              </p>
            </div>
          )}

          {/* Post Content */}
          <div>
            <Label htmlFor="content">Post Content</Label>
            <RichTextEditor
              content={{
                content: extractedContent || '',
                hideHeader: true,
                hideEditorHeader: true
              }}
              onContentChange={(content) => setExtractedContent(content.content)}
              compact={true}
              inline={true}
            />
            <p className="mt-1 text-xs text-muted-foreground">
              Rich text content for the post body
            </p>
          </div>

          {/* Meta Description */}
          <div>
            <Label htmlFor="modal-meta_description">Meta Description</Label>
            <Input
              id="modal-meta_description"
              value={formData.meta_description || ''}
              onChange={(e) => setFormData(prev => ({ ...prev, meta_description: e.target.value }))}
              placeholder="A brief description of this post for search engines"
            />
            <p className="mt-1 text-xs text-muted-foreground">
              Recommended length: 150-160 characters ({(formData.meta_description || '').length}/160)
            </p>
          </div>
          </AdminModalBody>

          <AdminModalFooter>
            {saveMessage && (
              <div className="flex items-center gap-2 rounded-md border border-green-200 bg-green-50 px-3 py-1.5">
                <CheckCircle className="w-4 h-4 text-green-600" />
                <span className="text-sm font-medium text-green-700">{saveMessage}</span>
              </div>
            )}
            {!saveMessage && <div />}
            <div className="flex items-center space-x-2">
              <Button 
                type="button" 
                variant="outline" 
                onClick={() => onOpenChange(false)}
                disabled={saving}
              >
                Cancel
              </Button>
              <Button 
                type="submit" 
                variant="outline"
                disabled={saving}
              >
                {saving ? "Saving..." : "Save as Draft"}
              </Button>
              <Button 
                type="button" 
                onClick={handlePublish}
                disabled={saving}
              >
                {saving ? (post?.is_published ? "Saving..." : "Publishing...") : (post?.is_published ? "Save" : "Publish")}
              </Button>
            </div>
          </AdminModalFooter>
        </form>

        {/* Image Picker Modal */}
        <MediaPicker
          open={showImagePicker}
          onOpenChange={setShowImagePicker}
          onSelectMedia={(imageUrl) => {
            handleImageChange(imageUrl)
            setShowImagePicker(false)
          }}
          currentMediaUrl={formData.featured_image || ''}
        />
      </AdminModalContent>
    </Dialog>
  )
}
