const ROUTE_TITLES: Record<string, string> = {
  "/": "Home",
  "/login": "Sign in",
  "/register": "Create account",
  "/forgot-password": "Forgot password",
  "/reset-password": "Reset password",
  "/sign-in-link": "Sign-in link",
  "/verify-email": "Verify email",
  "/change-email": "Confirm email change",
  "/revoke-email-change": "Revoke email change",
  "/report-unwanted-sign-in": "Report unwanted sign-in",
  "/pricing": "Pricing",
  "/maintenance": "Maintenance",
  "/_authenticated/home": "Home",
  "/_authenticated/account": "Account",
  "/_authenticated/account/billing_/success": "Billing success",
  "/_authenticated/admin/": "Admin dashboard",
  "/_authenticated/admin/dashboard": "Admin dashboard",
  "/_authenticated/admin/users": "Users",
  "/_authenticated/admin/announcements": "Announcements",
  "/_authenticated/admin/ai": "AI",
  "/_authenticated/admin/automations": "Automations",
  "/_authenticated/admin/automations/$automationId": "Automation",
  "/_authenticated/admin/automations/templates": "Automation templates",
  "/_authenticated/admin/automations/templates/$templateKey":
    "Automation template",
  "/_authenticated/admin/ai-usage": "Metered usage",
  "/_authenticated/admin/contacts": "Contacts",
  "/_authenticated/admin/dev-outbox": "Dev outbox",
  "/_authenticated/admin/feedback": "Feedback",
  "/_authenticated/admin/media": "Media",
  "/_authenticated/admin/membership": "Membership",
  "/_authenticated/admin/newsletter": "Newsletters",
  "/_authenticated/admin/newsletter/$broadcastId": "Newsletter",
  "/_authenticated/admin/notifications": "Notifications",
  "/_authenticated/admin/pages": "Pages",
  "/_authenticated/admin/plans": "Plans",
  "/_authenticated/admin/referrals": "Referrals",
  "/_authenticated/admin/segments": "Segments",
  "/_authenticated/admin/settings": "Settings",
  "/_authenticated/admin/settings/$tab": "Settings",
  "/_authenticated/admin/system-emails": "System emails",
  "/_authenticated/admin/system-emails/$kind": "System email",
  "/_authenticated/admin/traffic": "Traffic",
  "/_authenticated/changelog": "Changelog",
  "/_authenticated/changelog/": "Changelog admin",
  "/_authenticated/changelog/whats-new": "What's new",
}

export function routePageTitle(
  routeId: string | undefined,
  workspacesTitle: string
) {
  if (routeId === "/_authenticated/workspaces") return workspacesTitle
  return (routeId && ROUTE_TITLES[routeId]) || "Page"
}
