/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ChangeEmailRouteImport } from './routes/change-email'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInLinkRouteImport } from './routes/sign-in-link'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated/changelog'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin/ai'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminAutomationsRouteImport } from './routes/_authenticated/admin/automations'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin/billing'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin/feedback'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminMembershipRouteImport } from './routes/_authenticated/admin/membership'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin/plans'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminTrafficRouteImport } from './routes/_authenticated/admin/traffic'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedChangelogIndexRouteImport } from './routes/_authenticated/changelog/index'
import { Route as AuthenticatedChangelogWhatsNewRouteImport } from './routes/_authenticated/changelog/whats-new'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as AuthenticatedAccountBillingSuccessRouteImport } from './routes/_authenticated/account/billing_.success'
import { Route as AuthenticatedAdminAutomationsAutomationIdRouteImport } from './routes/_authenticated/admin/automations_.$automationId'
import { Route as AuthenticatedAdminMediaOrphansRouteImport } from './routes/_authenticated/admin/media_.orphans'
import { Route as AuthenticatedAdminMediaStorageRouteImport } from './routes/_authenticated/admin/media_.storage'
import { Route as AuthenticatedAdminSettingsTabRouteImport } from './routes/_authenticated/admin/settings/$tab'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google_.callback'
import { Route as ApiV1TrafficViewRouteImport } from './routes/api/v1/traffic/view'
import { Route as ApiV1MediaMediaIdFileRouteImport } from './routes/api/v1/media/$mediaId/file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeEmailRoute = ChangeEmailRouteImport.update({
  id: '/change-email',
  path: '/change-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInLinkRoute = SignInLinkRouteImport.update({
  id: '/sign-in-link',
  path: '/sign-in-link',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAutomationsRoute =
  AuthenticatedAdminAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMembershipRoute =
  AuthenticatedAdminMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTrafficRoute =
  AuthenticatedAdminTrafficRouteImport.update({
    id: '/traffic',
    path: '/traffic',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedChangelogIndexRoute =
  AuthenticatedChangelogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChangelogRoute,
  } as any)
const AuthenticatedChangelogWhatsNewRoute =
  AuthenticatedChangelogWhatsNewRouteImport.update({
    id: '/whats-new',
    path: '/whats-new',
    getParentRoute: () => AuthenticatedChangelogRoute,
  } as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountBillingSuccessRoute =
  AuthenticatedAccountBillingSuccessRouteImport.update({
    id: '/billing_/success',
    path: '/billing/success',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminAutomationsAutomationIdRoute =
  AuthenticatedAdminAutomationsAutomationIdRouteImport.update({
    id: '/automations_/$automationId',
    path: '/automations/$automationId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaOrphansRoute =
  AuthenticatedAdminMediaOrphansRouteImport.update({
    id: '/media_/orphans',
    path: '/media/orphans',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaStorageRoute =
  AuthenticatedAdminMediaStorageRouteImport.update({
    id: '/media_/storage',
    path: '/media/storage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsTabRoute =
  AuthenticatedAdminSettingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google_/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TrafficViewRoute = ApiV1TrafficViewRouteImport.update({
  id: '/api/v1/traffic/view',
  path: '/api/v1/traffic/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaMediaIdFileRoute = ApiV1MediaMediaIdFileRouteImport.update({
  id: '/api/v1/media/$mediaId/file',
  path: '/api/v1/media/$mediaId/file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-email': typeof ChangeEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in-link': typeof SignInLinkRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/changelog': typeof AuthenticatedChangelogRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/membership': typeof AuthenticatedAdminMembershipRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/changelog/whats-new': typeof AuthenticatedChangelogWhatsNewRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/changelog/': typeof AuthenticatedChangelogIndexRoute
  '/account/billing/success': typeof AuthenticatedAccountBillingSuccessRoute
  '/admin/automations/$automationId': typeof AuthenticatedAdminAutomationsAutomationIdRoute
  '/admin/media/orphans': typeof AuthenticatedAdminMediaOrphansRoute
  '/admin/media/storage': typeof AuthenticatedAdminMediaStorageRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/v1/traffic/view': typeof ApiV1TrafficViewRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-email': typeof ChangeEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in-link': typeof SignInLinkRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/workspaces': typeof AuthenticatedWorkspacesRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/membership': typeof AuthenticatedAdminMembershipRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/changelog/whats-new': typeof AuthenticatedChangelogWhatsNewRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/changelog': typeof AuthenticatedChangelogIndexRoute
  '/account/billing/success': typeof AuthenticatedAccountBillingSuccessRoute
  '/admin/automations/$automationId': typeof AuthenticatedAdminAutomationsAutomationIdRoute
  '/admin/media/orphans': typeof AuthenticatedAdminMediaOrphansRoute
  '/admin/media/storage': typeof AuthenticatedAdminMediaStorageRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/v1/traffic/view': typeof ApiV1TrafficViewRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-email': typeof ChangeEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in-link': typeof SignInLinkRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/changelog': typeof AuthenticatedChangelogRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/membership': typeof AuthenticatedAdminMembershipRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/changelog/whats-new': typeof AuthenticatedChangelogWhatsNewRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/changelog/': typeof AuthenticatedChangelogIndexRoute
  '/_authenticated/account/billing_/success': typeof AuthenticatedAccountBillingSuccessRoute
  '/_authenticated/admin/automations_/$automationId': typeof AuthenticatedAdminAutomationsAutomationIdRoute
  '/_authenticated/admin/media_/orphans': typeof AuthenticatedAdminMediaOrphansRoute
  '/_authenticated/admin/media_/storage': typeof AuthenticatedAdminMediaStorageRoute
  '/_authenticated/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/api/auth/google_/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/v1/traffic/view': typeof ApiV1TrafficViewRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-email'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sign-in-link'
    | '/verify-email'
    | '/account'
    | '/admin'
    | '/changelog'
    | '/home'
    | '/workspaces'
    | '/admin/ai'
    | '/admin/announcements'
    | '/admin/automations'
    | '/admin/billing'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/media'
    | '/admin/membership'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/traffic'
    | '/admin/users'
    | '/changelog/whats-new'
    | '/api/auth/google'
    | '/api/webhooks/stripe'
    | '/admin/'
    | '/changelog/'
    | '/account/billing/success'
    | '/admin/automations/$automationId'
    | '/admin/media/orphans'
    | '/admin/media/storage'
    | '/admin/settings/$tab'
    | '/api/auth/google/callback'
    | '/api/v1/traffic/view'
    | '/api/v1/media/$mediaId/file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-email'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sign-in-link'
    | '/verify-email'
    | '/account'
    | '/home'
    | '/workspaces'
    | '/admin/ai'
    | '/admin/announcements'
    | '/admin/automations'
    | '/admin/billing'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/media'
    | '/admin/membership'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/traffic'
    | '/admin/users'
    | '/changelog/whats-new'
    | '/api/auth/google'
    | '/api/webhooks/stripe'
    | '/admin'
    | '/changelog'
    | '/account/billing/success'
    | '/admin/automations/$automationId'
    | '/admin/media/orphans'
    | '/admin/media/storage'
    | '/admin/settings/$tab'
    | '/api/auth/google/callback'
    | '/api/v1/traffic/view'
    | '/api/v1/media/$mediaId/file'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/change-email'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sign-in-link'
    | '/verify-email'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/changelog'
    | '/_authenticated/home'
    | '/_authenticated/workspaces'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/automations'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/membership'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/traffic'
    | '/_authenticated/admin/users'
    | '/_authenticated/changelog/whats-new'
    | '/api/auth/google'
    | '/api/webhooks/stripe'
    | '/_authenticated/admin/'
    | '/_authenticated/changelog/'
    | '/_authenticated/account/billing_/success'
    | '/_authenticated/admin/automations_/$automationId'
    | '/_authenticated/admin/media_/orphans'
    | '/_authenticated/admin/media_/storage'
    | '/_authenticated/admin/settings/$tab'
    | '/api/auth/google_/callback'
    | '/api/v1/traffic/view'
    | '/api/v1/media/$mediaId/file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangeEmailRoute: typeof ChangeEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInLinkRoute: typeof SignInLinkRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiV1TrafficViewRoute: typeof ApiV1TrafficViewRoute
  ApiV1MediaMediaIdFileRoute: typeof ApiV1MediaMediaIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-email': {
      id: '/change-email'
      path: '/change-email'
      fullPath: '/change-email'
      preLoaderRoute: typeof ChangeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in-link': {
      id: '/sign-in-link'
      path: '/sign-in-link'
      fullPath: '/sign-in-link'
      preLoaderRoute: typeof SignInLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/automations': {
      id: '/_authenticated/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/membership': {
      id: '/_authenticated/admin/membership'
      path: '/membership'
      fullPath: '/admin/membership'
      preLoaderRoute: typeof AuthenticatedAdminMembershipRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/traffic': {
      id: '/_authenticated/admin/traffic'
      path: '/traffic'
      fullPath: '/admin/traffic'
      preLoaderRoute: typeof AuthenticatedAdminTrafficRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/changelog/': {
      id: '/_authenticated/changelog/'
      path: '/'
      fullPath: '/changelog/'
      preLoaderRoute: typeof AuthenticatedChangelogIndexRouteImport
      parentRoute: typeof AuthenticatedChangelogRoute
    }
    '/_authenticated/changelog/whats-new': {
      id: '/_authenticated/changelog/whats-new'
      path: '/whats-new'
      fullPath: '/changelog/whats-new'
      preLoaderRoute: typeof AuthenticatedChangelogWhatsNewRouteImport
      parentRoute: typeof AuthenticatedChangelogRoute
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/billing_/success': {
      id: '/_authenticated/account/billing_/success'
      path: '/billing/success'
      fullPath: '/account/billing/success'
      preLoaderRoute: typeof AuthenticatedAccountBillingSuccessRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/automations_/$automationId': {
      id: '/_authenticated/admin/automations_/$automationId'
      path: '/automations/$automationId'
      fullPath: '/admin/automations/$automationId'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsAutomationIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media_/orphans': {
      id: '/_authenticated/admin/media_/orphans'
      path: '/media/orphans'
      fullPath: '/admin/media/orphans'
      preLoaderRoute: typeof AuthenticatedAdminMediaOrphansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media_/storage': {
      id: '/_authenticated/admin/media_/storage'
      path: '/media/storage'
      fullPath: '/admin/media/storage'
      preLoaderRoute: typeof AuthenticatedAdminMediaStorageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/$tab': {
      id: '/_authenticated/admin/settings/$tab'
      path: '/$tab'
      fullPath: '/admin/settings/$tab'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTabRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/api/auth/google_/callback': {
      id: '/api/auth/google_/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/traffic/view': {
      id: '/api/v1/traffic/view'
      path: '/api/v1/traffic/view'
      fullPath: '/api/v1/traffic/view'
      preLoaderRoute: typeof ApiV1TrafficViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/$mediaId/file': {
      id: '/api/v1/media/$mediaId/file'
      path: '/api/v1/media/$mediaId/file'
      fullPath: '/api/v1/media/$mediaId/file'
      preLoaderRoute: typeof ApiV1MediaMediaIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountBillingSuccessRoute: typeof AuthenticatedAccountBillingSuccessRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountBillingSuccessRoute:
    AuthenticatedAccountBillingSuccessRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsTabRoute: typeof AuthenticatedAdminSettingsTabRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsTabRoute: AuthenticatedAdminSettingsTabRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminAutomationsRoute: typeof AuthenticatedAdminAutomationsRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMembershipRoute: typeof AuthenticatedAdminMembershipRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAdminTrafficRoute: typeof AuthenticatedAdminTrafficRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAutomationsAutomationIdRoute: typeof AuthenticatedAdminAutomationsAutomationIdRoute
  AuthenticatedAdminMediaOrphansRoute: typeof AuthenticatedAdminMediaOrphansRoute
  AuthenticatedAdminMediaStorageRoute: typeof AuthenticatedAdminMediaStorageRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminAutomationsRoute: AuthenticatedAdminAutomationsRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminMembershipRoute: AuthenticatedAdminMembershipRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
  AuthenticatedAdminTrafficRoute: AuthenticatedAdminTrafficRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAutomationsAutomationIdRoute:
    AuthenticatedAdminAutomationsAutomationIdRoute,
  AuthenticatedAdminMediaOrphansRoute: AuthenticatedAdminMediaOrphansRoute,
  AuthenticatedAdminMediaStorageRoute: AuthenticatedAdminMediaStorageRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedChangelogRouteChildren {
  AuthenticatedChangelogWhatsNewRoute: typeof AuthenticatedChangelogWhatsNewRoute
  AuthenticatedChangelogIndexRoute: typeof AuthenticatedChangelogIndexRoute
}

const AuthenticatedChangelogRouteChildren: AuthenticatedChangelogRouteChildren =
  {
    AuthenticatedChangelogWhatsNewRoute: AuthenticatedChangelogWhatsNewRoute,
    AuthenticatedChangelogIndexRoute: AuthenticatedChangelogIndexRoute,
  }

const AuthenticatedChangelogRouteWithChildren =
  AuthenticatedChangelogRoute._addFileChildren(
    AuthenticatedChangelogRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedChangelogRoute: AuthenticatedChangelogRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangeEmailRoute: ChangeEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInLinkRoute: SignInLinkRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiV1TrafficViewRoute: ApiV1TrafficViewRoute,
  ApiV1MediaMediaIdFileRoute: ApiV1MediaMediaIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
