/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminFeedbackRouteImport } from './routes/_authenticated/admin/feedback'
import { Route as AuthenticatedAdminSettingsTabRouteImport } from './routes/_authenticated/admin/settings/$tab'
import { Route as AuthenticatedAdminMediaVideosRouteImport } from './routes/_authenticated/admin/media/videos'
import { Route as AuthenticatedAdminMediaImagesRouteImport } from './routes/_authenticated/admin/media/images'
import { Route as AuthenticatedAdminFeedbackCommentsRouteImport } from './routes/_authenticated/admin/feedback/comments'
import { Route as ApiV1MediaMediaIdFileRouteImport } from './routes/api/v1/media/$mediaId/file'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminFeedbackRoute =
  AuthenticatedAdminFeedbackRouteImport.update({
    id: '/admin/feedback',
    path: '/admin/feedback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsTabRoute =
  AuthenticatedAdminSettingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminMediaVideosRoute =
  AuthenticatedAdminMediaVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminMediaRoute,
  } as any)
const AuthenticatedAdminMediaImagesRoute =
  AuthenticatedAdminMediaImagesRouteImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => AuthenticatedAdminMediaRoute,
  } as any)
const AuthenticatedAdminFeedbackCommentsRoute =
  AuthenticatedAdminFeedbackCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminFeedbackRoute,
  } as any)
const ApiV1MediaMediaIdFileRoute = ApiV1MediaMediaIdFileRouteImport.update({
  id: '/api/v1/media/$mediaId/file',
  path: '/api/v1/media/$mediaId/file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminMediaRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/admin/media/images': typeof AuthenticatedAdminMediaImagesRoute
  '/admin/media/videos': typeof AuthenticatedAdminMediaVideosRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/admin/media': typeof AuthenticatedAdminMediaRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/admin/media/images': typeof AuthenticatedAdminMediaImagesRoute
  '/admin/media/videos': typeof AuthenticatedAdminMediaVideosRoute
  '/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/feedback': typeof AuthenticatedAdminFeedbackRouteWithChildren
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/admin/feedback/comments': typeof AuthenticatedAdminFeedbackCommentsRoute
  '/_authenticated/admin/media/images': typeof AuthenticatedAdminMediaImagesRoute
  '/_authenticated/admin/media/videos': typeof AuthenticatedAdminMediaVideosRoute
  '/_authenticated/admin/settings/$tab': typeof AuthenticatedAdminSettingsTabRoute
  '/api/v1/media/$mediaId/file': typeof ApiV1MediaMediaIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/feedback'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/feedback/comments'
    | '/admin/media/images'
    | '/admin/media/videos'
    | '/admin/settings/$tab'
    | '/api/v1/media/$mediaId/file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/admin/feedback'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/feedback/comments'
    | '/admin/media/images'
    | '/admin/media/videos'
    | '/admin/settings/$tab'
    | '/api/v1/media/$mediaId/file'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/admin/feedback'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/feedback/comments'
    | '/_authenticated/admin/media/images'
    | '/_authenticated/admin/media/videos'
    | '/_authenticated/admin/settings/$tab'
    | '/api/v1/media/$mediaId/file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiV1MediaMediaIdFileRoute: typeof ApiV1MediaMediaIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/feedback': {
      id: '/_authenticated/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings/$tab': {
      id: '/_authenticated/admin/settings/$tab'
      path: '/$tab'
      fullPath: '/admin/settings/$tab'
      preLoaderRoute: typeof AuthenticatedAdminSettingsTabRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/media/videos': {
      id: '/_authenticated/admin/media/videos'
      path: '/videos'
      fullPath: '/admin/media/videos'
      preLoaderRoute: typeof AuthenticatedAdminMediaVideosRouteImport
      parentRoute: typeof AuthenticatedAdminMediaRoute
    }
    '/_authenticated/admin/media/images': {
      id: '/_authenticated/admin/media/images'
      path: '/images'
      fullPath: '/admin/media/images'
      preLoaderRoute: typeof AuthenticatedAdminMediaImagesRouteImport
      parentRoute: typeof AuthenticatedAdminMediaRoute
    }
    '/_authenticated/admin/feedback/comments': {
      id: '/_authenticated/admin/feedback/comments'
      path: '/comments'
      fullPath: '/admin/feedback/comments'
      preLoaderRoute: typeof AuthenticatedAdminFeedbackCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminFeedbackRoute
    }
    '/api/v1/media/$mediaId/file': {
      id: '/api/v1/media/$mediaId/file'
      path: '/api/v1/media/$mediaId/file'
      fullPath: '/api/v1/media/$mediaId/file'
      preLoaderRoute: typeof ApiV1MediaMediaIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminFeedbackRouteChildren {
  AuthenticatedAdminFeedbackCommentsRoute: typeof AuthenticatedAdminFeedbackCommentsRoute
}

const AuthenticatedAdminFeedbackRouteChildren: AuthenticatedAdminFeedbackRouteChildren =
  {
    AuthenticatedAdminFeedbackCommentsRoute:
      AuthenticatedAdminFeedbackCommentsRoute,
  }

const AuthenticatedAdminFeedbackRouteWithChildren =
  AuthenticatedAdminFeedbackRoute._addFileChildren(
    AuthenticatedAdminFeedbackRouteChildren,
  )

interface AuthenticatedAdminMediaRouteChildren {
  AuthenticatedAdminMediaImagesRoute: typeof AuthenticatedAdminMediaImagesRoute
  AuthenticatedAdminMediaVideosRoute: typeof AuthenticatedAdminMediaVideosRoute
}

const AuthenticatedAdminMediaRouteChildren: AuthenticatedAdminMediaRouteChildren =
  {
    AuthenticatedAdminMediaImagesRoute: AuthenticatedAdminMediaImagesRoute,
    AuthenticatedAdminMediaVideosRoute: AuthenticatedAdminMediaVideosRoute,
  }

const AuthenticatedAdminMediaRouteWithChildren =
  AuthenticatedAdminMediaRoute._addFileChildren(
    AuthenticatedAdminMediaRouteChildren,
  )

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsTabRoute: typeof AuthenticatedAdminSettingsTabRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsTabRoute: AuthenticatedAdminSettingsTabRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminFeedbackRoute: typeof AuthenticatedAdminFeedbackRouteWithChildren
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminFeedbackRoute: AuthenticatedAdminFeedbackRouteWithChildren,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiV1MediaMediaIdFileRoute: ApiV1MediaMediaIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
